// Offline conversion from the official downloads retained in the audit cache.
// Usage: node convert.mjs <audit-cache> <repository-root>
import {readFileSync,writeFileSync,copyFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {createHash} from 'node:crypto';

const [cache,root]=process.argv.slice(2);
if(!cache||!root)throw new Error('Provide audit-cache and repository-root paths.');
const raw=join(root,'data-source/atlas/canada-census-2021');
const assets=join(root,'public/assets/atlas/canada-census-agriculture-v1');
mkdirSync(raw,{recursive:true});mkdirSync(assets,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
const statLicence={name:'Statistics Canada Open Licence',url:'https://www.statcan.gc.ca/en/terms-conditions/open-licence'};
const geometryLicence={name:'Open Government Licence - Canada',url:'https://open.canada.ca/en/open-government-licence-canada'};
const tableUrl=id=>`https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=${id}01`;
const definitions={
 canola:{label:'カノーラ',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Canola (rapeseed)'],definition:'カノーラ（なたね）の地域別申告面積。'},
 wheat:{label:'小麦',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Wheat, total'],definition:'春小麦（デュラムを除く）・デュラム小麦・冬小麦を含む小麦の地域別申告面積。'},
 beef:{label:'肉用母牛',unit:'頭',unitLabel:'母牛頭数（頭）',table:'32100370',variables:['Cows, beef'],definition:'肉用の母牛頭数。子牛・育成牛・肥育牛・乳牛を含む牛の総頭数ではない。'},
 pasture:{label:'放牧地',unit:'ha',unitLabel:'申告面積（ha）',table:'32100249',variables:['Tame or seeded pasture','Natural land for pasture'],definition:'栽培・播種した放牧地と自然の放牧地の申告面積を合算。'},
 hay:{label:'干草・栽培牧草（アルファルファ＋その他）',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Alfalfa and alfalfa mixtures','All other tame hay and fodder crops'],definition:'アルファルファおよびその混播牧草と、その他の栽培干草・飼料作物の申告面積を合算。採種用牧草は含めない。'},
 soybeans:{label:'大豆',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Soybeans'],definition:'大豆の地域別申告面積。収穫量や輸出量ではない。'},
 corn:{label:'とうもろこし',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Corn, total'],definition:'子実用とサイレージ用を含むとうもろこしの総申告面積。子実収穫量ではない。'},
 lentils:{label:'レンズ豆',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Lentils'],definition:'レンズ豆の地域別申告面積。えんどうや他の豆類を含まない。'},
 potatoes:{label:'ばれいしょ',unit:'ha',unitLabel:'申告面積（ha）',table:'32100309',variables:['Potatoes'],definition:'ばれいしょの地域別申告面積。加工品の生産量・輸出量とは区別する。'},
 dairy:{label:'乳牛',unit:'頭',unitLabel:'乳牛頭数（頭）',table:'32100370',variables:['Cows, dairy'],definition:'乳用の牛の頭数。牛乳の産出量ではなく、酪農の飼養分布を表す。'}
};
const componentIds={'Canola (rapeseed)':'canola','Wheat, total':'wheat','Cows, beef':'beef','Tame or seeded pasture':'tame-pasture','Natural land for pasture':'natural-pasture','Alfalfa and alfalfa mixtures':'alfalfa-hay','All other tame hay and fodder crops':'other-hay','Soybeans':'soybeans','Corn, total':'corn','Lentils':'lentils','Potatoes':'potatoes','Cows, dairy':'dairy'};
function parseLine(line){const fields=[];let text='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){text+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){fields.push(text);text='';}else text+=c;}fields.push(text);return fields;}
const tables=[],sourceCells=new Map(),sourceGeographies=new Map();
for(const tableId of ['32100309','32100370','32100249']){
 const zip=readFileSync(join(cache,`${tableId}.zip`));copyFileSync(join(cache,`${tableId}.zip`),join(raw,`${tableId}-eng.zip`));
 const csv=readFileSync(join(cache,tableId,`${tableId}.csv`));const lines=csv.toString('utf8').replace(/^\uFEFF/,'').split(/\r?\n/);const header=lines.shift();const names=parseLine(header),index=Object.fromEntries(names.map((name,i)=>[name,i]));const variables=Object.values(definitions).filter(d=>d.table===tableId).flatMap(d=>d.variables);const selected=[];
 for(const line of lines){if(!line||!variables.some(v=>line.includes(`"${v}"`)))continue;const r=parseLine(line);const dguid=r[index.DGUID];if(!(dguid.startsWith('2021S0502')||dguid.startsWith('2021A0002')||dguid==='2021A000011124'))continue;
  const variable=r[3];if(!variables.includes(variable))continue;const expectedUnit=tableId==='32100370'?'Number of animals':'Hectares';if(r[index['Unit of measure']]!==expectedUnit)continue;
  if(r[index.REF_DATE]!=='2021'||r[index.SCALAR_FACTOR]!=='units'||r[index.UOM]!=='Number')throw new Error(`Unexpected period/unit/scalar: ${line}`);
  const quality=r[index.STATUS],value=r[index.VALUE]===''?null:Number(r[index.VALUE]);if(!/^[A-F]$/.test(quality)||quality==='F'&&value!==null||quality!=='F'&&value===null||value!==null&&(!Number.isFinite(value)||value<0))throw new Error(`Unexpected value/quality: ${line}`);
  const key=`${dguid}|${tableId}|${variable}`;if(sourceCells.has(key))throw new Error(`Duplicate source cell: ${key}`);
  sourceCells.set(key,{id:componentIds[variable],variable,value,quality,vector:r[index.VECTOR],coordinate:r[index.COORDINATE],unit:expectedUnit,symbol:r[index.SYMBOL],decimals:Number(r[index.DECIMALS])});sourceGeographies.set(dguid,r[index.GEO]);selected.push(line);
 }
 const selectedBuffer=Buffer.from(`${header}\n${selected.join('\n')}\n`);writeFileSync(join(raw,`${tableId}-selected.csv`),selectedBuffer);
 const metadata=readFileSync(join(cache,tableId,`${tableId}_MetaData.csv`));writeFileSync(join(raw,`${tableId}-metadata.csv`),metadata);
 tables.push({id:tableId,tableId:tableId.replace(/^(\d{2})(\d{2})(\d{4})$/,'$1-$2-$3-01'),url:tableUrl(tableId),download:`https://www150.statcan.gc.ca/n1/tbl/csv/${tableId}-eng.zip`,releasedAt:'2022-05-11',referenceYear:2021,licence:statLicence,archive:{file:`${tableId}-eng.zip`,bytes:zip.length,sha256:sha(zip)},csv:{sha256:sha(csv),rows:lines.filter(Boolean).length},selected:{file:`${tableId}-selected.csv`,rows:selected.length,sha256:sha(selectedBuffer)},metadata:{file:`${tableId}-metadata.csv`,sha256:sha(metadata)}});
}
const geometryBytes=readFileSync(join(cache,'ccs-geo.json'));copyFileSync(join(cache,'ccs-geo.json'),join(raw,'ccs-source-4326.geojson'));copyFileSync(join(cache,'ccs-geo.json'),join(assets,'ccs.geojson'));
const geo=JSON.parse(geometryBytes);if(geo.features.length!==1757)throw new Error('Expected all 1,757 official CCS polygons.');
const archive=readFileSync(join(cache,'leca000e21a_e.zip'));writeFileSync(join(raw,'leca000e21a_e.zip'),archive);copyFileSync(join(cache,'ccs-layer.json'),join(raw,'ccs-source-layer.json'));
let vertexCount=0;const bounds=[180,90,-180,-90];function countCoordinates(c){if(typeof c[0]==='number'){if(c.length!==2||!c.every(Number.isFinite))throw new Error('Invalid official coordinate');vertexCount++;bounds[0]=Math.min(bounds[0],c[0]);bounds[1]=Math.min(bounds[1],c[1]);bounds[2]=Math.max(bounds[2],c[0]);bounds[3]=Math.max(bounds[3],c[1]);}else c.forEach(countCoordinates);}
const regionKeys=new Set();for(const f of geo.features){if(regionKeys.has(f.properties.DGUID))throw new Error('Duplicate geometry key');regionKeys.add(f.properties.DGUID);countCoordinates(f.geometry.coordinates);}
const publishedKeys=[...sourceGeographies.keys()].filter(k=>k.startsWith('2021S0502'));if(publishedKeys.length!==1747||publishedKeys.some(k=>!regionKeys.has(k)))throw new Error('Published CCS DGUID join failed.');
function cell(dguid,definition){const components=definition.variables.map(v=>sourceCells.get(`${dguid}|${definition.table}|${v}`));if(components.some(c=>!c)){if(components.some(Boolean))throw new Error(`Partial geography coverage: ${dguid}`);return{value:null,quality:null,status:'not-covered',components:[]};}const unpublished=components.some(c=>c.quality==='F');return{value:unpublished?null:components.reduce((sum,c)=>sum+c.value,0),quality:components.length===1?components[0].quality:null,status:unpublished?'quality-f':'published',components};}
const source={name:'Statistics Canada, Census of Agriculture, 2021',url:'https://www150.statcan.gc.ca/n1/pub/32-26-0004/322600042021001-eng.htm',releasedAt:'2022-05-11',referenceDate:'2021-05-11',accessedAt:'2026-10-02',licence:statLicence,attribution:'Adapted from Statistics Canada, Census of Agriculture, 2021. This does not constitute an endorsement by Statistics Canada of this product.',geographicMeaning:'農場の本拠地があるCCSに集計された申告面積・頭数。複数地域にまたがる圃場も本拠地域に集計され、実際の畑・農場・牛の所在地を表すものではない。',geographicRuleUrl:'https://www150.statcan.gc.ca/n1/pub/32-26-0002/322600022021001-eng.htm',randomTabularAdjustment:'2021年農業センサスのRTA調整済み公表値。地域値から全国・州の公表値を再計算しない。',qualityUrl:'https://www150.statcan.gc.ca/n1/pub/32-26-0007/322600072021001-eng.htm',nationalCoverage:'カナダ全国の公表値に準州は含まれない。'};
const geometry={url:'/assets/atlas/canada-census-agriculture-v1/ccs.geojson',idProperty:'DGUID',featureCount:1757,sourceName:'2021 Census Consolidated Subdivision Generalized Cartographic Boundary File',sourceUrl:'https://www150.statcan.gc.ca/n1/pub/92-639-g/92-639-g2021001-eng.htm',serviceUrl:'https://geo.statcan.gc.ca/geo_wa/rest/services/2021/Agricultural_ecumene_boundary_files/MapServer/1',queryUrl:'https://geo.statcan.gc.ca/geo_wa/rest/services/2021/Agricultural_ecumene_boundary_files/MapServer/1/query?where=1%3D1&outFields=CCSUID,CCSNAME,DGUID,PRUID&returnGeometry=true&outSR=4326&f=geojson',downloadUrl:'https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/files-fichiers/leca000e21a_e.zip',sourceCrs:'EPSG:3347',crs:'EPSG:4326',releasedAt:'2022-09-27',referenceDate:'2021-01-01',accessedAt:'2026-10-02',sourceGeneralizationMetres:5000,bytes:geometryBytes.length,sha256:sha(geometryBytes),vertexCount,vertexMethod:'Count every original position in all Polygon/MultiPolygon rings, including closing positions; no coordinate rounding or simplification.',bounds,method:'Official REST output in WGS84 copied byte-for-byte. No additional simplification, tracing, coordinate approximation or invented points. Polygons represent statistical administrative regions, not cultivated parcels.',licence:geometryLicence,attribution:'Contains information licensed under the Open Government Licence – Canada. Source: Statistics Canada, Agricultural Ecumene Boundary File, 2021.',archive:{file:'leca000e21a_e.zip',bytes:archive.length,sha256:sha(archive)}};
const products=Object.fromEntries(Object.entries(definitions).map(([id,d])=>[id,{id,label:d.label,displayName:d.label,unit:d.unit,unitLabel:d.unitLabel,sourceTableId:d.table,sourceTableUrl:tableUrl(d.table),sourceVariables:d.variables,releasedAt:'2022-05-11',definition:d.definition,national:cell('2021A000011124',d),derived:d.variables.length>1,notes:d.variables.length>1?'公表された成分を合算。いずれかが品質Fなら合算値も不公表。合算値に公式品質等級は付与せず、各成分の品質を保持する。':'公表値と公式品質等級を保持する。'}]));
products.hay.originalTotalHay={value:5394265,unit:'ha',year:2021,source:'https://www150.statcan.gc.ca/n1/pub/95-634-x/2021001/article/00001/catm-ctra-037-eng.htm',comparable:false,note:'原図のTotal hayとは定義の異なる2成分合算。原図の全国値をこの指標へ流用しない。'};
const records=Object.fromEntries(geo.features.map(f=>{const p=f.properties;return[p.DGUID,{uid:p.CCSUID,name:p.CCSNAME,provinceCode:p.PRUID,covered:sourceGeographies.has(p.DGUID),cells:Object.fromEntries(Object.entries(definitions).map(([id,d])=>[id,cell(p.DGUID,d)]))}];}));
const provinces=[...sourceGeographies].filter(([k])=>k.startsWith('2021A0002')).map(([dguid,name])=>({code:dguid.slice(-2),name:name.replace(/\s*\[[^\]]+\]$/,''),dguid,cells:Object.fromEntries(Object.entries(definitions).map(([id,d])=>[id,cell(dguid,d)]))}));
const data={schemaVersion:1,id:'canada-census-agriculture-2021',year:2021,source,attribution:source.attribution,licence:statLicence,geometry,products,geography:{level:'Census consolidated subdivision',abbreviation:'CCS',publishedRegions:1747,notCoveredRegions:10,join:'Exact DGUID equality',meaning:source.geographicMeaning},quality:{A:'優良（CV 5%未満）',B:'良好（CV 5〜9.99%）',C:'良好（CV 10〜14.99%）',D:'許容範囲（CV 15〜24.99%）',E:'注意して使用（CV 25〜49.99%）',F:'品質上の理由で不公表（CV 50%以上）'},provinces,records};
const json=Buffer.from(JSON.stringify(data));writeFileSync(join(root,'src/data/atlas/canada/census-agriculture.json'),json);writeFileSync(join(assets,'census-agriculture.json'),json);
const counts=Object.fromEntries(Object.keys(products).map(id=>{const cells=Object.values(records).map(r=>r.cells[id]);return[id,{published:cells.filter(c=>c.status==='published').length,qualityF:cells.filter(c=>c.status==='quality-f').length,notCovered:cells.filter(c=>c.status==='not-covered').length,zero:cells.filter(c=>c.value===0).length}];}));
const manifest={id:data.id,schemaVersion:1,accessedAt:'2026-10-02',referenceYear:2021,source,statistics:{tables,dimensionFilter:{referenceDate:'2021',unitDimension:'Unit of measure',areaUnit:'Hectares',animalUnit:'Number of animals',uomColumn:'Number',scalarFactor:'units'},selectionMethod:'Retain original CSV row text for 2021 official Canada, province and CCS source cells of the explicitly named variables. Join CCS by DGUID only; retain exact numeric values, zero, quality, vector and coordinate. Never derive values from map dots or aggregate regions into government totals.',counts,publishedRegionCount:1747,geometryRegionCount:1757,unmatchedPublishedDguids:[]},geometry,products,output:{data:{file:'census-agriculture.json',bytes:json.length,sha256:sha(json)},geometry:{file:'ccs.geojson',bytes:geometryBytes.length,sha256:sha(geometryBytes)}}};
const manifestText=JSON.stringify(manifest,null,2)+'\n';writeFileSync(join(assets,'manifest.json'),manifestText);writeFileSync(join(raw,'manifest.json'),manifestText);
console.log(JSON.stringify({dataBytes:json.length,geometryBytes:geometryBytes.length,geometryVertices:vertexCount,records:Object.keys(records).length,counts,products:Object.fromEntries(Object.entries(products).map(([id,p])=>[id,p.national.value]))},null,2));
