// Generated by scripts/atlas-asia-climate.py from the pinned source legend.
export type AsiaClimateClass = { id:number; code:string; name:string; color:string; description:string; group:'熱帯'|'乾燥帯'|'温帯'|'冷帯'|'寒帯'; sourceLabel:string };
export const asiaClimateClasses: AsiaClimateClass[] = [
  {
    "id": 1,
    "code": "Af",
    "name": "熱帯雨林気候",
    "color": "#0000ff",
    "description": "明瞭な乾季がない熱帯の区分。",
    "group": "熱帯",
    "sourceLabel": "Tropical, rainforest"
  },
  {
    "id": 2,
    "code": "Am",
    "name": "熱帯モンスーン気候",
    "color": "#0078ff",
    "description": "短い乾季を持つ、降水量の多い熱帯の区分。",
    "group": "熱帯",
    "sourceLabel": "Tropical, monsoon"
  },
  {
    "id": 3,
    "code": "Aw",
    "name": "サバナ気候",
    "color": "#46aafa",
    "description": "乾季を持つ熱帯の区分。",
    "group": "熱帯",
    "sourceLabel": "Tropical, savannah"
  },
  {
    "id": 4,
    "code": "BWh",
    "name": "高温の砂漠気候",
    "color": "#ff0000",
    "description": "乾燥帯のうち、高温の砂漠気候に当たる区分。",
    "group": "乾燥帯",
    "sourceLabel": "Arid, desert, hot"
  },
  {
    "id": 5,
    "code": "BWk",
    "name": "低温の砂漠気候",
    "color": "#ff9696",
    "description": "乾燥帯のうち、低温の砂漠気候に当たる区分。",
    "group": "乾燥帯",
    "sourceLabel": "Arid, desert, cold"
  },
  {
    "id": 6,
    "code": "BSh",
    "name": "高温のステップ気候",
    "color": "#f5a500",
    "description": "乾燥帯のうち、高温の半乾燥気候に当たる区分。",
    "group": "乾燥帯",
    "sourceLabel": "Arid, steppe, hot"
  },
  {
    "id": 7,
    "code": "BSk",
    "name": "低温のステップ気候",
    "color": "#ffdc64",
    "description": "乾燥帯のうち、低温の半乾燥気候に当たる区分。",
    "group": "乾燥帯",
    "sourceLabel": "Arid, steppe, cold"
  },
  {
    "id": 8,
    "code": "Csa",
    "name": "夏に乾燥する高温夏の温帯",
    "color": "#ffff00",
    "description": "夏に乾燥し、夏の気温が高い温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, dry summer, hot summer"
  },
  {
    "id": 9,
    "code": "Csb",
    "name": "夏に乾燥する温暖夏の温帯",
    "color": "#c8c800",
    "description": "夏に乾燥し、夏が温暖な温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, dry summer, warm summer"
  },
  {
    "id": 10,
    "code": "Csc",
    "name": "夏に乾燥する冷夏の温帯",
    "color": "#969600",
    "description": "夏に乾燥し、夏が短く涼しい温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, dry summer, cold summer"
  },
  {
    "id": 11,
    "code": "Cwa",
    "name": "冬に乾燥する高温夏の温帯",
    "color": "#96ff96",
    "description": "冬に乾燥し、夏の気温が高い温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, dry winter, hot summer"
  },
  {
    "id": 12,
    "code": "Cwb",
    "name": "冬に乾燥する温暖夏の温帯",
    "color": "#64c864",
    "description": "冬に乾燥し、夏が温暖な温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, dry winter, warm summer"
  },
  {
    "id": 13,
    "code": "Cwc",
    "name": "冬に乾燥する冷夏の温帯",
    "color": "#329632",
    "description": "冬に乾燥し、夏が短く涼しい温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, dry winter, cold summer"
  },
  {
    "id": 14,
    "code": "Cfa",
    "name": "温暖湿潤気候",
    "color": "#c8ff50",
    "description": "明瞭な乾季がなく、夏の気温が高い温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, no dry season, hot summer"
  },
  {
    "id": 15,
    "code": "Cfb",
    "name": "西岸海洋性気候",
    "color": "#64ff50",
    "description": "明瞭な乾季がなく、夏が温暖な温帯の区分。名称は海岸からの距離を示すものではない。",
    "group": "温帯",
    "sourceLabel": "Temperate, no dry season, warm summer"
  },
  {
    "id": 16,
    "code": "Cfc",
    "name": "乾季のない冷夏の温帯",
    "color": "#32c800",
    "description": "明瞭な乾季がなく、夏が短く涼しい温帯の区分。",
    "group": "温帯",
    "sourceLabel": "Temperate, no dry season, cold summer"
  },
  {
    "id": 17,
    "code": "Dsa",
    "name": "夏に乾燥する高温夏の冷帯",
    "color": "#ff00ff",
    "description": "寒い冬と高温の夏を持ち、夏に乾燥する冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry summer, hot summer"
  },
  {
    "id": 18,
    "code": "Dsb",
    "name": "夏に乾燥する温暖夏の冷帯",
    "color": "#c800c8",
    "description": "寒い冬と温暖な夏を持ち、夏に乾燥する冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry summer, warm summer"
  },
  {
    "id": 19,
    "code": "Dsc",
    "name": "夏に乾燥する冷夏の冷帯",
    "color": "#963296",
    "description": "寒い冬と短く涼しい夏を持ち、夏に乾燥する冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry summer, cold summer"
  },
  {
    "id": 20,
    "code": "Dsd",
    "name": "夏に乾燥する厳冬の冷帯",
    "color": "#966496",
    "description": "とくに厳しい冬を持ち、夏に乾燥する冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry summer, very cold winter"
  },
  {
    "id": 21,
    "code": "Dwa",
    "name": "冬に乾燥する高温夏の冷帯",
    "color": "#aaafff",
    "description": "寒く乾燥する冬と、高温の夏を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry winter, hot summer"
  },
  {
    "id": 22,
    "code": "Dwb",
    "name": "冬に乾燥する温暖夏の冷帯",
    "color": "#5a78dc",
    "description": "寒く乾燥する冬と、温暖な夏を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry winter, warm summer"
  },
  {
    "id": 23,
    "code": "Dwc",
    "name": "冬に乾燥する冷夏の冷帯",
    "color": "#4b50b4",
    "description": "寒く乾燥する冬と、短く涼しい夏を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry winter, cold summer"
  },
  {
    "id": 24,
    "code": "Dwd",
    "name": "冬に乾燥する厳冬の冷帯",
    "color": "#320087",
    "description": "とくに厳しく乾燥する冬を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, dry winter, very cold winter"
  },
  {
    "id": 25,
    "code": "Dfa",
    "name": "乾季のない高温夏の冷帯",
    "color": "#00ffff",
    "description": "明瞭な乾季がなく、寒い冬と高温の夏を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, no dry season, hot summer"
  },
  {
    "id": 26,
    "code": "Dfb",
    "name": "乾季のない温暖夏の冷帯",
    "color": "#37c8ff",
    "description": "明瞭な乾季がなく、寒い冬と温暖な夏を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, no dry season, warm summer"
  },
  {
    "id": 27,
    "code": "Dfc",
    "name": "乾季のない冷夏の冷帯",
    "color": "#007d7d",
    "description": "明瞭な乾季がなく、寒い冬と短く涼しい夏を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, no dry season, cold summer"
  },
  {
    "id": 28,
    "code": "Dfd",
    "name": "乾季のない厳冬の冷帯",
    "color": "#00465f",
    "description": "明瞭な乾季がなく、とくに厳しい冬を持つ冷帯の区分。",
    "group": "冷帯",
    "sourceLabel": "Cold, no dry season, very cold winter"
  },
  {
    "id": 29,
    "code": "ET",
    "name": "ツンドラ気候",
    "color": "#b2b2b2",
    "description": "短い夏に気温が上がるが、樹木の生育に適した暖かさに達しない寒帯の区分。",
    "group": "寒帯",
    "sourceLabel": "Polar, tundra"
  },
  {
    "id": 30,
    "code": "EF",
    "name": "氷雪気候",
    "color": "#666666",
    "description": "最も暖かい月も平均気温が0℃未満となる寒帯の区分。",
    "group": "寒帯",
    "sourceLabel": "Polar, frost"
  }
];
export const asiaClimatePeriod = '1991–2020';
export const asiaClimateAttribution = 'Beck et al. (2023), CC BY 4.0';
