// Generated by scripts/prepare-atlas-livestock-statistics.py; do not edit values.
export const livestockStatistics = {
  "generatedAt": "2026-09-14",
  "supply": {
    "beef": {
      "beginningStocks": 602.0,
      "production": 26071.0,
      "imports": 5388.0,
      "totalSupply": 32061.0,
      "exports": 2579.0,
      "endingStocks": 577.0,
      "domestic": 28905.0,
      "decimals": 0,
      "page": 32,
      "unit": "百万lb",
      "basis": "枝肉重量",
      "supplyDifference": 0.0,
      "supplyTolerance": 2.0,
      "useDifference": 0.0,
      "useTolerance": 2.0,
      "year": 2025,
      "periodType": "calendar",
      "status": "published"
    },
    "hogs": {
      "beginningStocks": 435.0,
      "production": 27593.0,
      "imports": 1117.0,
      "totalSupply": 29145.0,
      "exports": 6972.0,
      "endingStocks": 430.0,
      "domestic": 21744.0,
      "decimals": 0,
      "page": 32,
      "unit": "百万lb",
      "basis": "枝肉重量",
      "supplyDifference": 0.0,
      "supplyTolerance": 2.0,
      "useDifference": 1.0,
      "useTolerance": 2.0,
      "year": 2025,
      "periodType": "calendar",
      "status": "published"
    },
    "broilers": {
      "beginningStocks": 761.0,
      "production": 47493.0,
      "imports": 152.0,
      "totalSupply": 48406.0,
      "exports": 6665.0,
      "endingStocks": 786.0,
      "domestic": 40955.0,
      "decimals": 0,
      "page": 32,
      "unit": "百万lb",
      "basis": "可調理重量",
      "supplyDifference": 0.0,
      "supplyTolerance": 2.0,
      "useDifference": 0.0,
      "useTolerance": 2.0,
      "year": 2025,
      "periodType": "calendar",
      "status": "published"
    },
    "layers": {
      "beginningStocks": 14.2,
      "production": 8765.0,
      "imports": 120.9,
      "totalSupply": 8900.1,
      "exports": 203.5,
      "endingStocks": 17.1,
      "domestic": 7515.8,
      "hatching": 1163.8,
      "decimals": 1,
      "page": 33,
      "unit": "百万ダース",
      "basis": "卵換算・ふ化用を含む",
      "supplyDifference": 0.0,
      "supplyTolerance": 0.2,
      "useDifference": 0.1,
      "useTolerance": 0.25,
      "year": 2025,
      "periodType": "calendar",
      "status": "published"
    },
    "dairy-fat": {
      "beginningStocks": 13.1,
      "production": 230.7,
      "imports": 7.4,
      "totalSupply": 251.1,
      "exports": 16.7,
      "endingStocks": 12.6,
      "domestic": 221.7,
      "rawMilkProduction": 231.7,
      "farmUse": 1.0,
      "decimals": 1,
      "page": 33,
      "unit": "十億lb",
      "basis": "乳脂肪換算",
      "supplyDifference": 0.1,
      "supplyTolerance": 0.2,
      "useDifference": -0.1,
      "useTolerance": 0.2,
      "year": 2025,
      "periodType": "calendar",
      "status": "published"
    },
    "dairy-skim": {
      "beginningStocks": 9.1,
      "production": 230.7,
      "imports": 6.9,
      "totalSupply": 246.6,
      "exports": 47.9,
      "endingStocks": 9.2,
      "domestic": 189.5,
      "rawMilkProduction": 231.7,
      "farmUse": 1.0,
      "decimals": 1,
      "page": 33,
      "unit": "十億lb",
      "basis": "無脂乳固形分換算",
      "supplyDifference": 0.1,
      "supplyTolerance": 0.2,
      "useDifference": 0.0,
      "useTolerance": 0.2,
      "year": 2025,
      "periodType": "calendar",
      "status": "published"
    }
  },
  "production": {
    "beef": {
      "year": 2024,
      "periodType": "FAOSTAT annual",
      "periodNote": "Country reporting-year exceptions follow the FAOSTAT QCL methodology.",
      "unit": "t",
      "itemCode": "867",
      "itemName": "Meat of cattle with the bone, fresh or chilled",
      "worldTotal": 69749016.37,
      "countries": [
        {
          "code": "US",
          "country": "United States of America",
          "value": 12289768.0,
          "flag": "A"
        },
        {
          "code": "FAO-21",
          "country": "Brazil",
          "value": 10237584.0,
          "flag": "A"
        },
        {
          "code": "FAO-351",
          "country": "China",
          "value": 7026372.52,
          "flag": "E"
        },
        {
          "code": "FAO-9",
          "country": "Argentina",
          "value": 3178044.0,
          "flag": "A"
        },
        {
          "code": "FAO-10",
          "country": "Australia",
          "value": 2589767.0,
          "flag": "A"
        }
      ],
      "trend": [
        {
          "year": 2015,
          "us": 10817307.0,
          "world": 61393409.45,
          "share": 17.61965510126918,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2016,
          "us": 11507221.0,
          "world": 61164704.93,
          "share": 18.813498754174404,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2017,
          "us": 11943486.0,
          "world": 62426548.88,
          "share": 19.132061942040835,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2018,
          "us": 12255874.0,
          "world": 64164418.97,
          "share": 19.100732456924796,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2019,
          "us": 12384649.0,
          "world": 65297652.08,
          "share": 18.966453778195326,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2020,
          "us": 12388505.0,
          "world": 64658456.9,
          "share": 19.15991440865951,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2021,
          "us": 12733653.0,
          "world": 65001636.11,
          "share": 19.589742292719038,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2022,
          "us": 12889961.0,
          "world": 66165056.75,
          "share": 19.481523379786115,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2023,
          "us": 12286638.0,
          "world": 67548292.14,
          "share": 18.189413249020156,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2024,
          "us": 12289768.0,
          "world": 69749016.37,
          "share": 17.619987549080328,
          "worldFlag": "A",
          "usFlag": "A"
        }
      ],
      "sourceCountrySum": 69590877.66,
      "countrySumDifference": -158138.71,
      "missingAreas": [
        "100"
      ],
      "worldAreaCode": "5000",
      "usAreaCode": "231",
      "elementCode": "5510"
    },
    "dairy": {
      "year": 2024,
      "periodType": "FAOSTAT annual",
      "periodNote": "Country reporting-year exceptions follow the FAOSTAT QCL methodology.",
      "unit": "t",
      "itemCode": "882",
      "itemName": "Raw milk of cattle",
      "worldTotal": 797287454.1,
      "countries": [
        {
          "code": "FAO-100",
          "country": "India",
          "value": 135000000.0,
          "flag": "E"
        },
        {
          "code": "US",
          "country": "United States of America",
          "value": 102452123.0,
          "flag": "A"
        },
        {
          "code": "FAO-351",
          "country": "China",
          "value": 41260060.0,
          "flag": "A"
        },
        {
          "code": "FAO-21",
          "country": "Brazil",
          "value": 36816177.86,
          "flag": "A"
        },
        {
          "code": "FAO-79",
          "country": "Germany",
          "value": 33777780.0,
          "flag": "A"
        }
      ],
      "trend": [
        {
          "year": 2015,
          "us": 94618978.5,
          "world": 668045144.32,
          "share": 14.163560547440579,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2016,
          "us": 96366267.0,
          "world": 673166828.55,
          "share": 14.315361796357784,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2017,
          "us": 97761519.0,
          "world": 688767650.89,
          "share": 14.193686197903777,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2018,
          "us": 98687302.0,
          "world": 704201767.62,
          "share": 14.014066214791645,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2019,
          "us": 99083289.0,
          "world": 721199095.37,
          "share": 13.738687366096439,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2020,
          "us": 101291379.0,
          "world": 748223400.29,
          "share": 13.537585026175472,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2021,
          "us": 102619953.0,
          "world": 765308120.81,
          "share": 13.408972178602696,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2022,
          "us": 102700692.0,
          "world": 770055290.07,
          "share": 13.33679455544864,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2023,
          "us": 102653065.0,
          "world": 785839487.72,
          "share": 13.062854005699442,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2024,
          "us": 102452123.0,
          "world": 797287454.1,
          "share": 12.85008593489669,
          "worldFlag": "A",
          "usFlag": "A"
        }
      ],
      "sourceCountrySum": 789063906.42,
      "countrySumDifference": -8223547.68,
      "missingAreas": [],
      "worldAreaCode": "5000",
      "usAreaCode": "231",
      "elementCode": "5510"
    },
    "hogs": {
      "year": 2024,
      "periodType": "FAOSTAT annual",
      "periodNote": "Country reporting-year exceptions follow the FAOSTAT QCL methodology.",
      "unit": "t",
      "itemCode": "1035",
      "itemName": "Meat of pig with the bone, fresh or chilled",
      "worldTotal": 125357199.58,
      "countries": [
        {
          "code": "FAO-351",
          "country": "China",
          "value": 57947565.37,
          "flag": "A"
        },
        {
          "code": "US",
          "country": "United States of America",
          "value": 12611319.0,
          "flag": "A"
        },
        {
          "code": "FAO-21",
          "country": "Brazil",
          "value": 5358897.2,
          "flag": "A"
        },
        {
          "code": "FAO-203",
          "country": "Spain",
          "value": 4956040.0,
          "flag": "A"
        },
        {
          "code": "FAO-185",
          "country": "Russian Federation",
          "value": 4942500.33,
          "flag": "I"
        }
      ],
      "trend": [
        {
          "year": 2015,
          "us": 11120747.53,
          "world": 118751830.06,
          "share": 9.36469570564191,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2016,
          "us": 11320182.0,
          "world": 118375987.06,
          "share": 9.562903998648187,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2017,
          "us": 11610981.0,
          "world": 119336451.91,
          "share": 9.72961807910684,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2018,
          "us": 11942965.0,
          "world": 119621810.84,
          "share": 9.983935969648794,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2019,
          "us": 12542865.0,
          "world": 108703743.59,
          "share": 11.538576856477146,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2020,
          "us": 12845097.0,
          "world": 108691794.88,
          "share": 11.81790862335238,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2021,
          "us": 12559837.0,
          "world": 121240279.34,
          "share": 10.359458975492657,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2022,
          "us": 12251984.0,
          "world": 122985675.16,
          "share": 9.962122811506791,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2023,
          "us": 12391146.0,
          "world": 124572943.89,
          "share": 9.946899874937202,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2024,
          "us": 12611319.0,
          "world": 125357199.58,
          "share": 10.060306900802898,
          "worldFlag": "A",
          "usFlag": "A"
        }
      ],
      "sourceCountrySum": 126229508.45,
      "countrySumDifference": 872308.87,
      "missingAreas": [
        "102",
        "136",
        "223"
      ],
      "worldAreaCode": "5000",
      "usAreaCode": "231",
      "elementCode": "5510"
    },
    "broilers": {
      "year": 2024,
      "periodType": "FAOSTAT annual",
      "periodNote": "Country reporting-year exceptions follow the FAOSTAT QCL methodology.",
      "unit": "t",
      "itemCode": "1058",
      "itemName": "Meat of chickens, fresh or chilled",
      "worldTotal": 128307229.46,
      "countries": [
        {
          "code": "US",
          "country": "United States of America",
          "value": 20176637.0,
          "flag": "A"
        },
        {
          "code": "FAO-351",
          "country": "China",
          "value": 16066789.58,
          "flag": "E"
        },
        {
          "code": "FAO-21",
          "country": "Brazil",
          "value": 13714701.69,
          "flag": "A"
        },
        {
          "code": "FAO-185",
          "country": "Russian Federation",
          "value": 5457329.8,
          "flag": "I"
        },
        {
          "code": "FAO-100",
          "country": "India",
          "value": 5019410.0,
          "flag": "A"
        }
      ],
      "trend": [
        {
          "year": 2015,
          "us": 18402752.88,
          "world": 104836376.8,
          "share": 17.55378566268803,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2016,
          "us": 18708464.57,
          "world": 107596333.71,
          "share": 17.38764131166789,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2017,
          "us": 19140570.0,
          "world": 111797284.26,
          "share": 17.120782608176746,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2018,
          "us": 19568042.0,
          "world": 114742265.74,
          "share": 17.05390936269305,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2019,
          "us": 20197090.45,
          "world": 117688372.64,
          "share": 17.161500322365235,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2020,
          "us": 18814264.0,
          "world": 118865210.64,
          "share": 15.828234265265085,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2021,
          "us": 19230123.0,
          "world": 119612247.41,
          "share": 16.077051820691977,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2022,
          "us": 19841239.0,
          "world": 122287314.59,
          "share": 16.22509993495475,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2023,
          "us": 19901890.0,
          "world": 124659230.54,
          "share": 15.965035171313676,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2024,
          "us": 20176637.0,
          "world": 128307229.46,
          "share": 15.725253428755629,
          "worldFlag": "A",
          "usFlag": "A"
        }
      ],
      "sourceCountrySum": 128650373.63,
      "countrySumDifference": 343144.17,
      "missingAreas": [],
      "worldAreaCode": "5000",
      "usAreaCode": "231",
      "elementCode": "5510"
    },
    "layers": {
      "year": 2024,
      "periodType": "FAOSTAT annual",
      "periodNote": "Country reporting-year exceptions follow the FAOSTAT QCL methodology.",
      "unit": "t",
      "itemCode": "1062",
      "itemName": "Hen eggs in shell, fresh",
      "worldTotal": 93693573.42,
      "countries": [
        {
          "code": "FAO-351",
          "country": "China",
          "value": 31266885.52,
          "flag": "E"
        },
        {
          "code": "FAO-100",
          "country": "India",
          "value": 8101885.0,
          "flag": "E"
        },
        {
          "code": "FAO-101",
          "country": "Indonesia",
          "value": 6579353.28,
          "flag": "A"
        },
        {
          "code": "US",
          "country": "United States of America",
          "value": 6469047.0,
          "flag": "A"
        },
        {
          "code": "FAO-21",
          "country": "Brazil",
          "value": 3700049.44,
          "flag": "A"
        }
      ],
      "trend": [
        {
          "year": 2015,
          "us": 5756587.0,
          "world": 72479293.12,
          "share": 7.942388442543353,
          "worldFlag": "E",
          "usFlag": "A"
        },
        {
          "year": 2016,
          "us": 6046956.0,
          "world": 74727792.42,
          "share": 8.091977300779469,
          "worldFlag": "E",
          "usFlag": "A"
        },
        {
          "year": 2017,
          "us": 6350756.0,
          "world": 79121184.96,
          "share": 8.026618917816572,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2018,
          "us": 6518471.0,
          "world": 80469117.87,
          "share": 8.10058712279009,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2019,
          "us": 6706770.0,
          "world": 84328766.01,
          "share": 7.9531224246832775,
          "worldFlag": "A",
          "usFlag": "A"
        },
        {
          "year": 2020,
          "us": 6658784.0,
          "world": 87256325.43,
          "share": 7.6312908745417,
          "worldFlag": "E",
          "usFlag": "A"
        },
        {
          "year": 2021,
          "us": 6639446.0,
          "world": 87774447.66,
          "share": 7.564212794272798,
          "worldFlag": "E",
          "usFlag": "A"
        },
        {
          "year": 2022,
          "us": 6528357.0,
          "world": 89762006.7,
          "share": 7.272962403591183,
          "worldFlag": "E",
          "usFlag": "A"
        },
        {
          "year": 2023,
          "us": 6535414.1,
          "world": 92087899.64,
          "share": 7.096930351923487,
          "worldFlag": "E",
          "usFlag": "A"
        },
        {
          "year": 2024,
          "us": 6469047.0,
          "world": 93693573.42,
          "share": 6.904472488204943,
          "worldFlag": "E",
          "usFlag": "A"
        }
      ],
      "sourceCountrySum": 89751695.99,
      "countrySumDifference": -3941877.43,
      "missingAreas": [],
      "worldAreaCode": "5000",
      "usAreaCode": "231",
      "elementCode": "5510"
    }
  },
  "exports": {
    "beef": {
      "year": 2025,
      "periodType": "calendar",
      "unit": "USD",
      "tradeType": "total exports including re-exports",
      "bicoParent": "0145AT",
      "sourceProductName": "Beef & Beef Products",
      "codes": [
        "0201306090",
        "0202306000",
        "0202206000",
        "0201303550",
        "0206100000",
        "0202303550",
        "0206290090",
        "1602509500",
        "0504000050",
        "0201203550",
        "0201206000",
        "0206220000",
        "0206290050",
        "0206210000",
        "0206290010",
        "1602509020",
        "0202203550",
        "0504000070",
        "0201306010",
        "0206290020",
        "0210200000",
        "0202100010",
        "0201100090",
        "0206290040",
        "0201100010",
        "0202100090",
        "0206290030"
      ],
      "totalUsd": 9334091867,
      "destinations": [
        {
          "country": "Korea, South",
          "value": 2228872359
        },
        {
          "country": "Japan",
          "value": 1757430631
        },
        {
          "country": "Mexico",
          "value": 1301223529
        },
        {
          "country": "Canada",
          "value": 881280585
        },
        {
          "country": "Taiwan",
          "value": 667923915
        },
        {
          "country": "Other",
          "value": 2497360848
        }
      ]
    },
    "hogs": {
      "year": 2025,
      "periodType": "calendar",
      "unit": "USD",
      "tradeType": "total exports including re-exports",
      "bicoParent": "0150AT",
      "sourceProductName": "Pork & Pork Products",
      "codes": [
        "0203294000",
        "0203129000",
        "0203194000",
        "0203121000",
        "0203192000",
        "0203292000",
        "0206490030",
        "1602497000",
        "0206490090",
        "0504000020",
        "0210120020",
        "0206300000",
        "0203229000",
        "1602492000",
        "0206490010",
        "1602424000",
        "1602419000",
        "0210110000",
        "1602491000",
        "0203221000",
        "0210190000",
        "0203110000",
        "0206490050",
        "0203210000",
        "1602412000",
        "0504000080",
        "1602411000",
        "1602494000",
        "0206490020",
        "0206490040",
        "1602422000",
        "0210120040",
        "0206410000"
      ],
      "totalUsd": 8397870100,
      "destinations": [
        {
          "country": "Mexico",
          "value": 2852928557
        },
        {
          "country": "Japan",
          "value": 1235277642
        },
        {
          "country": "China",
          "value": 856657516
        },
        {
          "country": "Canada",
          "value": 762045018
        },
        {
          "country": "Korea, South",
          "value": 669848573
        },
        {
          "country": "Other",
          "value": 2021112794
        }
      ]
    },
    "dairy": {
      "year": 2025,
      "periodType": "calendar",
      "unit": "USD",
      "tradeType": "total exports including re-exports",
      "bicoParent": "0170AT",
      "sourceProductName": "Dairy Products",
      "codes": [
        "0402100000",
        "3502200000",
        "0406200000",
        "0406909550",
        "0406100000",
        "0405100000",
        "0406901000",
        "1702110000",
        "1901100002",
        "0404100500",
        "0404900000",
        "2105000010",
        "0404104000",
        "1901909502",
        "2202991500",
        "0404100850",
        "0406300000",
        "0402210000",
        "0403200000",
        "0403900000",
        "0401205000",
        "0405900000",
        "1901902500",
        "3501100000",
        "0401500000",
        "0402910000",
        "3501906000",
        "1702190000",
        "0401400000",
        "1901903042",
        "0402990000",
        "0402290000",
        "0401201000",
        "1901903020",
        "3501902000",
        "0401100000",
        "0406400000",
        "0406906500",
        "0405200000",
        "0404102000"
      ],
      "totalUsd": 9511281905,
      "destinations": [
        {
          "country": "Mexico",
          "value": 2574876971
        },
        {
          "country": "Canada",
          "value": 1312018403
        },
        {
          "country": "Japan",
          "value": 556398043
        },
        {
          "country": "China",
          "value": 523324021
        },
        {
          "country": "Korea, South",
          "value": 517688975
        },
        {
          "country": "Other",
          "value": 4026975492
        }
      ],
      "products": [
        {
          "label": "チーズ",
          "valueUsd": 2966193957,
          "codes": [
            "0406200000",
            "0406909550",
            "0406100000",
            "0406901000",
            "0406300000",
            "0406400000",
            "0406906500"
          ]
        },
        {
          "label": "その他の乳製品・派生品",
          "valueUsd": 2262365830,
          "codes": [
            "1702110000",
            "1901100002",
            "0404900000",
            "2105000010",
            "1901909502",
            "2202991500",
            "0403200000",
            "0403900000",
            "0401205000",
            "1901902500",
            "3501100000",
            "0401500000",
            "0402910000",
            "3501906000",
            "1702190000",
            "0401400000",
            "1901903042",
            "0402990000",
            "0401201000",
            "1901903020",
            "3501902000",
            "0401100000"
          ]
        },
        {
          "label": "粉乳",
          "valueUsd": 2053827868,
          "codes": [
            "0402100000",
            "0402210000",
            "0402290000"
          ]
        },
        {
          "label": "ホエー・乳アルブミン",
          "valueUsd": 1634130742,
          "codes": [
            "3502200000",
            "0404100500",
            "0404104000",
            "0404100850",
            "0404102000"
          ]
        },
        {
          "label": "バター・乳脂肪",
          "valueUsd": 594763508,
          "codes": [
            "0405100000",
            "0405900000",
            "0405200000"
          ]
        }
      ]
    },
    "broilers": {
      "year": 2025,
      "periodType": "calendar",
      "unit": "USD",
      "tradeType": "total exports including re-exports",
      "bicoParent": "0155AT",
      "sourceProductName": "Poultry Meat & Prods. (excl. eggs)",
      "codes": [
        "0207140010",
        "0207130000",
        "0207140090",
        "0207140025",
        "1602320090",
        "0207140045",
        "1602320020",
        "1601000010",
        "1602320050",
        "0207140030",
        "1602320035",
        "0207140050",
        "0207110040",
        "0207120040",
        "0207120020",
        "0207110020"
      ],
      "totalUsd": 4756946998,
      "destinations": [
        {
          "country": "Mexico",
          "value": 901260289
        },
        {
          "country": "Canada",
          "value": 583554039
        },
        {
          "country": "Taiwan",
          "value": 342772719
        },
        {
          "country": "Cuba",
          "value": 297602968
        },
        {
          "country": "China",
          "value": 277236488
        },
        {
          "country": "Other",
          "value": 2354520495
        }
      ]
    },
    "layers": {
      "year": 2025,
      "periodType": "calendar",
      "unit": "USD",
      "tradeType": "total exports including re-exports",
      "bicoParent": "0165AT",
      "sourceProductName": "Eggs & Products",
      "codes": [
        "0407210000",
        "0408190000",
        "3502190000",
        "0408110000",
        "0408910000",
        "0407900000",
        "0408990000",
        "3502110000"
      ],
      "totalUsd": 360105802,
      "destinations": [
        {
          "country": "Canada",
          "value": 215606303
        },
        {
          "country": "Japan",
          "value": 33085657
        },
        {
          "country": "Mexico",
          "value": 21265275
        },
        {
          "country": "Ireland",
          "value": 19003172
        },
        {
          "country": "Bahamas, The",
          "value": 15197676
        },
        {
          "country": "Other",
          "value": 55947719
        }
      ]
    }
  },
  "sources": {
    "wasde": {
      "publisher": "USDA",
      "report": "WASDE-675",
      "releaseDate": "2026-09-11",
      "retrievedAt": "2026-09-14",
      "localRawPath": "scripts/data/wasde0926.txt",
      "sha256": "de4baa0dc24769b2d8cc153bac488049d905b5c8aa1fec9696e2d4e13036e285",
      "url": "https://esmis.nal.usda.gov/sites/default/release-files/796054/wasde0926.pdf"
    },
    "faostat": {
      "publisher": "FAO",
      "dataset": "QCL",
      "landingUrl": "https://www.fao.org/faostat/en/#data/QCL",
      "releaseDate": "2025-12-31T00:00:00",
      "retrievedAt": "2026-09-14",
      "sha256": "c5835418c18f9322e7decbd6800f93a216eaae3cdfa31acb08f0518c0c6d6853",
      "methodologyUrl": "https://files-faostat.fao.org/production/QCL/QCL_methodology_e.pdf"
    },
    "gats": {
      "publisher": "USDA FAS / U.S. Census Bureau",
      "landingUrl": "https://apps.fas.usda.gov/gats/ExpressQuery1.aspx",
      "retrievedAt": "2026-09-14",
      "releaseDate": "2026-09-03",
      "valuationUrl": "https://www.census.gov/foreign-trade/guide/sec2.html"
    }
  }
} as const;
