// Generated by scripts/prepare-atlas-supply-use.py; do not edit values.
export const supplyUseGenerated = {
  "source": {
    "publisher": "USDA",
    "report": "WASDE-675",
    "publishedAt": "2026-09-11",
    "retrievedAt": "2026-09-13",
    "sha256": "de4baa0dc24769b2d8cc153bac488049d905b5c8aa1fec9696e2d4e13036e285",
    "url": "https://www.usda.gov/oce/commodity/wasde/wasde0926.pdf",
    "rawUrl": "https://esmis.nal.usda.gov/sites/default/release-files/796054/wasde0926.txt",
    "extractor": "prepare-atlas-supply-use.py v1"
  },
  "crops": {
    "corn": {
      "beginningStocks": 1763.0,
      "production": 14892.0,
      "imports": 22.0,
      "totalSupply": 16677.0,
      "exports": 2873.0,
      "endingStocks": 1551.0,
      "fsiParent": 6815.0,
      "domestic": {
        "feed": 5438.0,
        "ethanol": 5436.0,
        "other-fsi": 1379.0
      },
      "adjustment": 0,
      "decimals": 0,
      "page": 12,
      "column": "2024/25",
      "status": "actual",
      "coverage": "complete",
      "roundingTolerance": 4.0,
      "supplyError": 0.0,
      "useError": 0.0
    },
    "soybean": {
      "beginningStocks": 342.0,
      "production": 4374.0,
      "imports": 30.0,
      "totalSupply": 4746.0,
      "exports": 1892.0,
      "endingStocks": 325.0,
      "domestic": {
        "crush": 2445.0,
        "seed": 70.0,
        "residual": 14.0
      },
      "adjustment": 0,
      "decimals": 0,
      "page": 15,
      "column": "2024/25",
      "status": "actual",
      "coverage": "complete",
      "roundingTolerance": 4.0,
      "supplyError": 0.0,
      "useError": 0.0
    },
    "wheat": {
      "beginningStocks": 696.0,
      "production": 1979.0,
      "imports": 150.0,
      "totalSupply": 2825.0,
      "exports": 829.0,
      "endingStocks": 855.0,
      "domestic": {
        "food": 969.0,
        "seed": 61.0,
        "feed": 111.0
      },
      "adjustment": 0,
      "decimals": 0,
      "page": 11,
      "column": "2024/25",
      "status": "actual",
      "coverage": "complete",
      "roundingTolerance": 4.0,
      "supplyError": 0.0,
      "useError": 0.0
    },
    "cotton": {
      "beginningStocks": 3.15,
      "production": 14.41,
      "imports": 0.0,
      "totalSupply": 17.56,
      "exports": 11.9,
      "endingStocks": 4.0,
      "domestic": {
        "mill": 1.7
      },
      "adjustment": -0.04,
      "decimals": 2,
      "page": 17,
      "column": "2024/25",
      "status": "actual",
      "coverage": "complete",
      "roundingTolerance": 0.03,
      "supplyError": 0.0,
      "useError": -0.0
    },
    "rice": {
      "beginningStocks": 39.8,
      "production": 222.6,
      "imports": 49.3,
      "totalSupply": 311.7,
      "exports": 90.3,
      "endingStocks": 53.9,
      "domestic": {
        "domestic": 167.5
      },
      "adjustment": 0,
      "decimals": 1,
      "page": 14,
      "column": "2024/25",
      "status": "actual",
      "coverage": "complete",
      "roundingTolerance": 0.30000000000000004,
      "supplyError": 0.0,
      "useError": 0.0
    }
  }
} as const;
