import {densityColors,missingColor} from '../data/atlas/population';
import {canadaDemographicShare,canadaDemographicShareColor} from '../lib/atlas-canada-demographics';
import {demographicComposition,concentrationMethod,concentrationNote,ethnicColors,religiousColors} from '../lib/atlas-canada-concentration';
import {canadaReligionColor,canadaReligionComposition,canadaReligionInitialIds} from '../lib/atlas-canada-religion-view';
import {renderCanadaReligionMap} from './atlas-canada-religion-map';
const japanese=(name:string)=>name.match(/（(.+)）/)?.[1]??name;
const provinceNames:Record<string,string>={'10':'ニューファンドランド・ラブラドール','11':'プリンスエドワード島','12':'ノバスコシア','13':'ニューブランズウィック','24':'ケベック','35':'オンタリオ','46':'マニトバ','47':'サスカチュワン','48':'アルバータ','59':'ブリティッシュコロンビア','60':'ユーコン','61':'北西準州','62':'ヌナブト'};
const nameOf=(r:any)=>r.level==='Census division'?r.name.split(',')[0]+'（'+provinceNames[r.id.slice(0,2)]+'）':japanese(r.name);
export const densityColor=(n:number|null)=>n===null?missingColor:densityColors[n===0?0:n<=1?1:n<10?2:n<100?3:n<1000?4:n<10000?5:6];
export function renderCanadaPopulationOverview(root:HTMLElement,config:any,state:any,demographic:any,choose:(id:string|null)=>void,choosePlace:(id:string,level:'cma'|'cd')=>void){
 const $=(s:string)=>root.querySelector<HTMLElement>(s)!;
 const topic=demographic.topic,data=topic==='distribution'?null:config.demographics[topic],colors=topic==='ethnicity'?ethnicColors:topic==='religion'?canadaReligionColor:religiousColors,params=new URL(location.href).searchParams,filtered=Boolean(data)&&params.get('mapGroup')==='1',cd=params.get('cd'),regional=config.demographics.ethnicity.regions;
 const compose=(record:any)=>topic==='religion'?canadaReligionComposition(record,data):demographicComposition(record,data,topic);
 const selectedRegion=regional.find((r:any)=>r.id===cd),ready=root.dataset.regionsReady==='true';
 const cma=config.cmas.find((r:any)=>r.id===state.cma),hasSelection=!!selectedRegion||!!cma;
 const selected=data?(selectedRegion?data.regions.find((r:any)=>r.id===cd):data.cmas.find((r:any)=>r.id===state.cma)??data.national):selectedRegion??cma??config.national.find((r:any)=>r.id==='Canada'),scope=selectedRegion?'統計地域（CD）':cma?'都市圏（CMA）':'全国';
 const selectedName=hasSelection?nameOf(selected):'全国';
 root.dataset.populationSelection=selectedRegion?'region':cma?'city':'national';
 const key=$('[data-population-category-key]');key.replaceChildren();
 for(const s of ['[data-population-population-legend]','[data-population-density-legend]','[data-demographic-share-legend]','[data-demographic-count-legend]'])$(s).hidden=true;
 function addKey(name:string,color:string,id?:string,container:HTMLElement=key){const el=document.createElement(id!==undefined?'button':'span'),swatch=document.createElement('i');swatch.style.background=color;el.append(swatch,document.createTextNode(name));if(id!==undefined){el.setAttribute('type','button');el.dataset.populationCategory=id;el.setAttribute('aria-pressed',String(id===''?!filtered:filtered&&demographic.group===id));el.addEventListener('click',()=>{root.dataset.populationReadingFocus='group';choose(id||null);});}container.append(el);}
 if(!data){['0','>0–1','>1–<10','10–<100','100–<1,000','1,000–<10,000','10,000以上'].forEach((n,i)=>addKey(n,densityColors[i]));addKey('未公表',missingColor);}else if(topic==='religion'){
  addKey('特徴的な分布','#d3d6d4','');for(const id of canadaReligionInitialIds){const g=data.groups.find((group:any)=>group.id===id);addKey(g.name,colors[id],id);}
  const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='ほか3区分';detail.className='population-religion-extra';detail.append(summary);for(const id of ['2','other-christian','24']){const g=data.groups.find((group:any)=>group.id===id);addKey(g.name,colors[id],id,detail);}key.append(detail);
 }else{addKey('全体の集積','#d3d6d4','');for(const g of data.groups)addKey(g.name,colors[g.id],g.id);addKey('複数集積（等幅の縞）','repeating-linear-gradient(135deg,#617989 0 5px,#dfd8c8 5px 10px)');addKey('集積基準外・背景','#d3d6d4');addKey('未公表',missingColor);}
 const filterKey=$('[data-population-filter-key]');filterKey.hidden=!filtered;filterKey.replaceChildren();if(filtered){const g=data.groups.find((g:any)=>g.id===demographic.group);filterKey.append(document.createTextNode(topic==='religion'?g.name+'が集積基準に該当するCDを強調。他の分布も薄く残します。':g.name+'の人口割合：'));if(topic!=='religion')['1%未満','1–5%未満','5–10%未満','10–25%未満','25–50%未満','50%以上'].forEach((label,i)=>{const item=document.createElement('span'),swatch=document.createElement('i');swatch.style.background=canadaDemographicShareColor([0,1,5,10,25,50][i]);item.append(swatch,label);filterKey.append(item);});}
 const coverage=ready?'全国293統計地域＋41都市圏。'+(topic==='religion'?'広域を初期表示。':'南部を初期表示。'):'地域境界を読み込み中。現在は41都市圏を表示。',ethnicityNote='可視的少数者の公式区分を使用。「該当しない」は白人と同義ではありません。先住民アイデンティティは別集計で、この区分と重複するため全行を合計しません。';
 const note=!data?'人口密度（人/km²）、2021年の地域平均。地図の面積は人数ではありません。':topic==='religion'?'CD内5%以上かつ全国割合の1.5倍以上の区分から、全国比が最も高い区分をCDの面色にします。併存する該当区分は小さな色点で補います。色面はCDの集計範囲で、住民全員の所属や最多・過半数を示しません。':filtered?'選択した区分の実際の人口割合を濃淡で表示します。':concentrationNote+' 都市の色点は同時に集積する区分。点の分割面積は割合・人数を示しません。';
 $('[data-population-coverage]').textContent=note+' '+coverage;
 $('[data-population-coverage-brief]').textContent='2021年・'+(topic==='religion'?'宗教13表示区分、原表23区分を保持。':topic==='ethnicity'?'人口集団14区分（先住民は別集計）。':'人口密度。')+coverage;
 $('#canada-population-title').textContent=!data?'2021年カナダの地域別人口密度':topic==='religion'?'宗教・無宗教の特徴的な同時分布':filtered?data.groups.find((g:any)=>g.id===demographic.group).name+'の割合':'特徴的な集積（最多・過半数の地図ではありません）';$('#canada-population-desc').textContent=note;
 $('[data-population-map-status]').textContent=root.dataset.regionsError==='true'?'地域境界を取得できませんでした。41都市圏を表示しています。再読み込みで再試行できます。':coverage+' 地域または都市を選ぶと右の解説が変わります。';
 const patterns=root.querySelector<SVGElement>('[data-population-concentration-patterns]')!;
 const patternId=(qualified:any[])=>`canada-${topic}-concentration-${qualified.map(g=>g.id).join('-')}`;
 if(patterns.getAttribute('data-topic')!==topic){
  patterns.replaceChildren();patterns.setAttribute('data-topic',topic);
  if(data&&topic!=='religion'){const seen=new Set<string>();for(const r of [...data.regions,...data.cmas]){const c=compose(r);if(c.qualified.length<2)continue;const id=patternId(c.qualified);if(seen.has(id))continue;seen.add(id);const pattern=document.createElementNS('http://www.w3.org/2000/svg','pattern');pattern.id=id;pattern.setAttribute('patternUnits','userSpaceOnUse');pattern.setAttribute('patternTransform','rotate(45)');pattern.setAttribute('width',String(c.qualified.length*8));pattern.setAttribute('height','8');pattern.dataset.populationConcentrationPattern='';const background=document.createElementNS('http://www.w3.org/2000/svg','rect');background.setAttribute('width',String(c.qualified.length*8));background.setAttribute('height','8');background.setAttribute('fill','#f0f3ef');pattern.append(background);for(const [i,g]of c.qualified.entries()){const stripe=document.createElementNS('http://www.w3.org/2000/svg','rect');stripe.setAttribute('x',String(i*8));stripe.setAttribute('y','0');stripe.setAttribute('width','6');stripe.setAttribute('height','8');stripe.setAttribute('fill',colors[g.id]);stripe.setAttribute('fill-opacity','.65');stripe.dataset.populationConcentrationGroup=g.id;pattern.append(stripe);}patterns.append(pattern);}}
 }
 const focusQualified=(c:any)=>c.rows.some((row:any)=>row.id===demographic.group&&row.share!==null&&row.share>=5&&row.ratio!==null&&row.ratio>=1.5);
 function fill(r:any){if(!data)return densityColor(r.density?.value??r.density2021?.value??null);if(topic==='religion'){const c=compose(r);return filtered&&focusQualified(c)?colors[demographic.group]:c.missing&&!c.primary?missingColor:c.primary?colors[c.primary.id]:'#f1f0e9';}if(filtered)return canadaDemographicShareColor(canadaDemographicShare(r.values[demographic.group]?.value??null,r.denominator.value));const c=compose(r);return c.missing?missingColor:c.qualified.length>1?`url(#${patternId(c.qualified)})`:c.primary?colors[c.primary.id]:'#d3d6d4';}
 for(const p of root.querySelectorAll<SVGElement>('[data-population-region]')){const r=(data?.regions??regional).find((r:any)=>r.id===p.dataset.populationRegion),c=data?compose(r):null;p.style.fill=fill(r);p.style.fillOpacity=topic==='religion'&&filtered&&c&&!focusQualified(c)?'.38':'1';p.setAttribute('aria-label',nameOf(r)+'：'+(c?.qualified.length?'特徴的な集積 '+c.qualified.map((g:any)=>g.name).join('、')+'。':'州より細かい統計地域。')+'構成と割合を開く');p.setAttribute('aria-pressed',String(r.id===cd));p.classList.toggle('is-selected-region',r.id===cd);}
 for(const marker of root.querySelectorAll<SVGElement>('[data-population-map-cma]')){
  const id=marker.dataset.populationMapCma!,r=(data??config).cmas.find((r:any)=>r.id===id),c=data?compose(r):null;
  marker.style.display='';marker.querySelector<SVGElement>('[data-population-symbol]')!.style.display='none';marker.classList.toggle('is-selected-cma',!selectedRegion&&id===state.cma);marker.setAttribute('aria-pressed',String(!selectedRegion&&id===state.cma));
  const boundary=marker.querySelector<SVGElement>('[data-population-boundary]')!;boundary.style.fill=ready?'none':fill(r);boundary.style.stroke=ready?!selectedRegion&&id===state.cma?'#263f48':'none':'';boundary.style.pointerEvents=ready?'none':'';marker.querySelector('[data-population-category-dots]')?.remove();
  const label=marker.querySelector<SVGTextElement>('[data-population-label]')!,point=marker.querySelector<SVGCircleElement>('.population-anchor')!;label.textContent=japanese(r.name);label.style.fontSize='13px';label.style.display=id===state.cma||['535','462','933','825','835','602','505','705'].includes(id)?'':'none';
  if(c&&(topic==='religion'?c.qualified.length>1:!filtered&&c.qualified.length)){const dots=document.createElementNS('http://www.w3.org/2000/svg','g');dots.dataset.populationCategoryDots='';dots.style.opacity=filtered?'.6':'1';c.qualified.slice(0,3).forEach((g:any,i:number)=>{const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',String(Number(point.getAttribute('cx'))+i*7));dot.setAttribute('cy',String(Number(point.getAttribute('cy'))+7));dot.setAttribute('r','3');dot.setAttribute('fill',colors[g.id]);dot.setAttribute('stroke','#fff');dots.append(dot);});marker.append(dots);}
  marker.setAttribute('aria-label',japanese(r.name)+'：'+(!data?`${r.density2021.value??'未公表'}人/km²`:c!.missing?'未公表値あり':c!.primary?c!.primary.name+' '+c!.primary.share.toFixed(1)+'%':'集積基準に達する区分なし')+'。都市圏の解説を開く');
 }
 const labels=[...root.querySelectorAll<SVGTextElement>('[data-population-label]')].filter(n=>n.style.display!=='none').sort((a,b)=>Number(b.closest('[data-population-map-cma]')?.getAttribute('data-population-map-cma')===state.cma)-Number(a.closest('[data-population-map-cma]')?.getAttribute('data-population-map-cma')===state.cma)),boxes:number[][]=[];
 if(topic==='religion')renderCanadaReligionMap(root,data,filtered?demographic.group:null,!filtered&&!hasSelection&&!params.has('zoom')&&!params.has('mapFrame'));
 else {root.querySelector('[data-religion-region-symbols]')?.replaceChildren();root.querySelector('[data-religion-map-callouts]')?.replaceChildren();}
 for(const label of labels){const anchor=label.parentElement!.querySelector('.population-anchor')!,x=Number(anchor.getAttribute('cx')),y=Number(anchor.getAttribute('cy')),width=(label.textContent?.length??0)*13;let placed=false;for(const [dx,dy]of [[8,-8],[8,19],[-width-8,-8],[-width-8,19],[8,-28]]){const b=[x+dx,y+dy-13,x+dx+width,y+dy+3];if(b[0]<2||b[2]>898||boxes.some(a=>b[0]<a[2]+3&&b[2]>a[0]-3&&b[1]<a[3]+3&&b[3]>a[1]-3))continue;label.setAttribute('x',String(x+dx));label.setAttribute('y',String(y+dy));boxes.push(b);placed=true;break;}if(!placed)label.style.display='none';}
 $('[data-population-composition]').hidden=!data;
 $('[data-population-clear-selection]').hidden=!hasSelection;
 if(!data){$('[data-population-change]').hidden=!!selectedRegion||!cma;$('[data-population-comparison-links]').hidden=!!selectedRegion||!cma;$('[data-population-distribution-heading]').textContent=selectedRegion?selectedName+'・統計地域（CD）':cma?'都市を選び、人口と仕事の関係を読む':'全国の人口分布';$('[data-population-comparison]').textContent=hasSelection?`${selectedName}・${scope}：${(selectedRegion?selected.population.value:selected.population[2021].value)?.toLocaleString('ja-JP')??'未公表'}人 ／ 密度 ${(selectedRegion?selected.density.value:selected.density2021.value)?.toLocaleString('ja-JP')??'未公表'}人/km²`:`2021年の全国人口 ${selected.population[2021].value.toLocaleString('ja-JP')}人。41都市圏に${config.cmaShare2021.toFixed(1)}%が住んでいます。`;return;}
 const c=compose(selected),g=data.groups.find((g:any)=>g.id===demographic.group),selectedCell=c.rows.find((r:any)=>r.id===g.id);
 const overview=$('[data-demographic-overview]');overview.hidden=hasSelection||filtered;
 $('[data-demographic-overview-title]').textContent=topic==='ethnicity'?'南部の大都市と、北部の地域を比べる':'西部の無宗教、東部の教派、都市周辺の複数宗教';
 $('[data-demographic-overview-intro]').textContent=topic==='ethnicity'?'バンクーバー、トロント、モントリオールでは人口集団の構成が異なります。北部では先住民アイデンティティの割合も、別の変数として確かめます。':'ユーコンとBCでは無宗教の割合が高く、ケベックではカトリック、ヌナブトとニューファンドランドでは聖公会の集積が見えます。Peelではイスラム教・ヒンドゥー教・シク教がそれぞれ12％を超えます。点は地域の割合の特徴で、面積や点の大きさは人数を表しません。';
 const examples=topic==='ethnicity'?[['cma','933',['5','4']],['cma','535',['4','5']],['cma','462',['6','8']],['cd','6205',['87']]]:[['cd','6001',['25']],['cd','2492',['8']],['cd','6204',['6']],['cd','1005',['6']],['cd','3521',['21','19','22']]];
 const list=$('[data-demographic-examples]');list.replaceChildren();
 for(const [level,id,groups]of examples){const record=(level==='cd'?data.regions:data.cmas).find((r:any)=>r.id===id),paragraph=document.createElement('p'),button=document.createElement('button'),values=document.createElement('span');button.type='button';button.dataset.demographicExample=String(id);button.textContent=nameOf(record)+(level==='cd'?'・CD':'・都市圏');button.addEventListener('click',()=>choosePlace(String(id),level as 'cma'|'cd'));for(const [index,groupId]of (groups as string[]).entries()){const group=data.groups.find((g:any)=>g.id===groupId),share=canadaDemographicShare(record.values[groupId]?.value??null,record.denominator.value),swatch=document.createElement('i');swatch.style.background=colors[groupId];swatch.setAttribute('aria-hidden','true');if(index)values.append(' ／ ');values.append(swatch,group.name+' '+(share===null?'未公表':share.toFixed(1)+'%'));}paragraph.append(button,values);list.append(paragraph);}
 const peel=topic==='religion'&&selectedRegion?.id==='3521',simultaneous=$('[data-demographic-simultaneous]');simultaneous.hidden=!hasSelection||!c.qualified.length||peel;simultaneous.textContent='同じ地域で集積基準に該当：'+c.qualified.map((row:any)=>row.name+' '+row.share.toFixed(1)+'%').join('、')+'。';$('[data-religion-peel-context]').hidden=!peel;
 const composition=$('[data-population-composition]') as HTMLDetailsElement,recordKey=topic+':'+(selectedRegion?.id??cma?.id??'national');if(composition.dataset.record!==recordKey){composition.open=hasSelection;composition.dataset.record=recordKey;}
 $('[data-demographic-heading]').textContent=hasSelection?selectedName+'・'+scope:topic==='ethnicity'?'全国の人口集団の分布':'全国の宗教・無宗教の地域差';$('[data-demographic-lead]').textContent=peel?'Peelはトロントの西側にある統計地域。Mississauga・Brampton・Caledonを含みます。':topic==='ethnicity'?'都市とその周辺を比べ、人口集団が特徴的に集まる場所を読む。':'無宗教・教派・都市の複数宗教が、同じ国の中でどう分布するかを読む。';
 $('[data-demographic-comparison]').textContent=!hasSelection&&!filtered?topic==='religion'?'面色はCD内で全国比が最も高い特徴的な区分。小点は同じCDで基準に該当する別の区分です。都市圏は重なる別集計で、地域を選ぶと各割合を読めます。':'単色は1区分、等幅の縞は同じ統計地域で特徴的に集まる複数区分を示します。都市の色点も複数区分を同時表示します。地域・都市を選ぶと実際の構成比を確認できます。':c.missing&&!c.qualified.length?'一部の構成比は未公表です。公表された区分のみ確認してください。':filtered?g.name+'：'+selectedCell.share.toFixed(1)+'% ／ 全国 '+selectedCell.national.toFixed(1)+'% ／ 全国比 '+selectedCell.ratio?.toFixed(2)+'倍':c.qualified.length?'特徴的な集積：'+c.qualified.map((row:any)=>row.name+' '+row.share.toFixed(1)+'%').join('、')+'。':'集積基準に達する区分はありません。住民がいないという意味ではありません。';
 if(root.dataset.populationReadingFocus==='group'&&filtered){const top=data.regions.map((r:any)=>({name:nameOf(r),share:canadaDemographicShare(r.values[g.id]?.value??null,r.denominator.value)})).filter((r:any)=>r.share!==null).sort((a:any,b:any)=>b.share-a.share).slice(0,3);$('[data-demographic-heading]').textContent=g.name+'の分布';$('[data-demographic-comparison]').textContent='全国293統計地域で割合が高い地域：'+top.map((r:any)=>r.name+' '+r.share.toFixed(1)+'%').join('、')+'。';}
 const nationalRow=filtered?selectedCell:c.primary;$('[data-demographic-national]').hidden=!hasSelection&&!filtered;$('[data-demographic-national]').textContent=nationalRow?'全国の'+nationalRow.name+'：'+nationalRow.national.toFixed(2)+'%。':'';
 $('[data-demographic-definition]').textContent=topic==='ethnicity'?ethnicityNote:'所属の自己申告です。米国の宗教団体による所属者数とは調査方法が異なります。信仰の強さ・政治姿勢は示しません。';$('[data-demographic-classification]').textContent=(topic==='religion'?'原表23末端区分を重複なく13表示区分へ集約。地域で5%以上かつ全国割合の1.5倍以上を満たす区分のうち、全国比が最大の区分でCDを塗り、併存する区分を小点で補います。その他キリスト教とその他の宗教は集計に残します。面はCDの集計範囲で、点は表示用基点です。':concentrationMethod)+' 公式の地域区分や統計的有意差ではなく、分布を読むための編集基準です。'+(peel?' Peelの人口構成と宗教は別の集計項目です。個人の移住歴と宗教は結び付けられず、宗教集積の原因もこの表だけでは特定できません。':'');$('[data-demographic-quality]').textContent=selectedName+'：長形式未回答率 '+(selected.quality?.tnr?.longForm??'未公表')+'%。 '+(selected.quality?.notes??[]).join(' ');
 const link=$('[data-demographic-population-link]') as HTMLAnchorElement;link.textContent=selectedName+'の2021年人口密度を見る';const target=new URL(location.href);target.searchParams.delete('topic');target.searchParams.delete('group');target.searchParams.delete('mapGroup');target.searchParams.set('metric','density');target.searchParams.set('year','2021');link.href=target.href;
 $('[data-population-composition-title]').textContent=hasSelection?selectedName+'・'+scope+'の構成（2021年）':'全国の構成（2021年）';$('[data-population-composition-note]').textContent='私的世帯人口を分母に使用。公表0と欠測・秘匿を区別。'+(topic==='ethnicity'?'先住民は別集計で他行と重複し、全行を足して100%にはなりません。':'キリスト教の親分類を除き、教派との二重計上を防いでいます。');
 const tbody=$('[data-population-composition-rows]');tbody.replaceChildren();for(const r of c.rows){const tr=document.createElement('tr'),name=document.createElement('th'),share=document.createElement('td'),count=document.createElement('td'),dot=document.createElement('i');dot.style.background=colors[r.id];name.append(dot,r.name);share.textContent=r.share===null?'未公表':r.share.toFixed(1)+'%';count.textContent=r.count===null?'未公表':r.count.toLocaleString('ja-JP')+'人';tr.append(name,share,count);tr.classList.toggle('is-active-category',filtered&&r.id===g.id);tbody.append(tr);}
 const original=$('[data-religion-source-detail]');original.hidden=topic!=='religion';if(topic==='religion'){const rows=$('[data-religion-source-rows]');rows.replaceChildren();for(const group of data.sourceGroups){const cell=selected.sourceValues[group.id],share=canadaDemographicShare(cell?.value??null,selected.denominator.value),tr=document.createElement('tr'),name=document.createElement('th'),pct=document.createElement('td'),count=document.createElement('td');name.textContent=group.name;pct.textContent=share===null?'未公表':share.toFixed(2)+'%';count.textContent=cell?.value===null?'未公表':cell.value.toLocaleString('ja-JP')+'人';tr.append(name,pct,count);rows.append(tr);}}
}
