import {initLatinEssentialLegends} from './atlas-latin-essential-legends.ts';
export function initLatinWorkspaceLayout():void {
 for(const root of document.querySelectorAll<HTMLElement>('[data-latin-workspace]')){
  if(root.dataset.layoutReady==='true')continue;root.dataset.layoutReady='true';
  const navigation=root.querySelector<HTMLElement>('[data-latin-navigation-selection]');if(navigation){for(const selector of ['[data-latin-agriculture-scope]','[data-latin-agriculture-place]','[data-nature-scope]','[data-nature-place]','[data-industry-scope]','[data-industry-place]','[data-lp-scope-select]','[data-lp-place-select]']){const label=root.querySelector(selector)?.closest('label');if(label)navigation.append(label);}}
  const syncFieldLinks=()=>{
   const placeSelect=root.querySelector<HTMLSelectElement>('[data-latin-agriculture-place],[data-nature-place],[data-industry-place],[data-lp-place-select]'),scopeSelect=root.querySelector<HTMLSelectElement>('[data-latin-agriculture-scope],[data-nature-scope],[data-industry-scope],[data-lp-scope-select]'),params=new URLSearchParams(location.search),routePlace=params.get('place'),routeScope=params.get('scope');
   // Route selection is already available while field modules hydrate their SSR controls.
   const place=routePlace&&placeSelect&&Array.from(placeSelect.options).some(option=>option.value===routePlace)?routePlace:placeSelect?.value??'all',scope=routeScope&&['all','central','south','country'].includes(routeScope)?routeScope:scopeSelect?.value??'all';
   for(const link of root.querySelectorAll<HTMLAnchorElement>('.latin-fields>a')){const url=new URL(link.href);if(url.pathname.endsWith('/overview/')){place==='all'?url.searchParams.delete('country'):url.searchParams.set('country',place);}else url.searchParams.set('place',place);url.searchParams.set('scope',scope);for(const flag of ['only','fallback']){const value=params.get(flag);if(value==='0'||value==='1')url.searchParams.set(flag,value);else url.searchParams.delete(flag);}if(url.pathname.endsWith('/'+root.dataset.latinField+'/')){const section=params.get('section');if(section)url.searchParams.set('section',section);else url.searchParams.delete('section');}else url.searchParams.delete('section');link.href=url.href;}
  };
  const scheduleFieldLinks=()=>queueMicrotask(()=>{syncFieldLinks();restoreSection();});root.addEventListener('change',scheduleFieldLinks);root.addEventListener('click',scheduleFieldLinks);window.addEventListener('popstate',scheduleFieldLinks);requestAnimationFrame(syncFieldLinks);
  const below=root.querySelector<HTMLElement>('[data-latin-below-workspace]');if(below){const extra=[...root.querySelectorAll<HTMLElement>('[data-nature-map-description],figure>[data-latin-agriculture-map-caption]')];if(extra.length){const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='地図の分布・尺度と読み方';detail.append(summary,...extra);below.prepend(detail);}const actions=root.querySelector('[data-nature-renderer]')?.closest('.latin-actions'),options=root.querySelector('.latin-map-options-body');if(actions&&options)options.append(actions);}if(root.dataset.latinField==='industry'&&below)for(const detail of root.querySelectorAll<HTMLElement>('.latin-industry-details'))below.append(detail);
  const fixed=root.querySelector<HTMLElement>('[data-latin-reading-fixed]'),scroll=root.querySelector<HTMLElement>('.latin-reading-scroll');
  if(fixed&&scroll&&root.dataset.latinField!=='nature'){const host=scroll.firstElementChild?.tagName==='DIV'?scroll.firstElementChild:scroll;for(const node of [...host.children])if(node.matches('h2,.latin-takeaway,.lp-cause-brief,.latin-comparison-link'))fixed.append(node);}
  const industryReading=root.querySelector<HTMLElement>('.latin-industry-reading');if(industryReading){const top=document.createElement('div'),body=document.createElement('div');top.className='latin-industry-reading-fixed';body.className='latin-industry-reading-scroll';for(const node of [...industryReading.children]){if(node.matches('[data-industry-reading-title],[data-industry-takeaway],.latin-industry-actions'))top.append(node);else body.append(node);}industryReading.append(top,body);}
  const message=root.querySelector<HTMLElement>('[data-latin-unavailable]')!,water=root.querySelector<HTMLElement>('[data-latin-water-items]');
  if(water&&root.dataset.latinField==='nature'&&scroll)scroll.prepend(water);
  const available=root.dataset.latinField==='nature'?'climate':root.dataset.latinField==='agriculture'?'agriculture':root.dataset.latinField==='industry'?'industry':'population';
  const waterSections=new Set(['water','rivers','rainfall','basins']);
  const sectionButtons=[...root.querySelectorAll<HTMLButtonElement>('[data-latin-section]')];
  const readSection=()=>{const requested=new URLSearchParams(location.search).get('section');return requested&&sectionButtons.some(button=>button.dataset.latinSection===requested)?requested:available;};
  const select=(id:string)=>{const panelId=id==='water'?'rivers':id;root.dataset.latinActiveSection=panelId;const panels=[...root.querySelectorAll<HTMLElement>('[data-latin-section-panel]')];const composition=root.dataset.latinField==='population'&&['ethnicity','religion'].includes(panelId)&&!!root.querySelector('[data-population-culture]');const missing=id!==available&&!composition&&!panels.some(panel=>panel.dataset.latinSectionPanel===panelId);panels.forEach(panel=>panel.hidden=panel.dataset.latinSectionPanel!==panelId);sectionButtons.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.latinSection===id||(button.dataset.latinSection==='water'&&waterSections.has(id)))));if(water){water.hidden=!waterSections.has(id);if(root.dataset.latinField==='nature'){if(missing)message.after(water);else if(scroll)scroll.prepend(water);}}message.hidden=!missing;root.classList.toggle('has-unavailable-section',missing);const label=root.querySelector<HTMLElement>(`[data-latin-section="${id}"]`)?.textContent??id;message.textContent=id==='basins'?'流域の分布図は未整備です。BasinATLAS v1原配布の取得が403 Forbiddenで拒否されました。河川線から流域の面・流向・面積を推定して補っていません。河川・地下水または降水量へ戻れます。':`${label}の分布図は未整備です。推定値で補わず、出典と範囲を確認してから追加します。整備済みの項目へ戻ると、元の地図・選択を続けられます。`;};
  const restoreSection=()=>select(readSection());
  const chooseSection=(id:string)=>{const url=new URL(location.href);if(id===available)url.searchParams.delete('section');else url.searchParams.set('section',id);if(url.href!==location.href)window.history.pushState(null,'',url);select(id);window.dispatchEvent(new window.CustomEvent('latin-section-change'));syncFieldLinks();};
  sectionButtons.forEach(button=>button.addEventListener('click',()=>chooseSection(button.dataset.latinSection!)));
  window.addEventListener('popstate',restoreSection);window.addEventListener('latin-section-change',restoreSection);requestAnimationFrame(restoreSection);
 }
 initLatinEssentialLegends();
}
