import {canadaLegacyPoint} from '../lib/atlas-canada-map-presentation';
import population from '../data/atlas/canada/population.json';
import {readCanadaPopulationState,writeCanadaPopulationState,copyCanadaPopulationMapState} from '../lib/atlas-canada-population';
import {isCanadaDemographicTopic} from '../lib/atlas-canada-demographics';
const canadaWaterFullFrame=[0,0,900,580];
import {industrySectors} from '../data/atlas/industry-catalog';
type Province={id:string;name:string;short:string;gdp:number};
type Metric={id:string;label:string;sector:string;gdp:number;employment:number|null;provinces:Province[]};
const reading:Record<string,[string,string]>={all:['中央部の加工・サービスと、西部の資源を比較する。','業態を選び、さらに分野を絞ると、州別GDPの大きさを比較できます。地形や水路・市場の位置と合わせて、産業の立地を読んでいきます。'],manufacturing:['加工の集積を、五大湖・セントローレンス沿いの輸送と結び付ける。','オンタリオとケベックを通る中央輸送回廊では、道路・鉄道・五大湖／セントローレンス水路が製品と市場をつなぎます。自動車、航空宇宙、食品などを切り替えると、製造業の中でも集積する州が違うことが分かります。'],resources:['資源の場所から、加工・輸送・市場へのつながりを追う。','アルバータの石油資源は集荷・精製・パイプラインを通じて他州や米国の市場につながります。石油・ガス、鉱業、電力では地理的な条件が異なるため、分野を分けて比較します。'],services:['人と仕事の集まりを、サービスの種類ごとに読む。','金融、専門サービス、商業・物流、医療・教育を分けて確認できます。GDPが大きいことと、雇用が多いことは同じではありません。下部の補助統計にある二つの構成比で、その違いを比較します。'],'construction-real-estate':['建設の活動と、不動産の付加価値を分けて読む。','建設は建物・インフラをつくる活動、不動産・賃貸は建物等を利用・賃貸する活動です。不動産GDPには持家の帰属家賃も含まれるため、GDPの割合を就業者の割合と同一視しません。']};
export function initCanadaIndustryParity(root:HTMLElement){
 const config=JSON.parse(root.querySelector('[data-ca-industry-config]')!.textContent!);const metrics:Metric[]=config.metrics;const total=metrics[0];
 const q=<T extends Element=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const svg=q<SVGSVGElement>('[data-ca-map]');let sector='all',subsector='all',province:string|null=null,frame=[...canadaWaterFullFrame];
 const corners=config.geometry.flatMap((g:any)=>[canadaLegacyPoint(g.bounds.slice(0,2)),canadaLegacyPoint(g.bounds.slice(2,4))]),xs=corners.map((p:number[])=>p[0]),ys=corners.map((p:number[])=>p[1]),bounds=[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)],wholeWidth=1.08*Math.max(bounds[2]-bounds[0],(bounds[3]-bounds[1])*900/580),wholeHeight=wholeWidth*580/900,wholeFrame=[(bounds[0]+bounds[2]-wholeWidth)/2,(bounds[1]+bounds[3]-wholeHeight)/2,wholeWidth,wholeHeight];
 const fmt=(n:number)=>n.toLocaleString('ja-JP',{maximumFractionDigits:1});
 function read(){const p=new URL(location.href).searchParams;const legacy=p.get('metric');sector=p.get('sector')??(legacy==='mining'?'resources':legacy==='manufacturing'?'manufacturing':legacy==='services'?'services':'all');if(!industrySectors.some(s=>s.id===sector))sector='all';subsector=p.get('subsector')??'all';if(!metrics.some(m=>m.id===subsector&&m.sector===sector))subsector='all';province=total.provinces.some(pv=>pv.id===p.get('province'))?p.get('province'):null;const parts=(p.get('industryFrame')??'').split(','),saved=parts.map(Number);frame=parts.length===4&&parts.every(v=>v.trim()!=='')&&saved.every(Number.isFinite)&&Math.abs(saved[0])<=4000&&Math.abs(saved[1])<=4000&&saved[2]>=150&&saved[2]<=2600&&saved[3]>=100&&saved[3]<=2600?saved:[...canadaWaterFullFrame];}
 function save(){const u=new URL(location.href);for(const k of ['metric','year','compare','only','zoom'])u.searchParams.delete(k);for(const [k,v]of Object.entries({sector,subsector,province})){if(v&&v!=='all')u.searchParams.set(k,v);else u.searchParams.delete(k);}if(u.href!==location.href)history.pushState(null,'',u);render();}
 function selected(){return metrics.find(m=>m.id===(subsector==='all'?sector:subsector))!;}
 function selectPlace(id:string){province=id;save();}
 function chart(){
  let rows:any[]=sector==='all'?config.nationalChart:sector==='services'||sector==='construction-real-estate'?config.nationalChart.filter((r:any)=>r.sector===sector):metrics.filter(m=>m.sector===sector&&m.id!==sector).map(m=>({id:m.id,label:m.label,gdp:m.gdp,employment:m.employment,sector}));
  const denominator=metrics.find(m=>m.id===sector)!;
  if(sector==='manufacturing'||sector==='resources'){const sum=rows.reduce((s,r)=>s+r.gdp,0);if(denominator.gdp-sum>1)rows.push({id:'other',label:sector==='manufacturing'?'その他の製造業':'採掘支援活動',gdp:denominator.gdp-sum,employment:null,sector});}
  rows=[...rows].sort((a,b)=>a.gdp-b.gdp);q('[data-ca-chart-title]').textContent=`${denominator.label}の全国構成`;q('[data-ca-chart-scope]').textContent=`${denominator.label}を100%`;
  const bars=q('[data-ca-bars]');bars.replaceChildren();const table=document.createElement('table');const caption=document.createElement('caption');caption.textContent='2021年 · 百万カナダドル／千人';table.append(caption);
  const thead=document.createElement('thead');thead.innerHTML='<tr><th scope="col">区分</th><th scope="col">付加価値</th><th scope="col">雇用</th></tr>';table.append(thead);const tbody=document.createElement('tbody');table.append(tbody);
  for(const r of rows){const li=document.createElement('li');const row=document.createElement('div');row.className='industry-paired-row';const name=document.createElement('span');name.className='industry-paired-name';name.textContent=r.label;row.append(name);for(const key of ['gdp','employment']){const value=r[key],den=(denominator as any)[key];const cell=document.createElement('span');cell.className='industry-paired-cell';cell.dataset.industryMetric=key;const share=value===null||!den?null:value/den*100;const strong=document.createElement('strong');strong.textContent=share===null?'—':share.toFixed(1);if(share!==null){const small=document.createElement('small');small.textContent='%';strong.append(small);}else cell.title='原表に対応する細分類の値なし';const track=document.createElement('i');track.className='industry-paired-track';const bar=document.createElement('b');bar.style.width=`${share??0}%`;bar.style.setProperty('--industry-color',config.colors[r.sector]??'#64815d');track.append(bar);cell.append(strong,track);row.append(cell);}li.append(row);bars.append(li);const tr=document.createElement('tr');for(const [i,value]of [r.label,fmt(r.gdp),r.employment===null?'—':fmt(r.employment)].entries()){const td=document.createElement(i===0?'th':'td');if(i===0)td.setAttribute('scope','row');td.textContent=value;tr.append(td);}tbody.append(tr);}
  q('[data-ca-numbers]').replaceChildren(table);if(rows.some(r=>r.employment===null)){const note=document.createElement('p');note.textContent='—：この雇用原表には対応する細分類の値がありません。雇用全体の比較は「全産業」で確認できます。';q('[data-ca-numbers]').append(note);}
 }
 function labels(){const m=selected(),all=subsector==='all';const ranked=[...m.provinces].sort((a,b)=>b.gdp-a.gdp);const stageWidth=q('[data-ca-map-frame]').clientWidth;const shown=all?ranked:ranked.slice(0,5),labelIds=new Set(ranked.slice(0,stageWidth<600?6:8).map(p=>p.id));if(province)labelIds.add(province);if(province&&!shown.some(p=>p.id===province))shown.push(m.provinces.find(p=>p.id===province)!);if(province)shown.sort((a,b)=>Number(b.id===province)-Number(a.id===province));const overlay=q('[data-ca-labels]');overlay.replaceChildren();const matrix=svg.getScreenCTM?.();if(!matrix)return;const stage=q('[data-ca-map-frame]').getBoundingClientRect();const max=ranked[0].gdp;const occupied:number[][]=[[stage.width-60,0,stage.width,205],[0,stage.height-35,stage.width,stage.height]];for(const p of shown){const source=config.geometry.find((g:any)=>g.id===p.id);if(!source)continue;const point=svg.createSVGPoint();[point.x,point.y]=canadaLegacyPoint(source.point);const projected=point.matrixTransform(matrix),x=projected.x-stage.x,y=projected.y-stage.y,r=all?7:Math.sqrt(p.gdp/max)*33+4;if(x>=0&&x<=stage.width&&y>=0&&y<=stage.height)occupied.push([x-r,y-r,x+r,y+r]);}const ns='http://www.w3.org/2000/svg';const lines=document.createElementNS(ns,'svg');lines.setAttribute('width','100%');lines.setAttribute('height','100%');lines.style.cssText='position:absolute;inset:0;pointer-events:none';overlay.append(lines);
 for(const p of shown){const source=config.geometry.find((g:any)=>g.id===p.id);if(!source)continue;const pt=svg.createSVGPoint();[pt.x,pt.y]=canadaLegacyPoint(source.point);const screen=pt.matrixTransform(matrix),x=screen.x-stage.x,y=screen.y-stage.y;if(x<0||x>stage.width||y<0||y>stage.height)continue;const b=document.createElement('button');b.type='button';b.className='ca-industry-marker';b.style.left=`${x}px`;b.style.top=`${y}px`;b.style.setProperty('--industry-color',config.colors[sector]);b.setAttribute('aria-pressed',String(province===p.id));b.dataset.caMarker=p.id;b.setAttribute('aria-label',p.name+'の産業を読む');
 const dot=document.createElement('i');dot.style.width=dot.style.height=`${all?8:Math.sqrt(p.gdp/max)*66}px`;const text=document.createElement('span');const title=document.createElement('strong');title.textContent=p.name;const detail=document.createElement('small');if(all){detail.textContent=metrics.filter(v=>v.id!==v.sector&&(sector==='all'||v.sector===sector)).map(v=>({name:v.label,gdp:v.provinces.find(pv=>pv.id===p.id)!.gdp})).sort((a,b)=>b.gdp-a.gdp).slice(0,2).map(v=>v.name).join('・');}else detail.textContent=`${fmt(p.gdp/1000)}十億CAD`;text.append(title,detail);b.append(dot,text);b.addEventListener('click',()=>selectPlace(p.id));overlay.append(b);
 const anchor=document.createElementNS(ns,'circle');anchor.dataset.caAnchor=p.id;anchor.setAttribute('cx',String(x));anchor.setAttribute('cy',String(y));anchor.setAttribute('r','2.5');anchor.setAttribute('fill','#47665b');lines.append(anchor);
 if(all&&!labelIds.has(p.id)){text.hidden=true;const hit=44;b.style.width=b.style.height=hit+'px';b.style.left=(x-hit/2)+'px';b.style.top=(y-hit/2)+'px';continue;}
 const hit=Math.max(44,all?8:Math.sqrt(p.gdp/max)*66);b.style.width=b.style.height=`${hit}px`;b.style.left=`${x-hit/2}px`;b.style.top=`${y-hit/2}px`;const w=text.offsetWidth||140,h=text.offsetHeight||48;let chosen:number[]|undefined;const offsets=[];for(let dy=-240;dy<=240;dy+=48)for(let dx=-280;dx<=280;dx+=70)offsets.push([dx,dy]);offsets.sort((a,c)=>a[0]**2+a[1]**2-c[0]**2-c[1]**2);
 for(const [dx,dy]of offsets){const left=Math.max(4,Math.min(stage.width-w-4,x+dx-w*.3)),top=Math.max(4,Math.min(stage.height-h-4,y+dy-h/2));const box=[left,top,left+w,top+h];if(!occupied.some(([a,c,d,e])=>box[0]<d+3&&box[2]>a-3&&box[1]<e+3&&box[3]>c-3)){chosen=box;break;}}
 if(!chosen){text.hidden=true;continue;}if(chosen){occupied.push([chosen[0],chosen[1],chosen[0]+w,chosen[1]+h]);text.style.left=`${chosen[0]-x+hit/2}px`;text.style.top=`${chosen[1]-y+hit/2}px`;if(Math.abs(chosen[0]+w/2-x)+Math.abs(chosen[1]+h/2-y)>35){const line=document.createElementNS(ns,'line');for(const [k,v]of Object.entries({x1:x,y1:y,x2:chosen[0]+w/2,y2:chosen[1]+h/2}))line.setAttribute(k,String(v));line.setAttribute('stroke','#718e87');line.setAttribute('stroke-width','.8');lines.append(line);}}

 }

 }
 function camera(persist=false){svg.setAttribute('viewBox',frame.join(' '));labels();if(persist){const u=new URL(location.href);u.searchParams.set('industryFrame',frame.map(v=>Number(v.toFixed(3))).join(','));history.pushState(null,'',u);} (root as any).canadaIndustryView={frame:frame.slice(),wholeFrame:wholeFrame.slice(),province,sector,subsector};}
 function render(){const m=selected();
 const raw=new URL(location.href).searchParams.get('populationReturn');const wrap=q('[data-ca-population-return-wrap]');wrap.hidden=true;
 if(raw){const source=new URL('?'+raw,location.href);if(!isCanadaDemographicTopic(source.searchParams.get('topic'))){const state=readCanadaPopulationState(source,population.cmas.map(p=>p.id));const back=q<HTMLAnchorElement>('[data-canada-population-industry-return]');back.href=copyCanadaPopulationMapState(source,writeCanadaPopulationState(new URL(back.getAttribute('href')!,location.href),state)).href;back.textContent=`元の${state.year}年${state.metric==='density'?'人口密度':'都市圏人口'}比較へ戻る`;wrap.hidden=false;}}
root.dataset.industrySubsector=subsector;q('#ca-industry-panel').setAttribute('aria-labelledby',`ca-sector-${sector}`);
 for(const b of root.querySelectorAll<HTMLElement>('[data-ca-sector]')){const on=b.dataset.caSector===sector;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;}
 for(const row of root.querySelectorAll<HTMLElement>('[data-ca-subtabs]'))row.hidden=row.dataset.caSubtabs!==sector;
 for(const b of root.querySelectorAll<HTMLElement>('[data-ca-subsector]')){const on=b.dataset.caSubsector===subsector;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;}
 q('[data-ca-breadcrumb]').textContent=m.label;q('[data-ca-title]').textContent=sector==='all'?'産業の立地と全国構成':m.label;q('[data-ca-lead]').textContent=reading[sector][0];
 const ranked=[...m.provinces].sort((a,b)=>b.gdp-a.gdp),p=m.provinces.find(p=>p.id===province);q('[data-ca-heading]').textContent=p?p.name:sector==='all'?'全国の産業配置':'GDPの大きい地域';q('[data-ca-reading]').textContent=p?`${p.name}の${m.label}GDPは${fmt(p.gdp/1000)}十億カナダドルで、この分野の全国計の${(p.gdp/m.gdp*100).toFixed(1)}%です。${reading[sector][1]}`:sector==='all'?'オンタリオ・ケベックの加工業とサービス、西部の資源関連産業を対比します。資源の位置だけでなく、道路・鉄道・水路と市場とのつながりを合わせて読みます。':`${ranked.slice(0,3).map(p=>p.name).join('、')}の順にGDPが大きい分野です。${reading[sector][1]}`;
 q('[data-ca-clear]').hidden=!p;q('[data-ca-reading]').hidden=!p&&sector==='all';q('[data-ca-operation-reading]').textContent=reading.all[1];const patterns=q<HTMLElement>('[data-ca-national-patterns]');patterns.hidden=!!p||sector!=='all';patterns.replaceChildren();if(!p&&sector==='all')for(const [id,title]of [['manufacturing','製造業：中央部の加工と輸送'],['resources','資源・エネルギー：資源から市場へ'],['services','サービス：人と仕事の集まり']]){const metric=metrics.find(m=>m.id===id)!,top=[...metric.provinces].sort((a,b)=>b.gdp-a.gdp).slice(0,3),section=document.createElement('section'),button=document.createElement('button'),paragraph=document.createElement('p');button.type='button';button.dataset.caPattern=id;button.textContent=title;button.addEventListener('click',()=>{sector=id;subsector='all';province=null;save();});paragraph.textContent='この分野の国内GDPは、'+top.map(p=>p.name+' '+(p.gdp/metric.gdp*100).toFixed(1)+'%').join('、')+'。'+reading[id][1];section.append(button,paragraph);patterns.append(section);}
 q('[data-ca-value]').hidden=!p;if(p)q('[data-ca-value]').textContent=`2021年 · ${m.label} · ${fmt(p.gdp)}百万CAD`;
 for(const shape of root.querySelectorAll<SVGPathElement>('[data-ca-province-shape]')){shape.classList.toggle('is-selected',shape.dataset.caProvinceShape===province);shape.setAttribute('aria-pressed',String(shape.dataset.caProvinceShape===province));}
 q('[data-ca-key]').textContent=subsector==='all'?'13州・準州の参照位置。ラベルは主要州のGDP上位2分野で、工場・鉱山の地点ではありません。全地域は下の一覧から選べます。':'丸の面積＝選択分野の州別GDP。全国上位5州を表示（2021年・当年価格）。州内割合を表す塗り分けではありません。';q('[data-ca-map-caption]').textContent=`${m.label} · ${subsector==='all'?'地形・水系と地域の産業':'GDP上位5州'}`;chart();requestAnimationFrame(()=>camera());
 }
 q('[data-ca-clear]').addEventListener('click',()=>{province=null;save();});
 for(const shape of root.querySelectorAll<SVGPathElement>('[data-ca-province-shape]')){const id=shape.dataset.caProvinceShape!;shape.setAttribute('role','button');shape.setAttribute('tabindex','0');shape.setAttribute('aria-label',total.provinces.find(p=>p.id===id)!.name+'を選ぶ');shape.addEventListener('click',()=>selectPlace(id));shape.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectPlace(id);}});}
 root.querySelector<HTMLAnchorElement>('[href="#canada-industry-statistics"]')!.addEventListener('click',()=>{q<HTMLDetailsElement>('.canada-industry-statistics').open=true;});
 for(const b of root.querySelectorAll<HTMLElement>('[data-ca-sector]'))b.addEventListener('click',()=>{sector=b.dataset.caSector!;subsector='all';province=null;save();});
 for(const b of root.querySelectorAll<HTMLElement>('[data-ca-subsector]'))b.addEventListener('click',()=>{subsector=b.dataset.caSubsector!;province=null;save();});
 for(const list of root.querySelectorAll('[role=tablist]'))list.addEventListener('keydown',(event)=>{const e=event as KeyboardEvent;const tabs=[...list.querySelectorAll<HTMLButtonElement>('[role=tab]')],i=tabs.indexOf(document.activeElement as HTMLButtonElement);if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||i<0)return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[j].click();tabs[j].focus();});
 for(const b of root.querySelectorAll<HTMLElement>('[data-ca-place]'))b.addEventListener('click',()=>{selectPlace(b.dataset.caPlace!);});
 for(const b of root.querySelectorAll<HTMLElement>('[data-ca-camera]'))b.addEventListener('click',()=>{if(b.dataset.caCamera==='reset')frame=[...canadaWaterFullFrame];else if(b.dataset.caCamera==='whole')frame=wholeFrame.slice();else{const factor=b.dataset.caCamera==='in'?.75:1/.75,w=Math.min(2600,Math.max(150,frame[2]*factor)),h=w*frame[3]/frame[2];frame=[frame[0]+(frame[2]-w)/2,frame[1]+(frame[3]-h)/2,w,h];}camera(true);});
 svg.addEventListener('keydown',e=>{if(e.target!==svg)return;const delta:Record<string,number[]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(delta[e.key]){e.preventDefault();frame[0]+=delta[e.key][0]*frame[2]*.1;frame[1]+=delta[e.key][1]*frame[3]*.1;camera(true);}});
 let drag:{x:number;y:number;frame:number[];moved:boolean}|null=null,ignoreClick=false;
 svg.addEventListener('pointerdown',e=>{if(e.button===0)drag={x:e.clientX,y:e.clientY,frame:frame.slice(),moved:false};});
 svg.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)<4)return;drag.moved=true;svg.setPointerCapture?.(e.pointerId);const matrix=svg.getScreenCTM()!;frame=[drag.frame[0]-dx/matrix.a,drag.frame[1]-dy/matrix.d,drag.frame[2],drag.frame[3]];camera();});
 svg.addEventListener('pointerup',()=>{if(drag?.moved){ignoreClick=true;camera(true);}drag=null;});svg.addEventListener('pointercancel',()=>{drag=null;});svg.addEventListener('click',e=>{if(ignoreClick){e.stopPropagation();ignoreClick=false;}},true);
 document.fonts?.ready.then(labels);
 window.addEventListener('popstate',()=>{read();render();});window.addEventListener('resize',labels);read();render();
}
