import {readCanadaPopulationState,writeCanadaPopulationState,formatCanadaPopulationValue,canadaPopulationDensityColor,canadaPopulationFrame,populationDensityColors} from '../lib/atlas-canada-population';
import type {CanadaNatureState} from '../lib/atlas-canada-nature';

export function renderPopulationNatureComparison(root:HTMLElement,config:any,nature:CanadaNatureState){
 const physical=nature.view==='landform'||nature.view==='elevation';
 const raw=new URL(location.href).searchParams.get('populationReturn'),context=root.querySelector<HTMLElement>('[data-canada-population-context]')!,layer=root.querySelector<SVGElement>('[data-canada-population-context-map]')!,legend=root.querySelector<HTMLElement>('[data-canada-population-context-legend]')!,back=root.querySelector<HTMLAnchorElement>('[data-canada-population-return]')!,mini=root.querySelector<SVGSVGElement>('[data-canada-population-context-mini-map]')!;
 context.hidden=back.hidden=!raw;legend.hidden=!raw||physical;layer.style.display=raw&&!physical?'':'none';mini.style.display=raw&&physical?'':'none';
 const position=root.querySelector<HTMLElement>('[data-canada-position-caption]')!;position.dataset.originalCaption??=position.textContent!;position.textContent=raw?'小さい点は気候観測地点。人口円の中心は都市圏の表示用位置で、都心や居住地点ではありません。位置図は等緯度経度表示で、面積の測定には使いません。':position.dataset.originalCaption;
 if(!raw)return false;
 const data=config.population,state=readCanadaPopulationState(new URL('?'+raw,location.href),data.cmas.map((c:any)=>c.id)),target=new URL(back.getAttribute('href')!,location.href);target.search=writeCanadaPopulationState(new URL(target.pathname,target),state).search;back.href=target.href;
 const chosen=[state.cma,state.compare].filter(Boolean),records=data.cmas.filter((c:any)=>chosen.includes(c.id)),city=config.cities.find((c:any)=>c.id===nature.city).name;
 const values=records.map((r:any)=>{const v=state.metric==='density'?r.density2021:r.population[state.year];return `${r.name} ${formatCanadaPopulationValue(v.value,state.metric)}${state.metric==='density'?'人/km²':'人'}${v.symbol?' '+v.symbol:''}`;}).join(' / ');
 const water=nature.water?`現在は${nature.water}${nature.only?'だけ':'を選び全水系'}を表示。${nature.water!=='Lake Ontario'?'元の比較入口はOntario湖です。':''}`:'現在は全水系を表示。';
 const question=nature.view==='water'?`${water} 都市圏の集中と南部の水域位置を比べます。水路の位置は交通の条件で、人口の原因を単独で決めません。`:physical?'都市圏の元分布と、地形・標高図の南部・山地・沿岸を左右で照合します。地形・標高図は別投影のため重ねません。':`${city}は1観測点。都市圏全体の平均気候ではありません。人口の分布と冬の気温・季節降水を比べます。`;
 root.querySelector<HTMLElement>('[data-canada-population-context-text]')!.textContent=`${state.year}年 ${values}。${question}`;
 if(!data.geometry?.every((g:any)=>Array.isArray(g.rings))){layer.replaceChildren();mini.replaceChildren();const message=root.dataset.populationGeometryState==='error'?'元の都市圏境界を取得できませんでした。元の人口ページと出典を確認できます。':'元の都市圏分布を読み込んでいます。';legend.textContent=message;root.querySelector<HTMLElement>('[data-canada-population-context-mini-legend]')!.textContent=message;return true;}
 const ns='http://www.w3.org/2000/svg',max=Math.max(...data.cmas.flatMap((r:any)=>[r.population[2016].value??0,r.population[2021].value??0])),frame=nature.frame??[0,0,900,580],scale=frame[2]/760,project=([lon,lat]:number[])=>[(lon+145)/95*900,(85-lat)/45*580];layer.replaceChildren();
 for(const g of data.geometry){if(state.only&&!chosen.includes(g.id))continue;const r=data.cmas.find((r:any)=>r.id===g.id),v=state.metric==='density'?r.density2021:r.population[state.year],group=root.ownerDocument.createElementNS(ns,'g');group.dataset.canadaPopulationContextCma=g.id;const title=root.ownerDocument.createElementNS(ns,'title');title.textContent=`${r.name}都市圏 ${state.year}年 ${formatCanadaPopulationValue(v.value,state.metric)} ${state.metric==='density'?'人/km²':'人'}${v.symbol?' '+v.symbol:''}`;group.append(title);const boundary=root.ownerDocument.createElementNS(ns,'path');boundary.dataset.canadaPopulationContextBoundary='';boundary.setAttribute('d',g.rings.map((ring:number[][])=>ring.map((xy,i)=>{const [x,y]=project(xy);return `${i?'L':'M'}${x.toFixed(3)},${y.toFixed(3)}`;}).join('')+'Z').join(''));boundary.setAttribute('fill-rule','evenodd');boundary.setAttribute('fill',state.metric==='density'?canadaPopulationDensityColor(v.value):'#c7d9bc');boundary.setAttribute('stroke',chosen.includes(g.id)?'#a64125':'#567968');boundary.setAttribute('stroke-width',chosen.includes(g.id)?'2':'0.7');group.append(boundary);const circle=root.ownerDocument.createElementNS(ns,'circle');circle.dataset.canadaPopulationContextSymbol='';circle.setAttribute('cx',String(g.point[0]));circle.setAttribute('cy',String(g.point[1]));circle.setAttribute('r',String(v.value===null?0:Math.sqrt(v.value/max)*22*scale));circle.setAttribute('fill','#426d84');circle.setAttribute('fill-opacity','.62');circle.setAttribute('stroke',chosen.includes(g.id)?'#a64125':'#fff');circle.setAttribute('stroke-width','1');circle.style.display=state.metric==='population'&&v.value!==null?'':'none';group.append(circle);layer.append(group);}
 function labelMarkers(group:SVGElement,factor:number){for(const marker of group.querySelectorAll<SVGElement>('[data-canada-population-context-cma]')){const id=marker.dataset.canadaPopulationContextCma!,g=data.geometry.find((g:any)=>g.id===id),r=data.cmas.find((r:any)=>r.id===id);if(state.metric==='population')marker.querySelector('[data-canada-population-context-symbol]')!.setAttribute('r',String(r.population[state.year].value===null?0:Math.sqrt(r.population[state.year].value/max)*22*factor));if(chosen.includes(id)){const text=root.ownerDocument.createElementNS(ns,'text');text.dataset.canadaPopulationContextLabel=id;text.setAttribute('x',String(g.point[0]+7*factor));text.setAttribute('y',String(g.point[1]-26*factor));text.style.cssText=`font-size:${22*factor}px;paint-order:stroke;stroke:#fff;stroke-width:${3*factor}px;fill:#254539;pointer-events:none`;text.textContent=r.name.split('（')[0];marker.querySelector('[data-canada-population-context-label]')?.remove();marker.append(text);}}}
 function addScale(group:SVGElement,box:number[]){const factor=box[2]/760,key=root.ownerDocument.createElementNS(ns,'g');key.dataset.canadaPopulationContextScale='';key.setAttribute('transform',`translate(${box[0]+12*factor},${box[1]+12*factor}) scale(${factor})`);const rect=root.ownerDocument.createElementNS(ns,'rect');rect.setAttribute('width',state.metric==='population'?'320':'710');rect.setAttribute('height','57');rect.setAttribute('fill','#fff');rect.setAttribute('fill-opacity','.93');key.append(rect);const text=(x:number,y:number,label:string)=>{const t=root.ownerDocument.createElementNS(ns,'text');t.setAttribute('x',String(x));t.setAttribute('y',String(y));t.style.fontSize='20px';t.textContent=label;key.append(t);};if(state.metric==='population'){for(const [count,x] of [[1000000,25],[5000000,165]]){const circle=root.ownerDocument.createElementNS(ns,'circle');circle.setAttribute('cx',String(x));circle.setAttribute('cy','27');circle.setAttribute('r',String(Math.sqrt(count/max)*22));circle.setAttribute('fill','#426d84');circle.setAttribute('fill-opacity','.62');circle.dataset.canadaPopulationLegendCount=String(count);key.append(circle);text(x+27,34,count===1000000?'100万人':'500万人');}}else{for(const [i,label] of ['50未満','50–150未満','150–300未満','300–600未満','600以上'].entries()){const swatch=root.ownerDocument.createElementNS(ns,'rect');swatch.setAttribute('x',String(i*135+5));swatch.setAttribute('y','10');swatch.setAttribute('width','24');swatch.setAttribute('height','20');swatch.setAttribute('fill',populationDensityColors[i]);swatch.dataset.canadaPopulationDensitySwatch=String(i);key.append(swatch);text(i*135+5,51,label);}text(676,26,'人/km²');}group.append(key);}
 labelMarkers(layer,scale);addScale(layer,frame);
 const copy=layer.cloneNode(true) as SVGElement;copy.style.display='';copy.querySelector('[data-canada-population-context-scale]')?.remove();const miniFrame=canadaPopulationFrame({...state,zoom:state.only?'selected':'south'},data.geometry);mini.setAttribute('viewBox',miniFrame.join(' '));labelMarkers(copy,miniFrame[2]/760);addScale(copy,miniFrame);mini.replaceChildren(...[...root.querySelectorAll('[data-canada-map] .canada-land')].map(p=>p.cloneNode(true)),copy);
 const note=`元の分布：${state.metric==='density'?'2021年人口密度（人/km²）':'人口 '+state.year+'年（円の面積）'}。都市圏境界2021年固定。水域：Natural Earth 1:50m。気候：ECCC 1991–2020年平年値（点）。`;
 legend.textContent=note;const miniLegend=root.querySelector<HTMLElement>('[data-canada-population-context-mini-legend]')!;miniLegend.hidden=!physical;miniLegend.textContent=note+' 地形・標高図は別投影です。';
 return true;
}
