import test from 'node:test';import assert from 'node:assert/strict';import {readFile,access} from 'node:fs/promises';import {transform} from 'esbuild';import {Window} from 'happy-dom';
const folder='atlas/north-america/canada/population',config=JSON.parse(await readFile('src/data/atlas/canada/population.json','utf8')),lib=await readFile('src/lib/atlas-canada-population.ts','utf8'),controller=(await readFile('src/scripts/atlas-canada-population.ts','utf8')).replace(/^import .*;\r?\n/,''),code=(await transform(`${lib}\n${controller}\ninitCanadaPopulation(document.querySelector('[data-canada-population]'));`,{loader:'ts',format:'iife'})).code;
async function page(search='',interactive=false,patch,stored){const w=new Window({url:`https://example.com/insight-journal/${folder}/${search}`,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:interactive,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write((await readFile(`dist/${folder}/index.html`,'utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));if(patch){const el=w.document.querySelector('[data-population-config]'),cfg=JSON.parse(el.textContent);patch(cfg);el.textContent=JSON.stringify(cfg);}if(stored)w.localStorage.setItem('insight-journal:canada-population:v1',stored);if(interactive)w.eval(code);return w;}
test('Population no-JS HTML shows honest 2021 circles, initial bars, complete source tables and dated definitions',async()=>{
 const w=await page();try{const d=w.document;assert.equal(d.querySelectorAll('[data-population-map-cma]').length,41);assert.equal(d.querySelectorAll('[data-population-row]').length,41);assert.equal(d.querySelectorAll('[data-population-national]').length,14);assert.equal(d.querySelector('[data-population-map]').getAttribute('viewBox'),'140 340 760 240');assert.match(d.querySelector('[data-population-comparison]').textContent,/6,202,225/);const max=d.querySelector('[data-population-row="535"] [data-population-bar]');assert.equal(max.style.width,'100%');assert.ok(parseFloat(d.querySelector('[data-population-row="462"] [data-population-bar]').style.width)<100);assert.ok(parseFloat(d.querySelector('[data-population-map-cma="462"] [data-population-symbol]').getAttribute('r'))<22);assert.match(d.querySelector('[data-population-row="462"]').textContent,/4,104,074 r/);assert.match(d.querySelector('#canada-population-comparisons').textContent,/rは改定.*2021年.*不完全/s);assert.match(d.querySelector('#canada-population-sources').textContent,/Adapted from Statistics Canada.*2016 and 2021.*This does not constitute an endorsement/s);assert.match(d.querySelector('#canada-population-sources').textContent,/OGL–Canada.*EPSG:3347.*250m/s);assert.match(d.querySelector('.population-more').textContent,/2016–2019.*2026年現在/s);assert.match(d.querySelector('noscript').textContent,/全55地域/);assert.equal(d.querySelectorAll('.population-tables[open]').length,0);assert.ok(d.querySelector('[data-news-rail]'));for(const name of ['population-selected.csv','manifest.json','population-boundaries.geojson']){assert.ok(d.querySelector(`a[href$="${name}"]`));await access(`dist/assets/atlas/canada-population-v1/${name}`);}assert.ok(!d.querySelector('[data-population-map]').innerHTML.includes('NaN'));
 }finally{await w.happyDOM.close();}
});
test('All 41 CMA, two population years and 2021 density show correct original values and single Ottawa–Gatineau',async()=>{
 const w=await page('',true);try{const d=w.document,q=s=>d.querySelector(s),change=(s,v)=>{q(s).value=String(v);q(s).dispatchEvent(new w.Event('change'));};for(const year of config.years){change('[data-population-metric]','population');change('[data-population-year]',year);for(const r of config.cmas){change('[data-population-cma]',r.id);assert.ok(q('[data-population-comparison]').textContent.includes(r.population[year].value.toLocaleString('ja-JP')));assert.ok(q('[data-population-comparison]').textContent.includes(r.name));if(r.population[year].symbol)assert.ok(q('[data-population-comparison]').textContent.includes(r.population[year].symbol));}assert.ok(q('[data-population-map-status]').textContent.includes('境界は2021年固定'));const radius=Number(q('[data-population-map-cma="535"] [data-population-symbol]').getAttribute('r'));assert.ok(Math.abs(radius-22*Math.sqrt(config.cmas.find(r=>r.id==='535').population[year].value/config.cmas.find(r=>r.id==='535').population[2021].value))<1e-10);}
 change('[data-population-metric]','density');assert.equal(q('[data-population-year]').value,'2021');assert.equal(q('[data-population-year]').disabled,true);for(const r of config.cmas){change('[data-population-cma]',r.id);assert.ok(q('[data-population-comparison]').textContent.includes(r.density2021.value.toLocaleString('ja-JP',{minimumFractionDigits:1,maximumFractionDigits:1})));assert.equal(q(`[data-population-map-cma="${r.id}"] [data-population-symbol]`).style.display,'none');}assert.equal(q('[data-population-density-legend]').hidden,false);assert.equal(d.querySelectorAll('[data-population-map-cma="505"]').length,1);change('[data-population-cma]','505');change('[data-population-compare]','535');assert.match(q('[data-population-comparison]').textContent,/Ottawa–Gatineau.*Toronto/s);change('[data-population-cma]','535');assert.equal(q('[data-population-compare]').value,'');
 }finally{await w.happyDOM.close();}
});
test('Population true isolation, keyboard selection, zoom, reset, URL/history/reload and storage all retain valid choices',async()=>{
 const search='?year=2016&cma=505&compare=535&metric=population&only=1&zoom=selected&keep=yes',w=await page(search,true);let reload,stored;try{const d=w.document,q=s=>d.querySelector(s);assert.equal(q('[data-population-cma]').value,'505');assert.equal(q('[data-population-year]').value,'2016');assert.equal([...d.querySelectorAll('[data-population-map-cma]')].filter(g=>g.style.display!=='none').length,2);assert.notEqual(q('[data-population-map]').getAttribute('viewBox'),'140 340 760 240');q('[data-population-only]').click();assert.equal([...d.querySelectorAll('[data-population-map-cma]')].filter(g=>g.style.display!=='none').length,41);q('[data-population-map-cma="933"]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(q('[data-population-cma]').value,'933');q('[data-population-locate="602"]').click();assert.equal(q('[data-population-cma]').value,'602');assert.equal(new URL(w.location).searchParams.get('keep'),'yes');q('[data-population-reset]').click();assert.equal(q('[data-population-map]').getAttribute('viewBox'),'140 340 760 240');assert.equal(q('[data-population-year]').value,'2016');
 w.history.replaceState(null,'','?year=2021&cma=462&compare=933&metric=density&only=1&zoom=country');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(q('[data-population-metric]').value,'density');assert.equal(q('[data-population-map]').getAttribute('viewBox'),'0 0 900 580');reload=await page(w.location.search,true);assert.equal(reload.document.querySelector('[data-population-cma]').value,'462');assert.equal(reload.document.querySelector('[data-population-only]').getAttribute('aria-pressed'),'true');stored=await page('',true,null,w.localStorage.getItem('insight-journal:canada-population:v1'));assert.equal(stored.document.querySelector('[data-population-cma]').value,'462');assert.equal(new URL(stored.location).searchParams.get('metric'),'density');
 }finally{await w.happyDOM.close();if(reload)await reload.happyDOM.close();if(stored)await stored.happyDOM.close();}
});
test('Population related nature actions preserve local CMA comparison and identify what readers should inspect',async()=>{
 const w=await page('?year=2016&cma=505&compare=535&metric=population&only=1&zoom=selected',true);try{const d=w.document;for(const a of d.querySelectorAll('[data-population-nature-link]')){const url=new URL(a.href),saved=new URLSearchParams(url.searchParams.get('populationReturn'));assert.equal(saved.get('cma'),'505');assert.equal(saved.get('compare'),'535');assert.equal(saved.get('year'),'2016');assert.equal(saved.get('zoom'),'selected');assert.equal(url.pathname,'/insight-journal/atlas/north-america/canada/nature/');assert.match(a.textContent,url.searchParams.get('view')==='landform'?/地形|山地|低地/:url.searchParams.get('view')==='water'?/湖|水域|河川/:/気温|雨|季節|気候/);}assert.ok([...d.querySelectorAll('a')].some(a=>a.href.includes('/canada/industry/')&&a.textContent.includes('市場')));for(const id of ['535','462','933','505','602','705'])assert.ok(d.querySelector(`[data-population-locate="${id}"]`));
 }finally{await w.happyDOM.close();}
});
test('Synthetic unpublished values and published zero stay distinct for controller circles and bars',async()=>{
 const w=await page('?cma=535&compare=462',true,cfg=>{cfg.cmas.find(r=>r.id==='535').population[2021]={value:0,symbol:'r'};cfg.cmas.find(r=>r.id==='462').population[2021]={value:null,symbol:'x'};});try{const d=w.document,zero=d.querySelector('[data-population-row="535"] [data-population-bar]'),missing=d.querySelector('[data-population-row="462"] [data-population-bar]');assert.equal(zero.style.width,'0%');assert.equal(missing.style.width,'0%');assert.equal(zero.parentElement.classList.contains('is-missing'),false);assert.equal(missing.parentElement.classList.contains('is-missing'),true);assert.equal(d.querySelector('[data-population-map-cma="462"] [data-population-symbol]').style.display,'none');assert.match(d.querySelector('[data-population-comparison]').textContent,/0 人 \(r\).*未公表 \(x\)/s);
 }finally{await w.happyDOM.close();}
});
