import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
import {transform} from 'esbuild';
import {Window} from 'happy-dom';
const lib=await readFile('src/lib/atlas-canada-agriculture.ts','utf8'),controller=(await readFile('src/scripts/atlas-canada-agriculture.ts','utf8')).replace(/^import .*;\r?\n/,'');
const code=(await transform(`${lib}\n${controller}\ninitCanadaAgriculture(document.querySelector('[data-canada-agriculture]'));`,{loader:'ts',format:'iife'})).code;
async function page(search='',interactive=false){const w=new Window({url:`https://example.com/insight-journal/atlas/north-america/canada/agriculture/${search}`,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:interactive,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write((await readFile('dist/atlas/north-america/canada/agriculture/index.html','utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));if(interactive)w.eval(code);return w;}
test('Canadian canola has fixed dated distribution, 44 source rows, causal prose, natural-environment transitions and complete sources without JS',async()=>{
 const w=await page();try{const d=w.document;assert.equal(d.querySelectorAll('[data-canola-row]').length,44);assert.equal(d.querySelectorAll('[data-canola-row]:not([hidden])').length,11);assert.equal(d.querySelectorAll('[data-canola-cell]').length,132);assert.match(d.querySelector('.canola-distribution figcaption').textContent,/2021.*10,000.*4,047.*ランダム.*農場/s);assert.match(d.querySelector('#canada-agriculture-sources').textContent,/2020.*2021.*2022.*2025.*Open Licence/s);assert.match(d.querySelector('.canola-scope').textContent,/畜産・林業は準備中/);assert.ok(d.querySelector('[data-news-rail]'));for(const a of d.querySelectorAll('a')){const u=new URL(a.href);if(u.origin==='https://example.com'&&u.pathname.includes('/atlas/'))await access(`dist/${u.pathname.replace('/insight-journal/','')}${u.pathname.endsWith('/')?'index.html':''}`);}const natural=await readFile('dist/atlas/north-america/canada/nature/index.html','utf8');assert.ok(natural.includes('/canada/agriculture/'));assert.ok((await readFile('dist/sitemap.xml','utf8')).includes('/canada/agriculture/'));}finally{await w.happyDOM.close();}
});
test('Canadian canola year and metric compare real values, keep map fixed and distinguish absence from reported zero and revised values',async()=>{
 const w=await page('?province=Canada&compare=Saskatchewan&metric=production',true);try{const d=w.document,q=s=>d.querySelector(s),change=(s,value)=>{q(s).value=value;q(s).dispatchEvent(new w.Event('change'));};const image=q('.canola-distribution img').src;assert.match(q('[data-canola-comparison]').textContent,/14,248,281.*r.*6,968,814.*r/);change('[data-canola-year]','2025');assert.equal(q('.canola-distribution img').src,image);assert.equal(d.querySelectorAll('[data-canola-row]:not([hidden])').length,11);assert.ok([...d.querySelectorAll('[data-canola-row]:not([hidden])')].every(r=>r.dataset.year==='2025'));change('[data-canola-year]','2021');change('[data-canola-province]','New Brunswick');assert.match(q('[data-canola-comparison]').textContent,/未収録.*F/);assert.ok(q('[data-canola-row="New Brunswick"][data-year="2021"] .canola-bar-track').classList.contains('is-missing'));change('[data-canola-province]','Newfoundland and Labrador');assert.match(q('[data-canola-comparison]').textContent,/0 t/);assert.ok(!q('[data-canola-row="Newfoundland and Labrador"][data-year="2021"] .canola-bar-track').classList.contains('is-missing'));}finally{await w.happyDOM.close();}
});
test('Canadian canola zoom, return, province selection, reload and history restore the independent comparison state',async()=>{
 const w=await page('?year=2022&province=Alberta&compare=Manitoba&metric=harvested&zoom=1',true);try{const d=w.document,q=s=>d.querySelector(s);assert.equal(q('[data-canola-year]').value,'2022');assert.equal(q('[data-canola-compare]').value,'Manitoba');assert.ok(q('[data-canola-map-scroll]').classList.contains('is-zoomed'));q('[data-canola-map-reset]').click();assert.ok(!q('[data-canola-map-scroll]').classList.contains('is-zoomed'));q('[data-canola-province-button=Manitoba]').click();assert.equal(q('[data-canola-compare]').value,'');assert.equal(new URL(w.location).searchParams.get('province'),'Manitoba');w.history.replaceState(null,'','?year=2020&province=Saskatchewan&compare=Canada&metric=seeded&zoom=1');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(q('[data-canola-year]').value,'2020');assert.equal(q('[data-canola-province]').value,'Saskatchewan');assert.equal(q('[data-canola-compare]').value,'Canada');assert.ok(q('[data-canola-map-scroll]').classList.contains('is-zoomed'));assert.match(q('[data-canola-comparison]').textContent,/2020年 作付面積/);}finally{await w.happyDOM.close();}
});
