import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
import {transform} from 'esbuild';
import {Window} from 'happy-dom';
const lib=await readFile('src/lib/atlas-canada-agriculture.ts','utf8'),controller=(await readFile('src/scripts/atlas-canada-agriculture.ts','utf8')).replace(/^import .*;\r?\n/,'');
const code=(await transform(`${lib}\n${controller}\ninitCanadaAgriculture(document.querySelector('[data-canada-agriculture]'));`,{loader:'ts',format:'iife'})).code;
async function page(search='',interactive=false){const w=new Window({url:`https://example.com/insight-journal/atlas/north-america/canada/agriculture/wheat/${search}`,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:interactive,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write((await readFile('dist/atlas/north-america/canada/agriculture/wheat/index.html','utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));if(interactive)w.eval(code);return w;}
test('Wheat initial HTML has honest ratios and F missingness, dated sources, distinct classes and causal reading without JavaScript',async()=>{
 const w=await page();try{const d=w.document,bar=id=>d.querySelector(`[data-canola-row="${id}"][data-year="2021"] [data-canola-bar]`);assert.equal(d.querySelectorAll('[data-canola-row]:not([hidden])').length,11);assert.equal(d.querySelectorAll('[data-canola-cell]').length,132);assert.equal(bar('Saskatchewan').style.width,'100%');assert.ok(Math.abs(parseFloat(bar('Alberta').style.width)-2813129/4827426*100)<1e-8);assert.equal(bar('Newfoundland and Labrador').style.width,'0%');assert.ok(bar('Newfoundland and Labrador').parentElement.classList.contains('is-missing'));assert.match(d.querySelector('.canola-distribution figcaption').textContent,/2021.*15,000.*6,070.*農場/s);assert.match(d.querySelector('#wheat-statistical-scope').textContent,/Wheat, all.*春小麦.*デュラム.*冬小麦.*センサス.*年次推計/s);assert.equal(d.querySelectorAll('[data-wheat-types] tbody tr').length,3);const reading=d.querySelector('.canada-reading').textContent;assert.match(reading,/輪作.*コンバイン.*乾燥.*貯蔵/s);assert.match(reading,/Vancouver.*日本.*等級/s);const source=d.querySelector('#canada-statcan-attribution').textContent;assert.match(source,/^Adapted from Statistics Canada,.*Total wheat area.*2021.*Table 32-10-0359-01.*September 30, 2026/s);assert.ok(source.endsWith('This does not constitute an endorsement by Statistics Canada of this product.'));assert.match(d.querySelector('.canola-scope').textContent,/カノーラ・小麦.*畜産・林業は準備中/s);assert.equal(d.querySelector('.canada-crop-tabs [aria-current=page]').textContent,'小麦');for(const a of d.querySelectorAll('a')){const u=new URL(a.href);if(u.origin==='https://example.com'&&u.pathname.includes('/atlas/'))await access(`dist/${u.pathname.replace('/insight-journal/','')}${u.pathname.endsWith('/')?'index.html':''}`);}assert.ok((await readFile('dist/sitemap.xml','utf8')).includes('/canada/agriculture/wheat/'));}finally{await w.happyDOM.close();}
});
test('Wheat uses shared controls for all years and metrics, fixed census map, real F, zero and revisions',async()=>{
 const w=await page('?province=Canada&compare=Saskatchewan&metric=production',true);try{const d=w.document,q=s=>d.querySelector(s),change=(s,v)=>{q(s).value=v;q(s).dispatchEvent(new w.Event('change'));};const image=q('.canola-distribution img').src;assert.match(q('[data-canola-comparison]').textContent,/22,422,100.*8,833,900/s);for(const y of ['2020','2021','2022','2025'])for(const m of ['seeded','harvested','production']){change('[data-canola-year]',y);change('[data-canola-metric]',m);assert.equal(q('.canola-distribution img').src,image);assert.equal(d.querySelectorAll('[data-canola-row]:not([hidden])').length,11);assert.ok([...d.querySelectorAll('[data-canola-row]:not([hidden])')].every(r=>r.dataset.year===y));assert.match(q('[data-canola-comparison]').textContent,m==='production'?/ t/:/ ha/);}change('[data-canola-year]','2021');change('[data-canola-province]','Newfoundland and Labrador');assert.match(q('[data-canola-comparison]').textContent,/未収録.*F/s);change('[data-canola-year]','2022');assert.match(q('[data-canola-comparison]').textContent,/0 t/);assert.ok(!q('[data-canola-row="Newfoundland and Labrador"][data-year="2022"] .canola-bar-track').classList.contains('is-missing'));change('[data-canola-province]','Canada');assert.match(q('[data-canola-comparison]').textContent,/34,878,782.*r/s);}finally{await w.happyDOM.close();}
});
test('Wheat reload and history keep comparison, metric and zoom on the wheat route without altering canola navigation',async()=>{
 const w=await page('?year=2025&province=Alberta&compare=Manitoba&metric=harvested&zoom=1',true);try{const d=w.document,q=s=>d.querySelector(s);assert.equal(q('[data-canola-year]').value,'2025');assert.equal(q('[data-canola-metric]').value,'harvested');assert.ok(q('[data-canola-map-scroll]').classList.contains('is-zoomed'));q('[data-canola-map-reset]').click();assert.ok(!q('[data-canola-map-scroll]').classList.contains('is-zoomed'));q('[data-canola-province-button=Manitoba]').click();assert.equal(q('[data-canola-compare]').value,'');assert.ok(w.location.pathname.endsWith('/agriculture/wheat/'));w.history.replaceState(null,'','?year=2020&province=Saskatchewan&compare=Canada&metric=seeded&zoom=1');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(q('[data-canola-year]').value,'2020');assert.equal(q('[data-canola-compare]').value,'Canada');assert.ok(q('[data-canola-map-scroll]').classList.contains('is-zoomed'));const canola=await readFile('dist/atlas/north-america/canada/agriculture/index.html','utf8');assert.ok(canola.includes('/canada/agriculture/wheat/'));assert.ok(canola.includes('canola-map-2021.jpg'));assert.ok(!/<table\b[^>]*\bdata-wheat-types\b/.test(canola));}finally{await w.happyDOM.close();}
});
