import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
import {transform} from 'esbuild';
import {Window} from 'happy-dom';
const lib=await readFile('src/lib/atlas-canada-nature.ts','utf8');
const controller=(await readFile('src/scripts/atlas-canada-nature.ts','utf8')).replace(/^import .*;\r?\n/,'');
const code=(await transform(`${lib}\n${controller}\ninitCanadaNature(document.querySelector('[data-canada-nature]'));`,{loader:'ts',format:'iife'})).code;
async function page(search='',interactive=false){const w=new Window({url:`https://example.com/insight-journal/atlas/north-america/canada/nature/${search}`,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:interactive,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write((await readFile('dist/atlas/north-america/canada/nature/index.html','utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));if(interactive)w.eval(code);return w;}
test('Canadian nature entry and dedicated route retain North America navigation, capital, numeric tables and complete sources',async()=>{
 await access('dist/atlas/north-america/canada/index.html');
 const w=await page();try{const d=w.document;assert.equal(d.querySelector('[data-canada-city]').value,'ottawa');assert.equal(d.querySelectorAll('[data-canada-climate-card]').length,5);assert.equal(d.querySelectorAll('[data-canada-climate-card] tbody tr').length,60);assert.equal(d.querySelectorAll('[data-canada-climate-card]:not([hidden])').length,1);assert.equal(d.querySelectorAll('[data-canada-water-shape]').length,233);assert.ok(d.querySelector('#canada-nature-sources'));assert.match(d.querySelector('#canada-nature-sources').textContent,/1991–2020.*2009.*1967/s);assert.match(d.querySelector('[data-canada-physical] figcaption').textContent,/投影が異なり/);assert.equal(d.querySelectorAll('[data-news-rail]').length,1);assert.deepEqual([...d.querySelectorAll('.regional-countries a')].map(a=>a.textContent),['カナダ','米国','メキシコ']);for(const a of d.querySelectorAll('.canada-fields a')){const p=new URL(a.href).pathname.replace('/insight-journal/','');await access(`dist/${p}index.html`);}assert.ok((await readFile('dist/sitemap.xml','utf8')).includes('/atlas/north-america/canada/nature/'));}finally{await w.happyDOM.close();}
});
test('Canadian climate comparison, keyboard city selection and history preserve map view and display requested data',async()=>{
 const w=await page('?city=regina&compare=ottawa&frame=200,200,400,250',true);try{const d=w.document,q=s=>d.querySelector(s),cards=()=>[...d.querySelectorAll('[data-canada-climate-card]:not([hidden])')].map(c=>c.dataset.canadaClimateCard);assert.deepEqual(cards().sort(),['ottawa','regina']);const view=q('[data-canada-map]').getAttribute('viewBox');q('[data-canada-city-button=vancouver]').click();assert.equal(q('[data-canada-map]').getAttribute('viewBox'),view);assert.equal(new URL(w.location).searchParams.get('city'),'vancouver');assert.deepEqual(cards().sort(),['ottawa','vancouver']);q('[data-canada-map-city=iqaluit]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(q('[data-canada-city]').value,'iqaluit');w.history.replaceState(null,'','?city=regina&compare=ottawa&view=landform');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(q('[data-canada-city]').value,'regina');assert.equal(q('[data-canada-physical]').hidden,false);assert.equal(q('[data-canada-locator]').hidden,true);q('[data-canada-view=climate]').click();assert.deepEqual(cards().sort(),['ottawa','regina']);assert.equal(q('[data-canada-physical]').hidden,true);}finally{await w.happyDOM.close();}
});
test('Canadian only-selected water actually removes every other distribution and return/history restore all',async()=>{
 const w=await page('',true);try{const d=w.document,q=s=>d.querySelector(s);q('[data-canada-view=water]').click();assert.equal(q('[data-canada-water-layers]').getAttribute('display'),'');const picker=q('[data-canada-water]');picker.value='Mackenzie';picker.dispatchEvent(new w.Event('change'));const only=q('[data-canada-only]');only.checked=true;only.dispatchEvent(new w.Event('change'));const shapes=[...d.querySelectorAll('[data-canada-water-shape]')];assert.ok(shapes.filter(s=>s.style.display!=='none').every(s=>s.dataset.canadaWaterShape==='Mackenzie'));assert.ok(shapes.some(s=>s.style.display==='none'));const saved=new URL(w.location).search;q('[data-canada-all-water]').click();assert.ok(shapes.every(s=>s.style.display!== 'none'));assert.equal(only.checked,false);w.history.replaceState(null,'',saved);w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(only.checked,true);assert.ok(shapes.filter(s=>s.style.display!=='none').every(s=>s.dataset.canadaWaterShape==='Mackenzie'));q('[data-canada-reset]').click();assert.equal(q('[data-canada-map]').getAttribute('viewBox'),'0 0 900 580');}finally{await w.happyDOM.close();}
});
