// Existing CI Chrome and acceptance artifact; no browser or workflow changes.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {execFileSync} from 'node:child_process';
import {readFile,mkdir,stat,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {chromium} from 'playwright';
import {createHash} from 'node:crypto';

test('西アジアの水系同時表示・250mm帯・500m帯をPC実画面で操作する',{skip:!process.env.CI,timeout:150000},async()=>{
 const output='/tmp/atlas-canada-qa/west-asia-natural';await mkdir(output,{recursive:true});
 const executablePath=process.env.REVIEW_CHROME_PATH||execFileSync('sh',['-c','command -v google-chrome || command -v google-chrome-stable'],{encoding:'utf8'}).trim();
 assert(executablePath);
 const records=[],errors=[],failures=[];
 const server=createServer(async(req,res)=>{
  try{const pathname=new URL(req.url,'http://localhost').pathname.replace(/^\/insight-journal/,'');let file=path.resolve('dist','.'+pathname);assert(file.startsWith(path.resolve('dist')+path.sep));if((await stat(file)).isDirectory())file=path.join(file,'index.html');const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.gz':'application/gzip','.png':'image/png','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]??'application/octet-stream'}).end(await readFile(file));}catch{res.writeHead(404).end();}
 });
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;let browser;
 try{
  browser=await chromium.launch({executablePath,headless:true,chromiumSandbox:true});
  for(const viewport of [{width:1440,height:1000},{width:1024,height:768}]){
   const context=await browser.newContext({viewport,serviceWorkers:'block'});await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(r.url());});
   const ready=()=>page.waitForFunction(()=>document.querySelector('[data-west-atlas]')?.dataset.ready==='true'&&document.querySelector('[data-west-loading]')?.hidden);
   const open=async query=>{await page.goto(origin+'/insight-journal/atlas/west-asia/nature/'+query);await ready();await page.evaluate(()=>document.fonts.ready);};
   const shot=async label=>{await page.evaluate(()=>window.scrollTo(0,0));const file=`${viewport.width}-${label}.jpg`,bytes=await page.screenshot({path:path.join(output,file),type:'jpeg',quality:90,animations:'disabled'});const boxes=await page.evaluate(()=>{const map=document.querySelector('[data-west-map]').getBoundingClientRect(),pane=document.querySelector('.west-reading').getBoundingClientRect();return {map:{width:map.width,height:map.height},pane:{top:pane.top,bottom:pane.bottom},overflow:document.documentElement.scrollWidth>innerWidth};});assert(boxes.map.width>200&&boxes.map.height>200);assert.equal(boxes.overflow,false);assert(boxes.pane.bottom<=viewport.height+1);records.push({file,viewport,sha256:createHash('sha256').update(bytes).digest('hex'),...boxes});};
   const pointer=async selector=>{const point=await page.evaluate(selector=>{const r=document.querySelector('[data-west-map]').getBoundingClientRect();for(let y=r.top+12;y<Math.min(r.bottom,innerHeight)-12;y+=7)for(let x=r.left+12;x<r.right-12;x+=7)if(document.elementFromPoint(x,y)?.closest(selector))return {x,y};},selector);assert(point,`actual pointer target: ${selector}`);await page.mouse.click(point.x,point.y);await ready();};
   const layerCounts=()=>page.evaluate(()=>({rain:document.querySelectorAll('[data-west-band="rainfall"]').length,lines:document.querySelectorAll('[data-west-aligned-line="rainfall"]').length,ground:document.querySelector('[data-west-water-groundwater]')?.children.length,rivers:document.querySelector('[data-west-water-rivers]')?.querySelectorAll('path').length,basins:document.querySelectorAll('[data-west-representative-basin]').length}));
   await open('');assert.equal(await page.locator('[data-west-country]').inputValue(),'');assert.equal(await page.locator('[data-west-city]').inputValue(),'');
   await page.locator('[data-west-standard-group="水資源"]').click();await ready();assert.equal(await page.locator('[data-west-atlas]').getAttribute('data-topic'),'water-overview');const counts=await layerCounts();assert.equal(counts.rain,107);assert.equal(counts.lines,75);assert.equal(counts.ground,166);assert.equal(counts.basins,2);assert.equal(counts.rivers,162);assert.equal(await page.locator('[data-country]').count(),0);const frame=await page.locator('[data-west-map]').getAttribute('viewBox');await shot('water-overview');
   await page.locator('[data-west-water-pick="groundwater"]').click();await ready();await pointer('[data-natural-feature^="ground:"]');await page.waitForFunction(()=>document.querySelector('[data-west-natural-selection]')?.textContent.includes('涵養区分'));assert.deepEqual(await layerCounts(),counts);assert.equal(await page.locator('[data-west-map]').getAttribute('viewBox'),frame);await shot('water-groundwater');const saved=page.url();await page.reload();await ready();assert((await page.locator('[data-west-natural-selection]').innerText()).includes('残存量・取水量ではありません'));assert.equal(page.url(),saved);
   await page.locator('[data-west-water-pick="rivers"]').click();await ready();await pointer('[data-natural-feature^="river:"]');assert((await page.locator('[data-west-natural-selection]').innerText()).includes('Natural Earth'));assert.deepEqual(await layerCounts(),counts);await shot('water-river');
   await page.locator('[data-west-water-pick="basins"]').click();await ready();await page.locator('[data-west-representative-basin="1060034260"]').press('Enter');await ready();assert((await page.locator('[data-west-regional-reading]').innerText()).includes('南の上流'));assert.equal(await page.locator('[data-west-map]').getAttribute('viewBox'),frame);assert.equal(await page.locator('[data-west-natural-selection] a').count(),1);await shot('water-nile');
   await page.locator('[data-west-natural-selection] a').click();await ready();assert.equal(await page.locator('[data-west-atlas]').getAttribute('data-topic'),'basins');assert(await page.evaluate(()=>{const svg=document.querySelector('[data-west-map]'),v=svg.viewBox.baseVal,b=svg.querySelector('[data-basin="1060034260"]').getBBox();return b.x>=v.x&&b.y>=v.y&&b.x+b.width<=v.x+v.width&&b.y+b.height<=v.y+v.height;}));await page.goBack();await ready();assert.equal(await page.locator('[data-west-map]').getAttribute('viewBox'),frame);
   await page.locator('[data-west-water-pick="rainfall"]').click();await ready();await pointer('[data-natural-feature^="rainfall:"]');assert.deepEqual(await layerCounts(),counts);await page.waitForFunction(()=>document.querySelector('[data-west-natural-value]')?.textContent.includes('GPCC v2025'));
   await page.locator('[data-west-topic-button="annual-precipitation"]').click();await ready();assert.equal(await page.locator('[data-west-raster]').count(),0);assert.equal(await page.locator('[data-west-band="rainfall"]').count(),107);await pointer('[data-natural-feature^="rainfall:"]');await page.waitForFunction(()=>document.querySelector('[data-west-natural-value]')?.textContent.includes('GPCC v2025'));assert((await page.locator('[data-west-natural-selection]').innerText()).includes('同じ広域の平滑化格子'));await shot('rainfall-250');
   await page.locator('[data-west-map]').focus();await page.keyboard.press('+');assert.notEqual(await page.locator('[data-west-map]').getAttribute('viewBox'),frame);await page.keyboard.press('Home');assert.equal(await page.locator('[data-west-map]').getAttribute('viewBox'),frame);
   await open('?topic=annual-precipitation&at=55,15');await page.waitForFunction(()=>document.querySelector('[data-west-natural-value]')?.textContent.includes('未収録'));assert(!(await page.locator('[data-west-natural-value]').innerText()).includes('：0'));
   await page.locator('[data-west-standard-group="標高（等高線）"]').click();await ready();assert.equal(await page.locator('[data-west-raster]').count(),0);assert.equal(await page.locator('[data-west-band="elevation"]').count(),1198);assert.equal(await page.locator('[data-west-aligned-line="elevation"]').count(),1155);assert((await page.locator('[data-west-legend]').innerText()).includes('-500'));await pointer('[data-natural-feature^="elevation:"]');await page.waitForFunction(()=>document.querySelector('[data-west-natural-value]')?.textContent.includes('ETOPO 2022'));await shot('elevation-500');
   await page.locator('[data-west-standard-group="地形"]').click();await ready();assert.equal(await page.locator('[data-west-band]').count(),0);assert.equal(await page.locator('[data-west-raster]').count(),0);assert.equal(await page.locator('[data-west-aligned-line="elevation"]').count(),1155);const line=page.locator('[data-natural-feature="line:500"][tabindex="0"]');await line.press('Enter');await ready();assert((await page.locator('[data-west-natural-selection]').innerText()).includes('500mの等高線'));await shot('terrain-outline');
   await context.close();
  }
  assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);await writeFile(path.join(output,'results.json'),JSON.stringify({passed:true,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),browser:browser.version(),chromiumSandbox:true,records,errors,failures},null,2)+'\n');
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
});
