import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Window} from 'happy-dom';
import {bundleCanadaSource} from '../fixtures/bundle-canada-source.mjs';
const html=await readFile('dist/atlas/north-america/canada/industry/index.html','utf8'),code=await bundleCanadaSource('src/scripts/atlas-canada-industry.ts',{globalName:'IndustryPilot'});
async function open(search=''){const w=new Window({url:'https://example.com/insight-journal/atlas/north-america/canada/industry/'+search,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write(html.replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));w.eval(code+"\nIndustryPilot.initCanadaIndustry(document.querySelector('[data-canada-industry]'))");return w;}
test('Canada keeps the major-industry tab and exposes exactly the three learning categories plus three statistics columns',async()=>{const w=await open();try{const d=w.document;assert.deepEqual([...d.querySelectorAll('[data-ca-sector]')].map(b=>b.dataset.caSector),['resources','manufacturing','services']);assert.equal(d.querySelectorAll('[data-ca-province-shape]').length,13);assert.equal(d.querySelectorAll('.ca-pilot-stat-card').length,3);assert.equal(d.querySelectorAll('[data-ca-bars] li').length,12);assert.equal(d.querySelectorAll('[data-industry-year],[data-industry-compare],[data-industry-save]').length,0);assert.match(d.querySelector('[data-ca-reading]').textContent,/サドベリー.*ラブラドール/);assert.match(d.querySelector('[data-ca-why]').textContent,/地質.*精鉱/s);}finally{await w.happyDOM.close();}});
test('Selection, explicit-only, clear and category switching separate map state from unmodified statistical classes',async()=>{const w=await open();try{const q=s=>w.document.querySelector(s);q('[data-ca-subtabs=resources] [data-ca-subsector=refining]').click();assert.equal(q('[data-ca-title]').textContent,'石油精製');assert.equal(q('[data-ca-only]').checked,false);assert.equal(q('[data-ca-stat-gdp]').textContent,'13,256.5');assert.equal(q('[data-ca-stat-employment]').textContent,'未取得');q('[data-ca-only]').checked=true;q('[data-ca-only]').dispatchEvent(new w.Event('change'));assert.equal(new URL(w.location.href).searchParams.get('only'),'1');q('[data-ca-clear]').click();assert.equal(q('[data-ca-title]').textContent,'資源・エネルギー');assert.equal(new URL(w.location.href).searchParams.has('only'),false);q('[data-ca-sector=manufacturing]').click();assert.equal(q('[data-ca-title]').textContent,'製造業');assert.equal(q('[data-ca-international]').hidden,true);q('[data-ca-sector=services]').click();assert.equal(q('[data-ca-port-statistics]').hidden,false);}finally{await w.happyDOM.close();}});
test('Overlap uses the same documented processor in both categories and preserves the camera',async()=>{const w=await open('?sector=resources&subsector=nickel&site=sudbury&industryFrame=50,220,940,510');try{const q=s=>w.document.querySelector(s),frame=q('[data-ca-map]').getAttribute('viewBox');assert.equal(q('[data-ca-overlap]').hidden,false);q('[data-ca-overlap]').click();assert.equal(q('[data-ca-title]').textContent,'ニッケル精錬');assert.equal(new URL(w.location.href).searchParams.get('site'),'sudbury');assert.equal(q('[data-ca-map]').getAttribute('viewBox'),frame);assert.match(q('[data-ca-stat-note]').textContent,/ニッケル・アルミだけの値ではありません/);w.history.replaceState(null,'','?sector=services&subsector=digital');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.match(q('[data-ca-stat-scope]').textContent,/一致統計は未収録/);}finally{await w.happyDOM.close();}});
test('The CER crude case keeps its verified 2024 quantities and export denominator, and the focus remains in this page',async()=>{const w=await open();try{const q=s=>w.document.querySelector(s);assert.equal(q('[data-ca-international]').hidden,false);for(const [id,value]of [['exports','420'],['us-share','93'],['alberta-share','91']])assert(q(`[data-ca-international-indicator=${id}]`).textContent.includes(value));assert.match(q('[data-ca-international]').textContent,/2024年.*分母：カナダの原油輸出量/s);q('[data-ca-international-place]').click();assert.equal(new URL(w.location.href).searchParams.get('site'),'athabasca');assert.equal(q('[data-ca-title]').textContent,'石油・天然ガス');assert.equal(q('[data-ca-international]').hidden,false);}finally{await w.happyDOM.close();}});
test('Legacy year/province handoffs remain statistical context with no invented location or 2025 value',async()=>{const w=await open('?metric=mining&year=2025&province=Alberta');try{const q=s=>w.document.querySelector(s);assert.equal(q('[data-ca-title]').textContent,'資源・エネルギー');assert.match(q('[data-ca-value]').textContent,/アルバータ.*2021年/);assert.equal(q('[data-ca-site-reading]').hidden,true);}finally{await w.happyDOM.close();}});
