import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
import {transform} from 'esbuild';
import {Window} from 'happy-dom';
const lib=await readFile('src/lib/atlas-canada-beef.ts','utf8'),controller=(await readFile('src/scripts/atlas-canada-beef.ts','utf8')).replace(/^import .*;\r?\n/,'');
const code=(await transform(`${lib}\n${controller}\ninitCanadaBeef(document.querySelector('[data-canada-beef]'));`,{loader:'ts',format:'iife'})).code;
async function page(search='',interactive=false,patch){const w=new Window({url:`https://example.com/insight-journal/atlas/north-america/canada/agriculture/beef/${search}`,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:interactive,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write((await readFile('dist/atlas/north-america/canada/agriculture/beef/index.html','utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));if(patch){const el=w.document.querySelector('[data-beef-config]'),config=JSON.parse(el.textContent);patch(config);el.textContent=JSON.stringify(config);}if(interactive)w.eval(code);return w;}
test('Beef initial HTML has truthful SSR bars, 99 values, 3 dated maps, classification, causal prose and full sources without JS',async()=>{
 const w=await page();try{const d=w.document;assert.equal(d.querySelectorAll('[data-beef-row]').length,33);assert.equal(d.querySelectorAll('[data-beef-row]:not([hidden])').length,11);assert.equal(d.querySelectorAll('[data-beef-cell]').length,99);assert.equal(d.querySelectorAll('[data-beef-map-panel]').length,3);assert.equal(d.querySelectorAll('[data-beef-map-panel]:not([hidden])').length,1);assert.equal(d.querySelector('[data-beef-row="Alberta"][data-year="2021"] [data-beef-bar]').style.width,'100%');const national=d.querySelector('[data-beef-row="Canada"][data-year="2021"]');assert.match(national.textContent,/3,776.3.*980.3.*12,645.0/s);assert.match(d.querySelector('[data-beef-map-panel=beef]').textContent,/2,500.*3,776,389.*肉牛すべて.*農場・肥育場/s);assert.match(d.querySelector('#beef-definitions').textContent,/18,559,652.*Total hay.*乾草だけ/s);assert.match(d.querySelector('#canada-beef-sources').textContent,/July 1, 2021, 2025 and 2026.*endorsement.*2026年8月24日.*Open Licence/s);assert.ok(d.querySelector('noscript').textContent.includes('原寸画像'));assert.ok(d.querySelector('[data-news-rail]'));
 for(const a of d.querySelectorAll('a')){const u=new URL(a.href);if(u.origin==='https://example.com'&&u.pathname.startsWith('/insight-journal/'))await access(`dist/${u.pathname.replace('/insight-journal/','')}${u.pathname.endsWith('/')?'index.html':''}`);}
 for(const crop of ['','wheat/'])assert.ok((await readFile(`dist/atlas/north-america/canada/agriculture/${crop}index.html`,'utf8')).includes('/canada/agriculture/beef/'));assert.ok((await readFile('dist/sitemap.xml','utf8')).includes('/canada/agriculture/beef/'));
 }finally{await w.happyDOM.close();}
});
test('Beef all 11 geographies and 3 years × 3 classes display the real data and do not change fixed maps',async()=>{
 const config=JSON.parse(await readFile('src/data/atlas/canada/beef.json','utf8')),w=await page('',true);try{const d=w.document,q=s=>d.querySelector(s),change=(s,v)=>{q(s).value=String(v);q(s).dispatchEvent(new w.Event('change'));};
 for(const map of ['beef','pasture','hay']){change('[data-beef-map]',map);assert.equal(d.querySelectorAll('[data-beef-map-panel]:not([hidden])').length,1);assert.equal(q('[data-beef-map-panel]:not([hidden])').dataset.beefMapPanel,map);const src=q(`[data-beef-map-panel=${map}] img`).src;
  for(const year of config.years)for(const m of config.metrics){change('[data-beef-year]',year);change('[data-beef-metric]',m.id);assert.equal(q(`[data-beef-map-panel=${map}] img`).src,src);assert.equal(d.querySelectorAll('[data-beef-row]:not([hidden])').length,11);for(const p of config.provinces){change('[data-beef-province]',p.id);const r=config.data.find(r=>r.year===year&&r.id===p.id),v=r.values[m.id].value;assert.ok(q('[data-beef-comparison]').textContent.includes(`${p.name}: ${v.toLocaleString('ja-JP',{minimumFractionDigits:1,maximumFractionDigits:1})} 千頭`));assert.match(q('[data-beef-comparison]').textContent,/7月1日/);}}
 }
 change('[data-beef-province]','Alberta');change('[data-beef-compare]','Saskatchewan');assert.ok(q('[data-beef-comparison]').textContent.includes(' ／ '));
 }finally{await w.happyDOM.close();}
});
test('Beef reload and history preserve map/year/class/compare/zoom, return resets zoom and equal comparisons clear',async()=>{
 const w=await page('?year=2026&province=Ontario&compare=Quebec&metric=dairy&map=hay&zoom=1',true);try{const d=w.document,q=s=>d.querySelector(s);assert.equal(q('[data-beef-year]').value,'2026');assert.equal(q('[data-beef-compare]').value,'Quebec');assert.equal(q('[data-beef-map-panel]:not([hidden])').dataset.beefMapPanel,'hay');assert.ok(q('[data-beef-map-panel=hay] [data-beef-map-scroll]').classList.contains('is-zoomed'));q('[data-beef-map-reset]').click();assert.ok(!q('[data-beef-map-panel=hay] [data-beef-map-scroll]').classList.contains('is-zoomed'));assert.equal(q('[data-beef-map]').value,'hay');q('[data-beef-province]').value='Quebec';q('[data-beef-province]').dispatchEvent(new w.Event('change'));assert.equal(q('[data-beef-compare]').value,'');w.history.replaceState(null,'','?year=2025&province=Manitoba&compare=Canada&metric=total&map=pasture&zoom=1');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(q('[data-beef-year]').value,'2025');assert.equal(q('[data-beef-map]').value,'pasture');assert.equal(q('[data-beef-compare]').value,'Canada');assert.equal(q('[data-beef-metric]').value,'total');q('[data-beef-province-button=Alberta]').click();assert.equal(new URL(w.location).searchParams.get('province'),'Alberta');assert.equal(new URL(w.location).searchParams.get('map'),'pasture');}finally{await w.happyDOM.close();}
});
test('Clearly synthetic missing/zero/revised fixtures exercise cattle display without claiming missingness in the real slice',async()=>{
 const w=await page('?province=Alberta&compare=Manitoba',true,config=>{const a=config.data.find(r=>r.year===2021&&r.id==='Alberta');a.values.beef={...a.values.beef,value:null,status:'F'};const m=config.data.find(r=>r.year===2021&&r.id==='Manitoba');m.values.beef={...m.values.beef,value:0,symbol:'r'};});try{const d=w.document;assert.match(d.querySelector('[data-beef-comparison]').textContent,/未収録.*F.*0.0 千頭.*r/);const a=d.querySelector('[data-beef-row="Alberta"][data-year="2021"] [data-beef-bar]'),m=d.querySelector('[data-beef-row="Manitoba"][data-year="2021"] [data-beef-bar]');assert.equal(a.style.width,'0%');assert.ok(a.parentElement.classList.contains('is-missing'));assert.equal(m.style.width,'0%');assert.ok(!m.parentElement.classList.contains('is-missing'));}finally{await w.happyDOM.close();}
});
