import test from 'node:test';import assert from 'node:assert/strict';import {readFile,access} from 'node:fs/promises';import {build,transform} from 'esbuild';import {Window} from 'happy-dom';
const folder='atlas/north-america/canada',config=JSON.parse(await readFile('src/data/atlas/canada/forestry.json','utf8'));
async function compile(name,call){return (await build({stdin:{contents:`import {initCanada${name==='nature'?'Nature':'Forestry'}} from './src/scripts/atlas-canada-${name}';${call}`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,format:'iife'})).outputFiles[0].text;}
const code=await compile('forestry',"initCanadaForestry(document.querySelector('[data-canada-forestry]'));"),natureCode=await compile('nature',"initCanadaNature(document.querySelector('[data-canada-nature]'));");
async function page(search='',interactive=false,patch){const w=new Window({url:`https://example.com/insight-journal/${folder}/agriculture/forestry/${search}`,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:interactive,suppressInsecureJavaScriptEnvironmentWarning:true}});w.document.write((await readFile(`dist/${folder}/agriculture/forestry/index.html`,'utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));if(patch){const el=w.document.querySelector('[data-forestry-config]'),cfg=JSON.parse(el.textContent);patch(cfg);el.textContent=JSON.stringify(cfg);}if(interactive)w.eval(code);return w;}
test('Forestry SSR has honest bars, confidential cells, all sources, dated distributions and accessible no-JS reading',async()=>{
 const w=await page();try{const d=w.document;assert.equal(d.querySelectorAll('[data-forestry-cell]').length,66);assert.equal(d.querySelectorAll('[data-forestry-row]:not([hidden])').length,11);assert.equal(d.querySelectorAll('[data-forestry-region-reading]').length,3);assert.match(d.querySelector('[data-forestry-row="Manitoba"][data-year="2024"]').textContent,/秘匿 x/);const secret=d.querySelector('[data-forestry-row="Prince Edward Island"][data-year="2021"] [data-forestry-bar]');assert.equal(secret.style.width,'0%');assert.ok(secret.parentElement.classList.contains('is-missing'));const visible=d.querySelector('[data-forestry-row="British Columbia"][data-year="2024"] [data-forestry-bar]');assert.ok(parseFloat(visible.style.width)>90&&parseFloat(visible.style.width)<100);assert.equal(d.querySelector('[data-forestry-row="Quebec"][data-year="2024"] [data-forestry-bar]').style.width,'100%');assert.equal([...d.querySelectorAll('[data-forestry-cover-layer]')].filter(el=>el.style.display!=='none').length,1);assert.match(d.querySelector('#forestry-definitions').textContent,/森林被覆.*森林土地面積.*蓄積.*伐採量.*製造品収入/s);assert.match(d.querySelector('#canada-forestry-sources').textContent,/2020.*30m.*86.9%.*2026年9月30日.*2025年12月18日.*Open Licence/s);assert.ok(d.querySelector('#canada-forestry-sources').textContent.includes('This does not constitute an endorsement'));assert.ok(d.querySelector('noscript').textContent.includes('2024年加工業表'));assert.match(d.body.textContent,/2023年の過去例.*2026年現在/s);assert.ok(d.querySelector('[data-news-rail]'));
 for(const a of d.querySelectorAll('a')){const u=new URL(a.href);if(u.origin==='https://example.com'&&u.pathname.startsWith('/insight-journal/'))await access(`dist/${u.pathname.replace('/insight-journal/','')}${u.pathname.endsWith('/')?'index.html':''}`);}for(const path of ['agriculture/','agriculture/wheat/','agriculture/beef/'])assert.ok((await readFile(`dist/${folder}/${path}index.html`,'utf8')).includes('/canada/agriculture/forestry/'));assert.ok((await readFile('dist/sitemap.xml','utf8')).includes('/canada/agriculture/forestry/'));
 }finally{await w.happyDOM.close();}
});
test('Forestry actual 3 years × 2 industries × 11 geographies retain values, quality and real suppressed bars',async()=>{
 const w=await page('',true);try{const d=w.document,q=s=>d.querySelector(s),change=(s,v)=>{q(s).value=String(v);q(s).dispatchEvent(new w.Event('change'));};
 for(const year of config.years)for(const metric of config.metrics){change('[data-forestry-year]',year);change('[data-forestry-metric]',metric.id);assert.equal(d.querySelectorAll('[data-forestry-row]:not([hidden])').length,11);for(const p of config.provinces){change('[data-forestry-province]',p.id);const r=config.data.find(r=>r.year===year&&r.id===p.id),v=r.values[metric.id],label=q('[data-forestry-comparison]').textContent;assert.ok(label.includes(p.name));assert.ok(label.includes(v.value===null?'秘匿':v.value.toLocaleString('ja-JP')));assert.ok(label.includes(v.status));if(p.id!=='Canada'){const bar=q(`[data-forestry-row="${p.id}"][data-year="${year}"] [data-forestry-bar]`);assert.equal(bar.parentElement.classList.contains('is-missing'),v.value===null);if(v.value===null)assert.equal(bar.style.width,'0%');}}assert.equal(q('[data-forestry-cover-layer=all]').getAttribute('href').endsWith('2020.png'),true);}
 change('[data-forestry-province]','British Columbia');change('[data-forestry-compare]','Quebec');assert.match(q('[data-forestry-comparison]').textContent,/ブリティッシュコロンビア.*ケベック/s);change('[data-forestry-province]','Quebec');assert.equal(q('[data-forestry-compare]').value,'');
 }finally{await w.happyDOM.close();}
});
test('Forest categories retain context while highlighting and recover, region selection is keyboard accessible and state survives reload/history',async()=>{
 const w=await page('?year=2021&province=Quebec&compare=Ontario&metric=paper&cover=mixed&region=quebec&zoom=1',true);try{const d=w.document,q=s=>d.querySelector(s),change=(s,v)=>{q(s).value=v;q(s).dispatchEvent(new w.Event('change'));};assert.equal(q('[data-forestry-year]').value,'2021');assert.equal(q('[data-forestry-metric]').value,'paper');assert.equal(q('[data-forestry-compare]').value,'Ontario');assert.equal(q('[data-forestry-focus]').getAttribute('aria-pressed'),'true');
 for(const cover of ['needleleaf','taiga','broadleaf','mixed','all']){change('[data-forestry-cover]',cover);const visible=[...d.querySelectorAll('[data-forestry-cover-layer]')].filter(el=>el.style.display!=='none');assert.equal(visible.length,cover==='all'?1:2);assert.equal(visible[0].dataset.forestryCoverLayer,'all');assert.equal(visible.at(-1).dataset.forestryCoverLayer,cover);assert.equal(Number(visible[0].style.opacity),cover==='all'?1:.3);assert.equal(new URL(w.location).searchParams.get('cover'),cover);}
 q('[data-forestry-region-marker=bc]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(q('[data-forestry-region]').value,'bc');assert.equal(q('[data-forestry-province]').value,'British Columbia');assert.equal(d.querySelectorAll('[data-forestry-region-reading]:not([hidden])').length,1);change('[data-forestry-cover]','taiga');q('[data-forestry-map-reset]').click();assert.equal(q('[data-forestry-cover]').value,'all');assert.equal(q('[data-forestry-map]').getAttribute('viewBox'),'0 0 900 580');assert.equal(q('[data-forestry-year]').value,'2021');
 w.history.replaceState(null,'','?year=2023&province=Ontario&compare=Canada&metric=wood&cover=broadleaf&region=ontario&zoom=1');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(q('[data-forestry-year]').value,'2023');assert.equal(q('[data-forestry-region]').value,'ontario');assert.equal(q('[data-forestry-cover]').value,'broadleaf');assert.equal(q('[data-forestry-compare]').value,'Canada');assert.notEqual(q('[data-forestry-map]').getAttribute('viewBox'),'0 0 900 580');
 }finally{await w.happyDOM.close();}
});
test('Nature comparisons explain their targets and return to local forestry choices without replacing capital default',async()=>{
 const w=await page('?year=2023&province=Quebec&compare=Ontario&metric=paper&cover=taiga&region=quebec&forestCamera=430,-20,1.4',true);let nw;try{const link=w.document.querySelector('[data-forestry-nature-link*="view=water"]'),url=new URL(link.href);assert.equal(url.searchParams.get('city'),'vancouver');assert.equal(url.searchParams.get('water'),'Fraser');assert.equal(url.searchParams.get('only'),'1');assert.ok(link.textContent.includes('海へのつながり'));nw=new Window({url:url.href,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});nw.document.write((await readFile(`dist/${folder}/nature/index.html`,'utf8')).replace(/<script(?![^>]*type="application\/json")[^>]*>[\s\S]*?<\/script>/g,''));nw.eval(natureCode);const back=nw.document.querySelector('[data-canada-forestry-return]');assert.equal(back.hidden,false);const returned=new URL(back.href);assert.equal(returned.origin,url.origin);assert.equal(returned.pathname,`/insight-journal/${folder}/agriculture/forestry/`);assert.equal(returned.searchParams.get('metric'),'paper');assert.equal(returned.searchParams.get('cover'),'taiga');assert.equal(returned.searchParams.get('year'),'2023');assert.equal(returned.searchParams.get('forestCamera'),'430,-20,1.4');assert.equal(nw.document.querySelector('[data-canada-city]').value,'vancouver');nw.document.querySelector('[data-canada-view=climate]').click();assert.equal(new URL(back.href).searchParams.get('cover'),'taiga');const capital=new URL(w.document.querySelector('[data-forestry-nature-link]:last-of-type')?.href??url);const a=[...w.document.querySelectorAll('[data-forestry-nature-link]')].find(a=>a.textContent.includes('首都Ottawa'));assert.equal(new URL(a.href).searchParams.has('city'),false);
 }finally{await w.happyDOM.close();if(nw)await nw.happyDOM.close();}
});
test('Clearly synthetic zero, missing F and revision flags remain distinct in the forestry controller',async()=>{
 const w=await page('?province=British+Columbia&compare=Ontario',true,cfg=>{cfg.data.find(r=>r.year===2024&&r.id==='British Columbia').values.wood={value:0,status:'A',symbol:'r'};cfg.data.find(r=>r.year===2024&&r.id==='Ontario').values.wood={value:null,status:'F',symbol:''};});try{const d=w.document,b=d.querySelector('[data-forestry-row="British Columbia"][data-year="2024"] [data-forestry-bar]'),o=d.querySelector('[data-forestry-row="Ontario"][data-year="2024"] [data-forestry-bar]');assert.equal(b.style.width,'0%');assert.equal(o.style.width,'0%');assert.equal(b.parentElement.classList.contains('is-missing'),false);assert.equal(o.parentElement.classList.contains('is-missing'),true);assert.match(d.querySelector('[data-forestry-comparison]').textContent,/0 千CAD.*r.*欠測.*F/s);}finally{await w.happyDOM.close();}
});
