"""Reuse North America's 30-class display palette without changing climate IDs.

Run directly to recolor the shipped v2 grids offline. The original v1 legend
remains a record of the publisher's colors, independent of display styling.
"""
import ast
import gzip
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public/assets/atlas/asia-climate-v2'
REFERENCE = ROOT / 'scripts/refine-atlas-nature.py'
LEGEND = ROOT / 'public/assets/atlas/nature-v1/climate-legend.json'
digest = lambda raw: hashlib.sha256(raw).hexdigest()


def write(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, separators=(',', ':')) + '\n', encoding='utf8', newline='\n')


def display_classes():
    # Read only literal assignments; never execute the North America generator.
    function = next(n for n in ast.parse(REFERENCE.read_text(encoding='utf8')).body if isinstance(n, ast.FunctionDef) and n.name == 'climate')
    literals = {}
    for node in function.body:
        if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name) and node.targets[0].id in ('codes', 'palette'):
            call = node.value
            assert isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute) and call.func.attr == 'split' and not call.args
            literals[node.targets[0].id] = ast.literal_eval(call.func.value).split()
    assert len(literals['codes']) == len(literals['palette']) == 30
    colors = dict(zip(literals['codes'], ['#' + color for color in literals['palette']]))
    for item in json.loads(LEGEND.read_text(encoding='utf8')):
        assert colors[item['code']] == item['color']
    classes = json.loads((ROOT / 'public/assets/atlas/asia-climate-v1/legend.json').read_text(encoding='utf8'))
    return [{**item, 'color': colors[item['code']]} for item in classes]


def palette_record():
    return {'reference': REFERENCE.relative_to(ROOT).as_posix(), 'referenceSha256': digest(REFERENCE.read_bytes()),
            'legend': LEGEND.relative_to(ROOT).as_posix(), 'legendSha256': digest(LEGEND.read_bytes()),
            'script': Path(__file__).relative_to(ROOT).as_posix(), 'scriptSha256': digest(Path(__file__).read_bytes()),
            'method': 'All 30 codes use the North America climate() palette. RGBA colors only; class IDs, masks and grids are unchanged.'}


def write_definitions(classes):
    path = ROOT / 'src/data/atlas/asia-climate-definitions.ts'
    header = path.read_text(encoding='utf8').split('export const asiaClimateClasses:')[0]
    header = header.replace('// Generated by scripts/atlas-asia-climate.py from the pinned source legend.', '// Generated by scripts/atlas_asia_climate_palette.py; source labels and North America display colors.')
    path.write_text(header + 'export const asiaClimateClasses: readonly AsiaClimateClass[] = ' + json.dumps(classes, ensure_ascii=False, indent=2) + ';\n', encoding='utf8', newline='\n')


def recolor():
    classes = display_classes()
    manifest = json.loads((OUT / 'manifest.json').read_text(encoding='utf8'))
    colors = np.zeros((31, 4), dtype=np.uint8)
    for item in classes:
        colors[item['id']] = [*bytes.fromhex(item['color'][1:]), 255]
    for region, record in manifest['regions'].items():
        raw = (OUT / record['grid']).read_bytes()
        assert digest(raw) == manifest['files'][record['grid']]['sha256']
        values = np.frombuffer(gzip.decompress(raw), dtype=np.uint8).reshape(record['height'], record['width'])
        assert values.max() <= 30
        Image.fromarray(colors[values]).save(OUT / record['image'], optimize=True)
        assert np.array_equal(np.asarray(Image.open(OUT / record['image'])), colors[values])
        print(region, 'verified all pixels; classification grid unchanged', flush=True)
    write(OUT / 'legend.json', classes)
    write_definitions(classes)
    manifest['version'] = '2.1.0'
    manifest['processing']['displayPalette'] = palette_record()
    manifest['processing']['scriptSha256'] = digest((ROOT / manifest['processing']['script']).read_bytes())
    manifest['files'] = {name: {'bytes': (OUT / name).stat().st_size, 'sha256': digest((OUT / name).read_bytes())} for name in manifest['files']}
    write(OUT / 'manifest.json', manifest)


if __name__ == '__main__':
    recolor()
