"""Reproduce MY2024/25 balances from the archived WASDE-675 text, no network.

USDA's table columns and units are retained. A different release must be
reviewed before changing this extractor's pinned column and section bounds.
"""
from pathlib import Path
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
raw = (ROOT / 'scripts/data/wasde0926.txt').read_bytes()
text = raw.decode('utf-8').replace('\r\n', '\n')
assert 'WASDE - 675' in text and '2024/25' in text

def section(start, end):
    return text.split(start, 1)[1].split(end, 1)[0]

def value(block, label):
    rows = re.findall(r'^\s*' + re.escape(label) + r'\s+(-?\d+(?:\.\d+)?)\s+', block, re.M)
    assert len(rows) == 1, (label, rows)
    return float(rows[0])

blocks = {
    'corn': section('\nCORN\n', 'WASDE - 675 - 13'),
    'soybean': section('\nSOYBEANS\n', '\nSOYBEAN OIL\n'),
    'wheat': section('U.S. Wheat Supply and Use  1/', 'U.S. Wheat by Class'),
    'cotton': section('U.S. Cotton Supply and Use  1/', 'WASDE - 675 - 18'),
    'rice': section('\nTOTAL RICE\n', '\nLONG GRAIN RICE\n'),
}

def extract(crop, digits, page, uses):
    block = blocks[crop]
    fields = {key: value(block, label) for key, label in {
        'beginningStocks': 'Beginning Stocks 2/' if crop == 'rice' else 'Beginning Stocks',
        'production': 'Production', 'imports': 'Imports', 'totalSupply': 'Supply, Total',
        'exports': 'Exports, Total  4/' if crop == 'rice' else 'Exports, Total' if crop == 'cotton' else 'Exports',
        'endingStocks': 'Ending Stocks',
    }.items()}
    domestic = {key: value(block, label) for key, label in uses.items()}
    if crop == 'corn':
        fsi = value(block, 'Food,Seed& Industrial 2/')
        domestic['other-fsi'] = fsi - domestic['ethanol']
        assert sum(domestic.values()) == value(block, 'Domestic, Total')
        fields['fsiParent'] = fsi
    if crop == 'wheat':
        assert sum(domestic.values()) == value(block, 'Domestic, Total')
    adjustment = value(block, 'Unaccounted 2/') if crop == 'cotton' else 0
    # Bounds follow the sum of half of each published rounding unit.
    tolerance = (len(domestic) + 5) * .5 * 10 ** -digits
    supply_error = fields['totalSupply'] - sum(fields[k] for k in ['beginningStocks','production','imports'])
    use_error = fields['totalSupply'] - (sum(domestic.values()) + fields['exports'] + fields['endingStocks'] + adjustment)
    assert abs(supply_error) < tolerance and abs(use_error) < tolerance, crop
    assert all(v >= 0 for v in [*fields.values(), *domestic.values()])
    return {**fields, 'domestic': domestic, 'adjustment': adjustment, 'decimals': digits,
            'page': page, 'column': '2024/25', 'status': 'actual', 'coverage': 'complete',
            'roundingTolerance': tolerance, 'supplyError': round(supply_error, 8), 'useError': round(use_error, 8)}

data = {
    'source': {'publisher': 'USDA', 'report': 'WASDE-675', 'publishedAt': '2026-09-11',
               'retrievedAt': '2026-09-13', 'sha256': hashlib.sha256(raw).hexdigest(),
               'url': 'https://www.usda.gov/oce/commodity/wasde/wasde0926.pdf',
               'rawUrl': 'https://esmis.nal.usda.gov/sites/default/release-files/796054/wasde0926.txt',
               'extractor': 'prepare-atlas-supply-use.py v1'},
    'crops': {
        'corn': extract('corn', 0, 12, {'feed': 'Feed and Residual', 'ethanol': 'Ethanol & by-products 3/'}),
        'soybean': extract('soybean', 0, 15, {'crush': 'Crushings', 'seed': 'Seed', 'residual': 'Residual'}),
        'wheat': extract('wheat', 0, 11, {'food': 'Food', 'seed': 'Seed', 'feed': 'Feed and Residual'}),
        'cotton': extract('cotton', 2, 17, {'mill': 'Domestic Use'}),
        'rice': extract('rice', 1, 14, {'domestic': 'Domestic & Residual  3/'}),
    }
}
out = ROOT / 'src/data/atlas/supply-use-generated.ts'
out.write_text('// Generated by scripts/prepare-atlas-supply-use.py; do not edit values.\nexport const supplyUseGenerated = ' + json.dumps(data, ensure_ascii=False, indent=2) + ' as const;\n')
print('Verified and generated 5 crop balances:', data['source']['sha256'])
