"""Build exact named Canada landforms from pinned official NRCan vectors.

Requires shapely 2.1.2 for validation. This preparation script never downloads
data. The seven existing official Regions are retained, and the separately
published Divisions feature named exactly "Rocky Mountains" is added. It does
not substitute Cordillera or Rocky Mountain Area for the Rocky Mountains.

Run from any directory:
  python scripts/prepare-canada-named-landforms.py
  python scripts/prepare-canada-named-landforms.py --check

Raw responses remain in the paths recorded in the generated manifest. To
reacquire them, use the exact query URLs in that manifest, with no generalized
geometry, clipping, geometry precision or coordinate rounding parameters.
"""
from pathlib import Path
import argparse
import hashlib
import json
import math
import sys

import shapely
from shapely.geometry import Point, shape
from shapely.validation import explain_validity


SERVICE = 'https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/phys_reg_en/MapServer'
CATALOGUE_ID = 'a3dfbaf4-1b20-4061-aa0a-e7a79953f52d'
REGIONS_QUERY = SERVICE + '/0/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson'
ROCKIES_QUERY = SERVICE + '/2/query?where=OBJECTID_12%3D78&outFields=*&returnGeometry=true&outSR=4326&f=geojson'
OUTPUT = 'public/assets/atlas/canada-landforms-v2'

# Existing UI IDs are stable; source names must match their official layer.
DEFINITIONS = [
    ('cordillera', 'Cordillera', '西部山地（コルディレラ）', [-126, 58]),
    ('interior-plains', 'Interior Plains', '内陸平原', [-110, 57]),
    ('canadian-shield', 'Canadian Shield', 'カナダ盾状地', [-93, 54]),
    ('great-lakes-st-lawrence-lowlands', 'Great Lakes - St. Lawrence Lowlands', '五大湖・セントローレンス低地', [-80.4, 43.4]),
    ('appalachian-uplands', 'Appalachian Uplands', 'アパラチア高地', [-66.5, 46.5]),
    ('hudson-bay-lowland', 'Hudson Bay Lowland', 'ハドソン湾低地', [-84.5, 53.5]),
    ('arctic-lands', 'Arctic Lands', '北極地域', [-110, 75]),
]
ROCKIES_DEFINITION = ('rockies', 'Rocky Mountains', 'ロッキー山脈', [-117.5, 52.5])

# Only acquisition snapshots are pinned. Generated bytes are checked by --check.
SOURCES = [
    {
        'file': 'public/assets/atlas/canada-physiography-v1/regions.geojson',
        'url': REGIONS_QUERY,
        'sha256': '26b0d3cde98e66167a2fa122cf73c2d098b5c8f24c225610df145e8c98004866',
        'retrievedAt': '2026-10-02',
        'layer': 0,
        'level': 'region',
        'sourceScaleRange': {'minScale': 50000000, 'maxScale': 15000001},
        'contentType': 'application/geo+json;charset=UTF-8',
    },
    {
        'file': OUTPUT + '/source/rocky-mountains.geojson',
        'url': ROCKIES_QUERY,
        'sha256': 'a59769d34f61f788f4bd8fed428e3dd7f0be08de225dfe4a83c5e06ea6fd5d31',
        'retrievedAt': '2026-10-05',
        'layer': 2,
        'level': 'division',
        'sourceScaleRange': {'minScale': 8000000, 'maxScale': 0},
        'contentType': 'application/geo+json;charset=UTF-8',
    },
]
EVIDENCE = [
    {
        'file': 'data-source/atlas/canada-physiography-v1/source-catalogue.json',
        'url': 'https://open.canada.ca/data/api/action/package_show?id=' + CATALOGUE_ID,
        'sha256': '4e4dc7c0bc74893827779a4987fd26932dbe07b8939a42b1dacc6a3a9a9b99d7',
        'role': 'Official catalogue, licence and related Regions/Subregions/Divisions description',
    },
    {
        'file': 'data-source/atlas/canada-physiography-v1/source-license.html',
        'url': 'https://open.canada.ca/en/open-government-licence-canada',
        'sha256': 'd7648d6d694d66a0891502f85c3383f9263d5e541b47e14fbf33450974af158f',
        'role': 'Unmodified Open Government Licence - Canada response',
    },
    {
        'file': 'data-source/atlas/canada-physiography-v1/source-layer.json',
        'url': SERVICE + '/0?f=pjson',
        'sha256': 'b6e9470e8cd02dbbdd7e34d4e9ae83c7181b15182baf812709edb7e6c4d01c02',
        'role': 'Regions layer metadata',
    },
    {
        'file': OUTPUT + '/source/source-division-layer.json',
        'url': SERVICE + '/2?f=pjson',
        'sha256': '7f90de8eb4c0f06755f829cd26c93eb4a3ad0d2ccde23fd9ca51be9e8fb394c6',
        'role': 'Divisions layer metadata',
    },
    {
        'file': OUTPUT + '/source/source-subregion-layer.json',
        'url': SERVICE + '/1?f=pjson',
        'sha256': '4f0f5a6b868e7091ca6ec0e6fef0d25b303985ccb9cea551ca041c4acb683c6e',
        'role': 'Subregions layer metadata; not used as a substitute for individual mountain ranges',
    },
]


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def encode(obj, compact=False):
    opts = {'separators': (',', ':')} if compact else {'indent': 2}
    return (json.dumps(obj, ensure_ascii=False, allow_nan=False, **opts) + '\n').encode('utf-8')


def pinned(root, record):
    raw = (root / record['file']).read_bytes()
    if sha(raw) != record['sha256']:
        raise ValueError('Pinned official source SHA256 mismatch: ' + record['file'])
    return raw, {**record, 'bytes': len(raw)}


def rings(geometry):
    if geometry['type'] == 'Polygon':
        return geometry['coordinates']
    if geometry['type'] == 'MultiPolygon':
        return [ring for polygon in geometry['coordinates'] for ring in polygon]
    raise ValueError('Expected Polygon or MultiPolygon')


def validate_geometry(geometry, identifier, anchor):
    vertex_count = 0
    for ring in rings(geometry):
        if len(ring) < 4 or ring[0] != ring[-1]:
            raise ValueError('Open or degenerate ring: ' + identifier)
        for coordinate in ring:
            if len(coordinate) != 2 or not all(math.isfinite(n) for n in coordinate):
                raise ValueError('Non-finite or unexpected coordinates: ' + identifier)
            if not (-180 <= coordinate[0] <= 180 and -90 <= coordinate[1] <= 90):
                raise ValueError('Unexpected longitude/latitude: ' + identifier)
        vertex_count += len(ring)
    geom = shape(geometry)
    if geom.is_empty or not geom.is_valid:
        raise ValueError(identifier + ': ' + explain_validity(geom))
    if not geom.contains(Point(anchor)):
        raise ValueError('Label anchor outside exact feature: ' + identifier)
    return geom, {
        'validGeometry': True,
        'finiteCoordinates': True,
        'closedRings': True,
        'labelAnchorInsideGeometry': True,
        'polygonCount': 1 if geom.geom_type == 'Polygon' else len(geom.geoms),
        'ringCount': len(rings(geometry)),
        'vertexCount': vertex_count,
    }


def named_feature(source_feature, definition, layer):
    identifier, name, name_ja, anchor = definition
    original = source_feature['properties']
    join_field = 'RegionEn' if layer == 0 else 'Div_En'
    object_id_field = 'OBJECTID' if layer == 0 else 'OBJECTID_12'
    if original[join_field] != name:
        raise ValueError('Exact official feature name mismatch: ' + identifier)
    # The source geometry object passes through unchanged. Only properties and
    # the GeoJSON Feature ID are augmented to support stable UI selection.
    geometry = source_feature['geometry']
    geom, validation = validate_geometry(geometry, identifier, anchor)
    properties = {
        **original,
        'id': identifier,
        'name': name,
        'nameJa': name_ja,
        'sourceName': name,
        'sourceLevel': 'region' if layer == 0 else 'division',
        'sourceLayer': layer,
        'sourceObjectIds': [original[object_id_field]],
        'sourceRegion': original['RegionEn'],
        'labelAnchor': anchor,
    }
    if layer == 2:
        properties['sourceSubregion'] = original['SubRegionE']
        properties['sourceDivision'] = original['Div_En']
        properties['parentId'] = 'cordillera'
    feature = {'type': 'Feature', 'id': identifier, 'properties': properties, 'geometry': geometry}
    metadata = {
        'id': identifier,
        'name': name,
        'nameJapanese': name_ja,
        'sourceLevel': properties['sourceLevel'],
        'sourceLayer': layer,
        'sourceJoinField': join_field,
        'sourceObjectIds': properties['sourceObjectIds'],
        'sourceRegion': original['RegionEn'],
        'labelAnchor': anchor,
        'bounds': list(geom.bounds),
        'geometrySha256': sha(encode(geometry, compact=True)),
        'coordinatesUnchanged': geometry == source_feature['geometry'],
        'validation': validation,
    }
    if layer == 2:
        metadata.update({'sourceSubregion': original['SubRegionE'], 'sourceDivision': original['Div_En'], 'parentId': 'cordillera'})
    return feature, metadata, geom


def prepare(root):
    if shapely.__version__ != '2.1.2':
        raise ValueError('Validation requires the recorded shapely 2.1.2; found ' + shapely.__version__)
    raw_regions, region_source = pinned(root, SOURCES[0])
    raw_rockies, rockies_source = pinned(root, SOURCES[1])
    region_data = json.loads(raw_regions)
    rockies_data = json.loads(raw_rockies)
    if region_data['type'] != 'FeatureCollection' or len(region_data['features']) != 7:
        raise ValueError('Expected the seven original official Regions')
    if rockies_data['type'] != 'FeatureCollection' or len(rockies_data['features']) != 1:
        raise ValueError('Expected a single exact Rocky Mountains Division')
    rocky = rockies_data['features'][0]
    if rocky['properties'] != {
        'OBJECTID_12': 78, 'RegionEn': 'Cordillera',
        'SubRegionE': 'Rocky Mountain Area', 'Div_En': 'Rocky Mountains',
        'XLandform_1': 'Mountains',
    }:
        raise ValueError('Unexpected exact Rocky Mountains official attributes')
    features, metadata, geometries = [], [], {}
    region_names = [f['properties']['RegionEn'] for f in region_data['features']]
    if len(set(region_names)) != 7:
        raise ValueError('Duplicate official Regions')
    for definition in DEFINITIONS:
        original = next(f for f in region_data['features'] if f['properties']['RegionEn'] == definition[1])
        feature, record, geom = named_feature(original, definition, 0)
        features.append(feature)
        metadata.append(record)
        geometries[definition[0]] = geom
    feature, record, geom = named_feature(rocky, ROCKIES_DEFINITION, 2)
    features.append(feature)
    metadata.append(record)
    geometries['rockies'] = geom

    # Regions form a partition; Rocky Mountains is an intentional nested
    # selection within Cordillera. Every other positive-area overlap is an error.
    if not geometries['cordillera'].covers(geometries['rockies']):
        raise ValueError('Exact Rocky Mountains outline extends outside its official parent')
    if geometries['cordillera'].equals(geometries['rockies']):
        raise ValueError('Rocky Mountains must not be the Cordillera region outline')
    allowed_overlap = {'cordillera', 'rockies'}
    overlap_pairs = []
    for index, left in enumerate(features):
        for right in features[index + 1:]:
            left_id, right_id = left['id'], right['id']
            if geometries[left_id].intersection(geometries[right_id]).area > 0:
                if {left_id, right_id} != allowed_overlap:
                    raise ValueError('Unintended feature area overlap: ' + left_id + '/' + right_id)
                overlap_pairs.append([left_id, right_id])

    evidence = []
    for item in EVIDENCE:
        raw, record = pinned(root, item)
        if item['file'].endswith('source-catalogue.json'):
            catalogue = json.loads(raw)['result']
            if catalogue['license_id'] != 'ca-ogl-lgo' or catalogue['id'] != CATALOGUE_ID:
                raise ValueError('Unexpected catalogue or licence')
        if item['file'].endswith(('source-layer.json', 'source-division-layer.json', 'source-subregion-layer.json')):
            layer_metadata = json.loads(raw)
            if layer_metadata['geometryType'] != 'esriGeometryPolygon' or layer_metadata['extent']['spatialReference']['wkid'] != 3978:
                raise ValueError('Unexpected official polygon type or source CRS')
        evidence.append(record)

    collection = {'type': 'FeatureCollection', 'features': features}
    output_raw = encode(collection, compact=True)
    manifest = {
        'version': 2,
        'title': 'Named Canada landforms from official NRCan Regions and Divisions',
        'preparedAt': '2026-10-05',
        'source': {
            'catalogueId': CATALOGUE_ID,
            'publisher': 'Government of Canada; Natural Resources Canada',
            'title': 'Physiographic Regions of Canada',
            'catalogueUrl': 'https://open.canada.ca/data/en/dataset/' + CATALOGUE_ID,
            'descriptionUrl': 'https://atlas.gc.ca/phys/en/index.html',
            'published': '2019-04-01',
            'temporalCoverageStart': '2017-09-01',
            'catalogueModified': '2022-01-12',
            'licence': 'Open Government Licence - Canada 2.0',
            'licenceUrl': 'https://open.canada.ca/en/open-government-licence-canada',
            'attribution': 'Contains information licensed under the Open Government Licence – Canada.',
        },
        'geometry': {
            'filename': 'landforms.geojson',
            'sha256': sha(output_raw),
            'bytes': len(output_raw),
            'sourceCrs': 'EPSG:3978',
            'deliveryCrs': 'EPSG:4326',
            'featureJoinField': 'id',
            'featureCount': 8,
            'regionFeatureCount': 7,
            'divisionFeatureCount': 1,
            'polygonCount': sum(f['validation']['polygonCount'] for f in metadata),
            'ringCount': sum(f['validation']['ringCount'] for f in metadata),
            'vertexCount': sum(f['validation']['vertexCount'] for f in metadata),
            'originalCoordinatesPreserved': True,
            'simplificationApplied': False,
            'coordinateRoundingApplied': False,
            'clippingApplied': False,
            'unionApplied': False,
            'imageTracingApplied': False,
            'method': 'Select exact official layer-0 RegionEn names and exact layer-2 Div_En=Rocky Mountains, OBJECTID_12=78. Retain every source geometry coordinate unchanged; append stable UI IDs and explicit source hierarchy only.',
        },
        'validation': {
            'library': 'shapely 2.1.2',
            'validGeometries': 8,
            'finiteCoordinates': True,
            'closedRings': True,
            'labelAnchorsInsideExactGeometries': True,
            'unintendedPositiveAreaOverlapPairs': 0,
            'intentionalNestedOverlapPairs': overlap_pairs,
            'rockiesInsideCordillera': True,
            'rockiesDifferentFromCordillera': True,
            'rockiesExactOfficialDivisionObjectId': 78,
        },
        'features': metadata,
        'rawGeometrySnapshots': [region_source, rockies_source],
        'sourceEvidence': evidence,
        'reproduction': {
            'script': 'scripts/prepare-canada-named-landforms.py',
            'command': 'python scripts/prepare-canada-named-landforms.py',
            'verificationCommand': 'python scripts/prepare-canada-named-landforms.py --check',
            'dependencies': ['shapely==2.1.2'],
            'networkRequired': False,
        },
        'limitations': [
            'The seven existing national Regions remain broad named physiographic regions. They must not be relabelled as smaller ranges, grassland extent, elevation observations or administrative boundaries.',
            'Rockies uses the individual Rocky Mountains Division, not the broader Cordillera Region or Rocky Mountain Area Subregion; the separately named Rocky Mountain Foothills Division is excluded.',
            'The eight selections are hierarchical and do not form an eight-way partition. Rocky Mountains overlaps its parent Cordillera by design.',
            'Interior Plains includes northern plains as well as its southern part. It is not an exact Prairies polygon. No Prairies boundary is inferred from provinces, a latitude cut or adjacent unnamed divisions.',
            'Label anchors are cartographic positions verified inside each source feature; they are not observation locations.',
            'Catalogue publication, temporal coverage and catalogue modification dates are distinct. The separately linked historical map does not establish a reference year for these vectors.',
        ],
    }
    return {'landforms.geojson': output_raw, 'manifest.json': encode(manifest)}, manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--check', action='store_true', help='Validate pinned sources and compare generated artifacts without writing')
    args = parser.parse_args()
    root = args.repo.resolve()
    files, manifest = prepare(root)
    destination = root / OUTPUT
    if not args.check:
        destination.mkdir(parents=True, exist_ok=True)
    for filename, raw in files.items():
        path = destination / filename
        if args.check:
            if not path.exists() or path.read_bytes() != raw:
                raise ValueError('Generated artifact differs from pinned-source reproduction: ' + str(path))
        else:
            path.write_bytes(raw)
    print(json.dumps({
        'mode': 'check' if args.check else 'prepare',
        'featureCount': manifest['geometry']['featureCount'],
        'regionFeatureCount': 7,
        'divisionFeatureCount': 1,
        'rockiesExactDivision': 78,
        'validGeometries': manifest['validation']['validGeometries'],
        'unintendedOverlapPairs': 0,
        'geometrySha256': manifest['geometry']['sha256'],
    }))


if __name__ == '__main__':
    try:
        main()
    except (ValueError, KeyError, StopIteration) as error:
        print('Canada named landform preparation failed: ' + str(error), file=sys.stderr)
        sys.exit(1)
