import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {bundleCanadaSource} from '../fixtures/bundle-canada-source.mjs';
const json=async p=>JSON.parse(await readFile(p,'utf8'));const water=await json('src/data/atlas/canada/water-resources.json');const industry=await json('src/data/atlas/canada/industry-parity.json');const basins=await json('public/assets/atlas/canada-water-v1/river-basins.geojson');
const mod=async p=>import('data:text/javascript;base64,'+Buffer.from(await bundleCanadaSource(p,{format:'esm',platform:'node'})).toString('base64'));
test('Canada reuses every available US climate code color and all seven precipitation bands',async()=>{const shared=await mod('src/lib/atlas-canada-presentation.ts');const us=await json('public/assets/atlas/nature-v1/climate-legend.json');const ca=await json('public/assets/atlas/canada-climate-elevation-v1/koppen-manifest.json');const groups=shared.canadaClimateGroups(ca.classes);for(const g of groups){const ref=us.find(u=>u.code===g.id);if(ref)assert.equal(g.color,ref.color,g.id);}assert.deepEqual(water.datasets.precipitation.groups.map(({id,name,color})=>({id,name,color})),shared.canadaPrecipitationPresentation);});
function inRing(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))inside=!inside;}return inside;}
function contains(f,p){const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;return polygons.some(r=>inRing(p,r[0])&&!r.slice(1).some(h=>inRing(p,h)));}
test('Named catchments contain independent river-valley points and preserve international/tributary topology',()=>{const byId=new Map(basins.features.map(f=>[f.properties.id,f]));const points={mackenzie:[-117.3,56.23],fraser:[-122.75,53.9],columbia:[-117.4,47.65],nelson:[-97.1,49.9],'st-lawrence':[-79.4,43.7],'saint-john':[-66.64,45.96],saskatchewan:[-106.67,52.15]};for(const [id,p]of Object.entries(points))assert.ok(contains(byId.get(id),p),id);assert.equal(contains(byId.get('mackenzie'),[-113.5,53.5]),false,'Edmonton drains through the Saskatchewan/Nelson system');assert.ok(contains(byId.get('saskatchewan'),[-113.5,53.5]));assert.ok(contains(byId.get('nelson'),points.saskatchewan));assert.equal(byId.get('saskatchewan').properties.parent,'nelson');assert.ok(contains(byId.get('columbia'),[-117.4,47.65]),'US Spokane remains in the cross-border Columbia catchment');assert.equal(byId.size,7);assert.ok(basins.features.every(f=>f.properties.sourceIds.length>0));});
test('New basin and rain artifacts match their processing manifests',async()=>{for(const manifestPath of ['river-basins-manifest.json','shared-palette-manifest.json']){const manifest=await json('public/assets/atlas/canada-water-v1/'+manifestPath);const outputs=manifest.outputs??[{file:'river-basins.geojson',sha256:manifest.sha256}];for(const row of outputs)assert.equal(createHash('sha256').update(await readFile('public/assets/atlas/canada-water-v1/'+row.file)).digest('hex'),row.sha256,row.file);}});
test('Industry GDP aggregation has no invented residual or missing-as-zero employment',()=>{const total=industry.metrics[0];assert.equal(industry.year,2021);assert.equal(industry.nationalChart.length,12);assert.ok(Math.abs(industry.nationalChart.reduce((s,r)=>s+r.gdp,0)-total.gdp)<20);assert.ok(Math.abs(industry.nationalChart.reduce((s,r)=>s+r.employment,0)-total.employment)<2);for(const m of industry.metrics){assert.equal(m.provinces.length,13);assert.ok(Math.abs(m.provinces.reduce((s,p)=>s+p.gdp,0)-m.gdp)<.01);assert.ok(m.provinces.every(p=>Number.isFinite(p.gdp)&&p.gdp>=0));}assert.equal(industry.metrics.find(m=>m.id==='auto').employment,null);assert.equal([...industry.metrics.find(m=>m.id==='auto').provinces].sort((a,b)=>b.gdp-a.gdp)[0].id,'Ontario');});
