import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {transform} from 'esbuild';import sharp from 'sharp';
const data=JSON.parse(await readFile('src/data/atlas/canada/forestry.json','utf8')),manifest=JSON.parse(await readFile('public/assets/atlas/canada-forestry-v1/manifest.json','utf8')),parse=l=>[...l.matchAll(/"((?:[^"]|"")*)"(?:,|$)/g)].map(m=>m[1].replaceAll('""','"'));
const lib=await import(`data:text/javascript;base64,${Buffer.from((await transform(await readFile('src/lib/atlas-canada-forestry.ts','utf8'),{loader:'ts',format:'esm'})).code).toString('base64')}`);
test('Forestry selection retains 66 original nominal manufacturing revenues, 20 confidential values, quality and vectors',async()=>{
 const lines=(await readFile('data-source/atlas/canada/agriculture/forestry/forestry-selected.csv','utf8')).trim().split(/\r?\n/),headers=parse(lines.shift());assert.equal(lines.length,66);assert.equal(data.data.length,33);let suppressed=0;
 for(const line of lines){const r=Object.fromEntries(parse(line).map((v,i)=>[headers[i],v])),m=data.metrics.find(m=>m.source===r['North American Industry Classification System (NAICS)']);assert.ok(m);assert.equal(r['Principal statistics'],'Revenue from goods manufactured');assert.equal(r.UOM,'Dollars');assert.equal(r.SCALAR_FACTOR,'thousands');assert.ok(['2021','2023','2024'].includes(r.REF_DATE));const v=data.data.find(v=>String(v.year)===r.REF_DATE&&v.id===r.GEO).values[m.id];assert.equal(v.value,r.VALUE===''?null:Number(r.VALUE));assert.equal(v.status,r.STATUS);assert.equal(v.symbol,r.SYMBOL);assert.equal(v.vector,r.VECTOR);assert.equal(v.decimals,Number(r.DECIMALS));if(r.STATUS==='x'){suppressed++;assert.equal(v.value,null);}}
 assert.equal(suppressed,20);assert.equal(data.data.find(r=>r.year===2024&&r.id==='British Columbia').values.wood.value,10916312);assert.equal(data.data.find(r=>r.year===2024&&r.id==='Quebec').values.paper.value,11928895);assert.equal(data.data.find(r=>r.year===2024&&r.id==='Manitoba').values.paper.status,'x');assert.equal(manifest.statistics.releaseDate,'2025-12-18');assert.equal(manifest.statistics.suppressed,20);
});
test('Forest masks follow source BigTIFF class colors, isolate actual pixels and never derive forest area',async()=>{
 const folder='data-source/atlas/canada/agriculture/forestry',b=await readFile(`${folder}/landcover-2020-cog-header.bin`);assert.equal(b.readUInt16LE(2),43);let off=Number(b.readBigUInt64LE(8)),n=Number(b.readBigUInt64LE(off)),palette;for(let i=0;i<n;i++){const p=off+8+i*20;if(b.readUInt16LE(p)===320)palette=Number(b.readBigUInt64LE(p+12));}assert.ok(palette);
 const src=await sharp(`${folder}/landcover-2020-wms.png`).ensureAlpha().raw().toBuffer(),all=await sharp('public/assets/atlas/canada-forestry-v1/forest-all-2020.png').ensureAlpha().raw().toBuffer(),hash=b=>createHash('sha256').update(b).digest('hex');let forestPixels=0;
 for(const c of data.classes){assert.deepEqual(c.color,[0,1,2].map(k=>b.readUInt16LE(palette+(k*256+c.code)*2)/257));const pixels=await sharp(`public/assets/atlas/canada-forestry-v1/forest-${c.id}-2020.png`).ensureAlpha().raw().toBuffer();let count=0;for(let i=0;i<src.length;i+=4){const matches=src[i+3]&&c.color.every((v,j)=>src[i+j]===v);assert.equal(pixels[i+3],matches?255:0);if(matches){assert.deepEqual(pixels.subarray(i,i+4),src.subarray(i,i+4));count++;}}assert.equal(count,manifest.forest.forestClassPixels[c.id]);forestPixels+=count;}
 let allCount=0;for(let i=0;i<all.length;i+=4){const matches=src[i+3]&&data.classes.some(c=>c.color.every((v,j)=>src[i+j]===v));assert.equal(all[i+3],matches?255:0);if(matches)allCount++;}assert.equal(allCount,forestPixels);assert.equal(manifest.forest.unknownPixels,0);assert.equal(manifest.forest.year,2020);assert.equal(manifest.forest.sourceResolutionMetres,30);assert.deepEqual(manifest.forest.bboxLonLat,[-145,40,-50,85]);assert.match(manifest.forest.method,/not hectare estimates/);
 for(const m of manifest.forest.mapAssets)assert.equal(m.sha256,hash(await readFile(`public/assets/atlas/canada-forestry-v1/${m.file}`)));assert.equal(manifest.selectedCsvSha256,hash(await readFile('public/assets/atlas/canada-forestry-v1/forestry-selected.csv')));
});
test('Forestry URL keeps fixed cover, independent statistics and local nature return while validating invalid states',()=>{
 const ids=data.provinces.map(p=>p.id),url=new URL('https://example.com/insight-journal/atlas/north-america/canada/agriculture/forestry/?year=2021&province=Quebec&compare=Ontario&metric=paper&cover=taiga&region=quebec&zoom=1&keep=1'),state=lib.readCanadaForestryState(url,data.years,ids);assert.deepEqual(state,{year:2021,province:'Quebec',compare:'Ontario',metric:'paper',cover:'taiga',region:'quebec',zoom:true,camera:null});const saved=lib.writeCanadaForestryState(url,state);assert.equal(saved.searchParams.get('keep'),'1');assert.deepEqual(lib.readCanadaForestryState(saved,data.years,ids),state);
 const target=lib.canadaForestryComparisonUrl(saved,new URL('https://example.com/insight-journal/atlas/north-america/canada/nature/?city=vancouver&view=water&water=Fraser&only=1'),state),returnParams=new URLSearchParams(target.searchParams.get('forestryReturn'));assert.equal(target.searchParams.get('city'),'vancouver');assert.equal(target.searchParams.get('water'),'Fraser');assert.equal(returnParams.get('cover'),'taiga');assert.equal(returnParams.has('keep'),false);assert.equal(returnParams.has('city'),false);
 assert.deepEqual(lib.readCanadaForestryState(new URL('https://example.com/?year=1999&province=bad&compare=British+Columbia&metric=harvest&cover=wetland&region=unknown'),data.years,ids),{year:2024,province:null,compare:'British Columbia',metric:'wood',cover:'all',region:null,zoom:false,camera:null});assert.equal(lib.formatCanadaForestryValue(0),'0');assert.equal(lib.formatCanadaForestryValue(null),'欠測');
});
