import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {readCanadaPopulationState,writeCanadaPopulationState,formatCanadaPopulationValue,canadaPopulationNatureUrl,canadaPopulationDensityColor,canadaPopulationFrame} from '../../src/lib/atlas-canada-population.ts';
import {readZipEntries,parseDbf,readShapeRecords,inverseCanadaLambert,forwardCanadaLambert,pointInRings,signedRingArea,simplifyRing} from '../../scripts/lib/canada-geography.mjs';
const data=JSON.parse(await readFile('src/data/atlas/canada/population.json','utf8')),geometry=JSON.parse(await readFile('src/data/atlas/canada/population-geometry.json','utf8')),manifest=JSON.parse(await readFile('public/assets/atlas/canada-population-v1/manifest.json','utf8'));
const parse=line=>{const row=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else value+=c;}row.push(value);return row;};
test('Population retains every original census value and its own Symbols column for 41 CMA and 14 national/provincial records',async()=>{
 let values=0,revised=0;for(const [file,records] of [['98100003.csv',data.cmas],['98100001.csv',data.national]]){const rows=(await readFile(`data-source/atlas/canada/population/${file}`,'utf8')).trim().split(/\r?\n/).slice(1).map(parse);for(const r of records){const raw=rows.find(a=>a[2]===r.dguid);assert.ok(raw);for(const [cell,index] of [[r.population[2021],4],[r.population[2016],6],[r.changePercent,8],[r.landAreaKm2,22],[r.density2021,24]]){assert.equal(cell.value,raw[index]===''?null:Number(raw[index]));assert.equal(cell.symbol,raw[index+1]);values++;if(cell.symbol==='r')revised++;}}}
 assert.equal(values,275);assert.ok(revised>0);assert.equal(data.cmas.length,41);assert.equal(data.national.length,14);assert.equal(data.cmas.filter(r=>r.id==='505').length,1);assert.equal(data.cmas.find(r=>r.id==='505').population[2021].value,1488307);assert.equal(data.cmas.find(r=>r.id==='462').population[2016].symbol,'r');assert.ok(data.national.find(r=>r.id==='Canada').notes.includes(2));assert.ok(data.cmas.find(r=>r.id==='462').notes.includes(2));assert.deepEqual(data.cmaTotal,{2016:25716855,2021:27281119});assert.equal(data.cmaTotal[2021]/36991981*100,data.cmaShare2021);
});
test('Official geometry preserves all rings and holes, combines two Ottawa–Gatineau pieces and has correct geographic alignment',async()=>{
 const entries=readZipEntries(await readFile('data-source/atlas/canada/population/lcma000b21a_e.zip')),file=ext=>[...entries].find(([name])=>name.endsWith(ext))[1],dbf=parseDbf(file('.dbf')),shapes=readShapeRecords(file('.shp'));
 const selected=dbf.map((d,i)=>({d,s:shapes[i]})).filter(r=>r.d.CMATYPE==='B');assert.equal(selected.length,42);assert.equal(geometry.features.length,41);assert.equal(selected.reduce((n,r)=>n+r.s.rings.length,0),2519);assert.equal(geometry.features.reduce((n,r)=>n+r.rings.length,0),2519);const og=geometry.features.find(g=>g.id==='505');assert.deepEqual(new Set(og.provinceCodes),new Set(['24','35']));assert.equal(og.sourcePieces,2);
 for(const g of geometry.features){const original=selected.filter(r=>r.d.CMAUID===g.id).flatMap(r=>r.s.rings);assert.equal(g.rings.length,original.length);assert.ok(pointInRings(forwardCanadaLambert(g.anchor),original));for(let i=0;i<g.rings.length;i++){const ring=g.rings[i];assert.ok(ring.length>=4);assert.deepEqual(ring[0],ring.at(-1));assert.equal(Math.sign(signedRingArea(ring)),Math.sign(signedRingArea(original[i])));for(const p of [ring[0],ring[Math.floor(ring.length/2)]])assert.ok(p[0]>=-145&&p[0]<=-50&&p[1]>=40&&p[1]<=85);}}
 const origin=inverseCanadaLambert([6200000,3000000]);assert.ok(Math.abs(origin[0]+91.86666666666666)<1e-10);assert.ok(Math.abs(origin[1]-63.390675)<1e-10);assert.ok(manifest.geometry.maxRoundTripMetres<0.001);assert.ok(manifest.geometry.spotChecks.every(s=>s.insideOriginal));assert.match(file('.xml').toString('utf8'),/Open Government Licence/);
 const geojson=JSON.parse(await readFile('public/assets/atlas/canada-population-v1/population-boundaries.geojson','utf8'));for(const f of geojson.features){assert.equal(f.geometry.type,'MultiPolygon');for(const polygon of f.geometry.coordinates){assert.ok(signedRingArea(polygon[0])>0);for(const hole of polygon.slice(1))assert.ok(signedRingArea(hole)<0);}}assert.equal(geojson.features.find(f=>f.properties.CMAUID==='505').properties.sourcePieces,2);
});
test('Display simplification respects its original metre tolerance, closure and ring orientation',async()=>{
 const entries=readZipEntries(await readFile('data-source/atlas/canada/population/lcma000b21a_e.zip')),b=[...entries].find(([name])=>name.endsWith('.shp'))[1],records=readShapeRecords(b);const rings=records.flatMap(r=>r.rings).filter(r=>r.length>1000).slice(0,8);let max=0;
 for(const original of rings){const simplified=simplifyRing(original,250);assert.deepEqual(simplified[0],original[0]);assert.deepEqual(simplified.at(-1),original.at(-1));assert.equal(Math.sign(signedRingArea(simplified)),Math.sign(signedRingArea(original)));let cursor=0;for(let k=0;k<simplified.length-1;k++){const a=simplified[k],b=simplified[k+1];let last=cursor+1;while(last<original.length&&!(original[last][0]===b[0]&&original[last][1]===b[1]))last++;assert.ok(last<original.length);for(let i=cursor;i<=last;i++){const p=original[i],dx=b[0]-a[0],dy=b[1]-a[1],t=dx||dy?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy))):0;max=Math.max(max,Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy));}cursor=last;}}
 assert.ok(max<=250.000001);assert.ok(max>0);
});
test('Population URL validates metrics and dates, preserves unrelated queries and creates a local return state',()=>{
 const ids=data.cmas.map(r=>r.id),url=new URL('https://example.com/insight-journal/atlas/north-america/canada/population/?year=2016&cma=505&compare=535&metric=population&only=1&zoom=selected&keep=yes'),state=readCanadaPopulationState(url,ids);assert.deepEqual(state,{year:2016,cma:'505',compare:'535',metric:'population',only:true,zoom:'selected'});const saved=writeCanadaPopulationState(url,state);assert.equal(saved.searchParams.get('keep'),'yes');assert.deepEqual(readCanadaPopulationState(saved,ids),state);const target=canadaPopulationNatureUrl(saved,new URL('https://example.com/insight-journal/atlas/north-america/canada/nature/?city=ottawa&view=water&water=Lake+Ontario&only=1'),state),back=new URLSearchParams(target.searchParams.get('populationReturn'));assert.equal(back.get('cma'),'505');assert.equal(back.get('year'),'2016');assert.equal(back.has('keep'),false);assert.equal(target.searchParams.get('water'),'Lake Ontario');
 assert.deepEqual(readCanadaPopulationState(new URL('https://example.com/?year=2016&metric=density&cma=bad&compare=535&zoom=bad'),ids),{year:2021,cma:'535',compare:null,metric:'density',only:false,zoom:'south'});assert.equal(formatCanadaPopulationValue(0),'0');assert.equal(formatCanadaPopulationValue(null),'未公表');assert.equal(formatCanadaPopulationValue(0,'density'),'0.0');assert.notEqual(canadaPopulationDensityColor(null),canadaPopulationDensityColor(0));for(const r of geometry.features){const b=r.bounds;assert.ok(b[0]>=140&&b[1]>=340&&b[2]<=900&&b[3]<=580);}assert.deepEqual(canadaPopulationFrame({...state,zoom:'country'},geometry.features),[0,0,900,580]);
});
test('Public population extracts and official sources match their reproducible SHA-256 ledger',async()=>{
 const hash=b=>createHash('sha256').update(b).digest('hex');for(const source of manifest.sources){const b=await readFile(`data-source/atlas/canada/population/${source.file}`);assert.equal(b.length,source.bytes);assert.equal(hash(b),source.sha256);assert.match(source.url,/^https:\/\/www1[25]0?\.statcan\.gc\.ca\//);}for(const asset of manifest.assets){const b=await readFile(`public/assets/atlas/canada-population-v1/${asset.file}`);assert.equal(b.length,asset.bytes);assert.equal(hash(b),asset.sha256);}assert.equal(manifest.statistics.densityYear,2021);assert.equal(manifest.statistics.releaseDate,'2022-02-09');assert.match(manifest.geometry.method,/no area\/density estimation/);
});
