import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {demographicComposition} from '../../src/lib/atlas-canada-concentration.ts';
const load=t=>JSON.parse(fs.readFileSync(`src/data/atlas/canada/profile-${t}.json`)),religion=load('religion'),ethnicity=load('ethnicity');
test('Official profile covers 293 CDs and 41 CMAs with 23 religious leaves, no Christian parent duplication',()=>{
 for(const d of [religion,ethnicity]){assert.equal(d.regions.length,293);assert.equal(d.cmas.length,41);assert.equal(new Set(d.regions.map(r=>r.dguid)).size,293);for(const r of [...d.regions,...d.cmas,d.national])for(const g of d.groups){const c=r.values[g.id];assert.ok(c);assert.ok(c.value===null||c.value>=0&&c.value<=r.denominator.value);}}
 assert.equal(religion.groups.length,23);assert.equal(religion.groups.some(g=>g.id==='3'),false);assert.equal(religion.national.values['8'].value,10880360);assert.equal(religion.national.values['11'].value,87725);
 for(const r of religion.regions){if(Object.values(r.values).every(c=>c.value!==null))assert.ok(Math.abs(Object.values(r.values).reduce((n,c)=>n+c.value,0)-r.denominator.value)<=100,r.name);}
 assert.match(ethnicity.groups.find(g=>g.id==='3').name,/可視的少数者/);assert.match(ethnicity.groups.find(g=>g.id==='87').name,/別集計/);
});
test('A characteristic minority can be primary instead of a local majority; missing remains unclassified',()=>{
 const data={groups:[{id:'8'},{id:'11'},{id:'25'}],national:{denominator:{value:10000},values:{8:{value:3000},11:{value:25},25:{value:4000}}}},r={denominator:{value:10000},values:{8:{value:6000},11:{value:600},25:{value:3400}}};const c=demographicComposition(r,data,'religion');assert.equal(c.primary.id,'11');assert.equal(c.primary.share,6);assert.equal(c.primary.ratio,24);assert.equal(c.qualified.length,2);r.values['11']={value:null,symbol:'x'};assert.equal(demographicComposition(r,data,'religion').primary,null);
});
test('No-religion remains in composition but cannot mask distinctive denominations',()=>{const c=demographicComposition(religion.cmas.find(r=>r.id==='933'),religion,'religion');assert.ok(c.rows.find(g=>g.id==='25').share>40);assert.ok(c.qualified.every(g=>g.id!=='25'));});
test('Public profile assets retain their audited source hashes and unique geographic join',()=>{const m=JSON.parse(fs.readFileSync('public/assets/atlas/canada-demographics-v2/manifest.json'));for(const [p,x] of Object.entries(m.outputs)){const b=fs.readFileSync(p);assert.equal(b.length,x.bytes);assert.equal(createHash('sha256').update(b).digest('hex'),x.sha256);}const geo=JSON.parse(fs.readFileSync('public/assets/atlas/canada-demographics-v2/regions.geojson'));assert.equal(geo.features.length,293);assert.equal(new Set(geo.features.map(f=>f.id)).size,293);for(const f of geo.features)assert.equal(ethnicity.regions.find(r=>r.id===f.id).dguid,f.properties.dguid);});
